"""The single ``COMPLICATION_TYPE_*`` table (``Toybox/Complications.html``).

Every complication type the SDK exposes, in one place, because two different
things in this compiler both need to resolve a name to a real
``Complications.Type`` constant and it must be the same table for both:

* **A launch target.** Tapping an element on a watch face cannot open an
  arbitrary app: the platform offers exactly one door,
  ``Complications.exitTo(id)``, documented as "launches the app associated
  with the complication" (API level 4.2.0). An interactive element names a
  **complication type**, and the watch opens whatever glance or app owns
  that type -- Body Battery opens Garmin's Body Battery glance, and so on.
  ``on_hold:`` (and a carousel item's ``launch:``) both resolve here.
* **A data source.** ``wfb.catalog``'s ``complication.<name>`` sources
  (``complication.body_battery``, ``complication.sleep_score``, ...) are
  generated by looping over this same table -- see ``catalog.py``'s
  ``CATALOG`` construction. Reading a complication's *value* and launching
  its glance are different questions about the same 42 platform concepts,
  so this module answers both rather than keeping two tables that could
  drift apart.

``wfb.catalog`` imports this module; this module must **not** import
``wfb.catalog`` back (that would be circular).

Generated by reading the ``COMPLICATION_TYPE_*`` "Type" constant table in
``$CIQ_SDK/doc/Toybox/Complications.html`` (rendered to text with
``tools/research/h2t.py``) rather than typed from memory -- the same
discipline :mod:`wfb.catalog` follows, and for the same reason: a name is a
claim about a symbol that exists, and it should be checked. ``value_type``,
``nullable`` and ``doc`` below are transcribed **verbatim** from that table's
"Description" column (with only the leading "Value is a(n) " trimmed from
``doc`` -- the type and nullability already say that).

``since`` is the API level that *type* was added, which is not the same as
the device supporting it -- a device's own ConnectIQ ceiling can sit below
it (see ``activity.sleep_score`` -> ``complication.sleep_score`` in
:mod:`wfb.catalog` for a concrete case: ``COMPLICATION_TYPE_SLEEP_SCORE``
needs 6.0.2, above fr955's own 5.2.0 ceiling). A hold on a type the watch
does not know simply does nothing; it is not a crash --
``WfbComplications.mc``'s ``subscribe()`` catches both ways a device can
decline a type (``subscribeToUpdates`` returning ``false`` or throwing
``ComplicationNotFoundException``).

Two types' documented value type changed across API levels -- ``ALTITUDE``
was ``Number`` before 5.1.0, ``CURRENT_TEMPERATURE`` was ``Number`` before
5.0.0. Both this project's targets (fenix8solar47mm/51mm, fr955) sit above
both levels (see CLAUDE.md's device table), so ``value_type`` below is the
*current* ``"float"`` for each, not the historical ``"number"`` -- there is
no device this project targets that would ever see the old shape.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ComplicationType:
    """One ``COMPLICATION_TYPE_*`` the SDK exposes.

    Used both as an ``on_hold:``/``launch:`` target and as the type behind a
    ``complication.<name>`` catalogue source.
    """

    #: The spelling used in a design file: the constant, lowercased.
    name: str
    #: The Monkey C constant, emitted as ``Complications.<constant>``.
    constant: str
    #: The API level this type was introduced at.
    since: str
    #: "number" / "float" / "string" -- plain strings, not `catalog.Type`,
    #: because this module must not import `wfb.catalog` (circular). Callers
    #: map onto `catalog.Type` themselves; see `catalog.py`'s generated
    #: `complication.*` sources.
    value_type: str
    #: Transcribed from the SDK's own Type table: does that table's
    #: description end "...or null"? Kept for documentation accuracy even
    #: though every generated `complication.*` Source is `nullable=True`
    #: regardless -- `Complications.getComplication(id)` itself returns
    #: null whenever the device does not support the type, so the generated
    #: guard is unconditional either way (see catalog.py's comment on this).
    nullable: bool
    #: SDK-documented unit, or None when the description names none.
    #: Distances metres, pressure pascals, temperature Celsius, sunrise/
    #: sunset "seconds since local midnight", race predictors seconds, race
    #: pace metres/second, percentages percent.
    unit: str | None
    #: The Type table's own description, verbatim (leading "Value is a(n) "
    #: trimmed -- value_type/nullable already say that part).
    doc: str


def _t(name: str, constant: str, since: str, value_type: str, nullable: bool,
       unit: str | None, doc: str) -> ComplicationType:
    return ComplicationType(name, constant, since, value_type, nullable, unit, doc)


#: The API level ``Complications.exitTo`` itself needs, independent of the
#: type named -- Toybox/Complications.html.
EXIT_TO_API_LEVEL = "4.2.0"

#: ``Toybox.Complications`` is gated by this permission, and the SDK's own
#: table (Core_Topics/Manifest_and_Permissions.html) marks it available to a
#: Watch Face -- checked directly, not assumed.
EXIT_TO_PERMISSION = "ComplicationSubscriber"

#: Every complication type, keyed by the name a design writes. All 42 real
#: ``COMPLICATION_TYPE_*`` values (``COMPLICATION_TYPE_INVALID`` is not a
#: value and is excluded) -- transcribed from
#: ``$CIQ_SDK/doc/Toybox/Complications.html``'s "Type" constant table.
TYPES: dict[str, ComplicationType] = {t.name: t for t in [
    _t('battery', 'COMPLICATION_TYPE_BATTERY', '4.2.0', 'number', True, 'percent',
       'a non-negative Number percent 0 to 100 representing battery charge'),
    _t('steps', 'COMPLICATION_TYPE_STEPS', '4.2.0', 'number', False, None,
       'a non-negative Number of steps for the current day, not available in '
       'wheelchair mode'),
    _t('calories', 'COMPLICATION_TYPE_CALORIES', '4.2.0', 'number', False, None,
       'a non-negative Number of calories burned for the current day'),
    _t('floors_climbed', 'COMPLICATION_TYPE_FLOORS_CLIMBED', '4.2.0', 'number', False, None,
       'a non-negative Number of floors climbed, not available in wheelchair mode'),
    _t('intensity_minutes', 'COMPLICATION_TYPE_INTENSITY_MINUTES', '4.2.0', 'number', False, None,
       'a non-negative Number of intensity minutes that resets weekly'),
    _t('date', 'COMPLICATION_TYPE_DATE', '4.2.0', 'string', False, None,
       'a String with the day of the month and the month e.g., 28 Mar'),
    _t('weekday_monthday', 'COMPLICATION_TYPE_WEEKDAY_MONTHDAY', '4.2.0', 'string', False, None,
       'a String with the day of the week and the day of the month e.g., Mon 28'),
    _t('current_weather', 'COMPLICATION_TYPE_CURRENT_WEATHER', '4.2.0', 'number', False, None,
       'a Weather.CONDITION_* for the current weather'),
    _t('forecast_weather_1day', 'COMPLICATION_TYPE_FORECAST_WEATHER_1DAY', '4.2.0', 'number', False, None,
       'a Weather.CONDITION_* for the forecast weather one day in the future'),
    _t('forecast_weather_2day', 'COMPLICATION_TYPE_FORECAST_WEATHER_2DAY', '4.2.0', 'number', False, None,
       'a Weather.CONDITION_* for the forecast weather two days in the future'),
    _t('forecast_weather_3day', 'COMPLICATION_TYPE_FORECAST_WEATHER_3DAY', '4.2.0', 'number', False, None,
       'a Weather.CONDITION_* for the forecast weather three days in the future'),
    _t('calendar_events', 'COMPLICATION_TYPE_CALENDAR_EVENTS', '4.2.0', 'string', True, None,
       'a String with the time of your next calendar event'),
    _t('sunrise', 'COMPLICATION_TYPE_SUNRISE', '4.2.0', 'number', True, 'seconds since local midnight',
       'a non-negative Number representing seconds since midnight local time of the sunrise'),
    _t('sunset', 'COMPLICATION_TYPE_SUNSET', '4.2.0', 'number', True, 'seconds since local midnight',
       'a non-negative Number representing seconds since midnight local time of the sunset'),
    # Prior to ConnectIQ API version 5.1.0, the value was a Number -- both
    # this project's targets are above that level (see module docstring),
    # so value_type is the current Float.
    _t('altitude', 'COMPLICATION_TYPE_ALTITUDE', '4.2.0', 'float', True, 'meters',
       'a Float of the current altitude in meters'),
    _t('sea_level_pressure', 'COMPLICATION_TYPE_SEA_LEVEL_PRESSURE', '4.2.0', 'float', True, 'pascals',
       'a Float in pascals of the current pressure'),
    _t('notification_count', 'COMPLICATION_TYPE_NOTIFICATION_COUNT', '4.2.0', 'number', True, None,
       'a non-negative Number of notifications'),
    _t('heart_rate', 'COMPLICATION_TYPE_HEART_RATE', '4.2.0', 'number', True, 'beats per minute',
       'a non-negative Number in beats per minute'),
    _t('weekly_run_distance', 'COMPLICATION_TYPE_WEEKLY_RUN_DISTANCE', '4.2.0', 'float', False, 'meters',
       'a Float of your weekly run distance in meters'),
    _t('weekly_bike_distance', 'COMPLICATION_TYPE_WEEKLY_BIKE_DISTANCE', '4.2.0', 'float', False, 'meters',
       'a Float of your weekly bike distance in meters'),
    _t('recovery_time', 'COMPLICATION_TYPE_RECOVERY_TIME', '4.2.0', 'number', False, None,
       'a Number of minutes remaining in your recovery time'),
    _t('stress', 'COMPLICATION_TYPE_STRESS', '4.2.0', 'number', True, None,
       'a Number representing your current stress level'),
    _t('body_battery', 'COMPLICATION_TYPE_BODY_BATTERY', '4.2.0', 'number', True, None,
       'a Number representing your current body battery'),
    _t('vo2max_run', 'COMPLICATION_TYPE_VO2MAX_RUN', '4.2.0', 'number', True, None,
       'a Number representing your running VO2 max'),
    _t('vo2max_bike', 'COMPLICATION_TYPE_VO2MAX_BIKE', '4.2.0', 'number', True, None,
       'a Number representing your cycling VO2 max'),
    _t('training_status', 'COMPLICATION_TYPE_TRAINING_STATUS', '4.2.0', 'string', False, None,
       'a String representing your training status'),
    _t('race_predictor_5k', 'COMPLICATION_TYPE_RACE_PREDICTOR_5K', '4.2.0', 'number', False, 'seconds',
       'a Number representing your predicted 5K time in seconds'),
    _t('race_predictor_10k', 'COMPLICATION_TYPE_RACE_PREDICTOR_10K', '4.2.0', 'number', False, 'seconds',
       'a Number representing your predicted 10k time in seconds'),
    _t('race_predictor_half_marathon', 'COMPLICATION_TYPE_RACE_PREDICTOR_HALF_MARATHON', '4.2.0',
       'number', False, 'seconds',
       'a Number representing your predicted half marathon time in seconds'),
    _t('race_predictor_marathon', 'COMPLICATION_TYPE_RACE_PREDICTOR_MARATHON', '4.2.0', 'number', False,
       'seconds', 'a Number representing your predicted your marathon time in seconds'),
    _t('race_pace_predictor_5k', 'COMPLICATION_TYPE_RACE_PACE_PREDICTOR_5K', '4.2.0', 'float', False,
       'meters/second', 'a Float representing your 5k pace in meters/second'),
    _t('race_pace_predictor_10k', 'COMPLICATION_TYPE_RACE_PACE_PREDICTOR_10K', '4.2.0', 'float', False,
       'meters/second', 'a Float representing your 10k pace in meters/second'),
    _t('race_pace_predictor_half_marathon', 'COMPLICATION_TYPE_RACE_PACE_PREDICTOR_HALF_MARATHON',
       '4.2.0', 'float', False, 'meters/second',
       'a Float representing your half marathon pace in meters/second'),
    _t('race_pace_predictor_marathon', 'COMPLICATION_TYPE_RACE_PACE_PREDICTOR_MARATHON', '4.2.0',
       'float', False, 'meters/second', 'a Float representing your marathon pace in meters/second'),
    _t('pulse_ox', 'COMPLICATION_TYPE_PULSE_OX', '4.2.0', 'number', True, 'percent',
       'a non-negative Number as a percent from 0 to 100 representing your blood oxygen'),
    _t('respiration_rate', 'COMPLICATION_TYPE_RESPIRATION_RATE', '4.2.0', 'number', True,
       'breaths per minute', 'a non-negative Number representing your breaths per minute'),
    _t('solar_input', 'COMPLICATION_TYPE_SOLAR_INPUT', '4.2.0', 'number', True, 'percent',
       'a non-negative Number representing percent between 0 to 100 of solar charge'),
    # Prior to ConnectIQ API version 5.0.0, the value was a Number -- both
    # this project's targets are above that level (see module docstring),
    # so value_type is the current Float.
    _t('current_temperature', 'COMPLICATION_TYPE_CURRENT_TEMPERATURE', '4.2.0', 'float', True,
       'degrees Celsius', 'a Float representing temperature in degrees Celsius'),
    _t('high_low_temperature', 'COMPLICATION_TYPE_HIGH_LOW_TEMPERATURE', '4.2.0', 'string', False, None,
       'a String providing the high and low temperature values in a format similar to '
       '"H <high> / L <low>"'),
    _t('wheelchair_pushes', 'COMPLICATION_TYPE_WHEELCHAIR_PUSHES', '4.2.3', 'number', False, None,
       'a non-negative Number of pushes for the current day, only available in wheelchair mode'),
    _t('last_golf_round_score', 'COMPLICATION_TYPE_LAST_GOLF_ROUND_SCORE', '5.0.0', 'string', False, None,
       'a String in the format "<LastRoundTotalScore>(<Offset>)" where Offset is "E" for '
       'even-par, a negative value for under par, or a positive value for over par'),
    _t('sleep_score', 'COMPLICATION_TYPE_SLEEP_SCORE', '6.0.2', 'number', True, None,
       'a non-negative number from 0 to 100 representing sleep score'),
]}


#: `Complications.Unit` (`Toybox/Complications.html`'s own "Unit" constant
#: table, API 4.2.0) mapped to a short display suffix, transcribed from that
#: table's own description column ("value is in meters", "meters/second",
#: "degrees Celsius", "grams"). Used only by a `complication_slot` element's
#: `unit: true` -- `Complications.Complication.unit` comes back typed
#: `Complications.Unit or Lang.String or Null`, i.e. either this enum or a
#: literal string a *user* complication supplied directly (see
#: `runtime-lib/WfbComplications.mc`'s `unitSuffix`, which checks `instanceof
#: Lang.String` before falling back to this table). `UNIT_INVALID` is not a
#: real unit and maps to no suffix, the same way `COMPLICATION_TYPE_INVALID`
#: is excluded from :data:`TYPES` above.
UNIT_SUFFIX: dict[str, str] = {
    "UNIT_DISTANCE": "m",
    "UNIT_ELEVATION": "m",
    "UNIT_HEIGHT": "m",
    "UNIT_SPEED": "m/s",
    "UNIT_TEMPERATURE": "°C",
    "UNIT_WEIGHT": "g",
}


def get(name: str) -> ComplicationType | None:
    return TYPES.get(name)


def names() -> list[str]:
    return sorted(TYPES)


def suggest(name: str, limit: int = 3) -> list[str]:
    """Nearest names, for the "misspelled hold target" diagnostic."""
    import difflib

    return difflib.get_close_matches(name, TYPES, n=limit, cutoff=0.5)
