"""Complication types a watch face can *launch* (ADR 0006 §6).

Tapping an element on a watch face cannot open an arbitrary app: the platform
offers exactly one door, ``Complications.exitTo(id)``, documented as "launches
the app associated with the complication" (``Toybox/Complications.html``, API
level 4.2.0).  So an interactive element names a **complication type**, and the
watch opens whatever glance or app owns that type -- Body Battery opens
Garmin's Body Battery glance, and so on.

This is a different question from :mod:`wfb.catalog`'s ``complication_*``
readers, which is why it is a different table.  There, a complication is a
value to *read*, and only nine are worth reading because everything else is
already reachable more cheaply through ``ActivityMonitor``/``Activity``/
``Weather``/``UserProfile``.  Here every type is a valid destination whether or
not the design displays its value, so all 42 are listed.

Generated by reading the ``COMPLICATION_TYPE_*`` table in
``$CIQ_SDK/doc/Toybox/Complications.html`` rather than typed from memory --
the same discipline :mod:`wfb.catalog` follows, and for the same reason: a
name is a claim about a symbol that exists, and it should be checked.

``since`` is the API level that *type* was added, which is not the same as the
device supporting it -- a device's own ConnectIQ ceiling can sit below it (see
``activity.sleep_score`` in :mod:`wfb.catalog` for a concrete case).  A tap on
a type the watch does not know simply does nothing; it is not a crash.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Launchable:
    """One ``COMPLICATION_TYPE_*`` an ``on_hold:`` may name."""

    #: The spelling used in a design file: the constant, lowercased.
    name: str
    #: The Monkey C constant, emitted as ``Complications.<constant>``.
    constant: str
    #: The API level this type was introduced at.
    since: str


def _l(name: str, constant: str, since: str) -> Launchable:
    return Launchable(name, constant, since)


#: The API level ``Complications.exitTo`` itself needs, independent of the
#: type named -- Toybox/Complications.html.
EXIT_TO_API_LEVEL = "4.2.0"

#: ``Toybox.Complications`` is gated by this permission, and the SDK's own
#: table (Core_Topics/Manifest_and_Permissions.html) marks it available to a
#: Watch Face -- checked directly, not assumed.
EXIT_TO_PERMISSION = "ComplicationSubscriber"

#: Every launchable type, keyed by the name a design writes.
LAUNCHABLE: dict[str, Launchable] = {l.name: l for l in [
    _l('battery', 'COMPLICATION_TYPE_BATTERY', '4.2.0'),
    _l('steps', 'COMPLICATION_TYPE_STEPS', '4.2.0'),
    _l('calories', 'COMPLICATION_TYPE_CALORIES', '4.2.0'),
    _l('floors_climbed', 'COMPLICATION_TYPE_FLOORS_CLIMBED', '4.2.0'),
    _l('intensity_minutes', 'COMPLICATION_TYPE_INTENSITY_MINUTES', '4.2.0'),
    _l('date', 'COMPLICATION_TYPE_DATE', '4.2.0'),
    _l('weekday_monthday', 'COMPLICATION_TYPE_WEEKDAY_MONTHDAY', '4.2.0'),
    _l('current_weather', 'COMPLICATION_TYPE_CURRENT_WEATHER', '4.2.0'),
    _l('forecast_weather_1day', 'COMPLICATION_TYPE_FORECAST_WEATHER_1DAY', '4.2.0'),
    _l('forecast_weather_2day', 'COMPLICATION_TYPE_FORECAST_WEATHER_2DAY', '4.2.0'),
    _l('forecast_weather_3day', 'COMPLICATION_TYPE_FORECAST_WEATHER_3DAY', '4.2.0'),
    _l('calendar_events', 'COMPLICATION_TYPE_CALENDAR_EVENTS', '4.2.0'),
    _l('sunrise', 'COMPLICATION_TYPE_SUNRISE', '4.2.0'),
    _l('sunset', 'COMPLICATION_TYPE_SUNSET', '4.2.0'),
    _l('altitude', 'COMPLICATION_TYPE_ALTITUDE', '4.2.0'),
    _l('sea_level_pressure', 'COMPLICATION_TYPE_SEA_LEVEL_PRESSURE', '4.2.0'),
    _l('notification_count', 'COMPLICATION_TYPE_NOTIFICATION_COUNT', '4.2.0'),
    _l('heart_rate', 'COMPLICATION_TYPE_HEART_RATE', '4.2.0'),
    _l('weekly_run_distance', 'COMPLICATION_TYPE_WEEKLY_RUN_DISTANCE', '4.2.0'),
    _l('weekly_bike_distance', 'COMPLICATION_TYPE_WEEKLY_BIKE_DISTANCE', '4.2.0'),
    _l('recovery_time', 'COMPLICATION_TYPE_RECOVERY_TIME', '4.2.0'),
    _l('stress', 'COMPLICATION_TYPE_STRESS', '4.2.0'),
    _l('body_battery', 'COMPLICATION_TYPE_BODY_BATTERY', '4.2.0'),
    _l('vo2max_run', 'COMPLICATION_TYPE_VO2MAX_RUN', '4.2.0'),
    _l('vo2max_bike', 'COMPLICATION_TYPE_VO2MAX_BIKE', '4.2.0'),
    _l('training_status', 'COMPLICATION_TYPE_TRAINING_STATUS', '4.2.0'),
    _l('race_predictor_5k', 'COMPLICATION_TYPE_RACE_PREDICTOR_5K', '4.2.0'),
    _l('race_predictor_10k', 'COMPLICATION_TYPE_RACE_PREDICTOR_10K', '4.2.0'),
    _l('race_predictor_half_marathon', 'COMPLICATION_TYPE_RACE_PREDICTOR_HALF_MARATHON', '4.2.0'),
    _l('race_predictor_marathon', 'COMPLICATION_TYPE_RACE_PREDICTOR_MARATHON', '4.2.0'),
    _l('race_pace_predictor_5k', 'COMPLICATION_TYPE_RACE_PACE_PREDICTOR_5K', '4.2.0'),
    _l('race_pace_predictor_10k', 'COMPLICATION_TYPE_RACE_PACE_PREDICTOR_10K', '4.2.0'),
    _l('race_pace_predictor_half_marathon', 'COMPLICATION_TYPE_RACE_PACE_PREDICTOR_HALF_MARATHON', '4.2.0'),
    _l('race_pace_predictor_marathon', 'COMPLICATION_TYPE_RACE_PACE_PREDICTOR_MARATHON', '4.2.0'),
    _l('pulse_ox', 'COMPLICATION_TYPE_PULSE_OX', '4.2.0'),
    _l('respiration_rate', 'COMPLICATION_TYPE_RESPIRATION_RATE', '4.2.0'),
    _l('solar_input', 'COMPLICATION_TYPE_SOLAR_INPUT', '4.2.0'),
    _l('current_temperature', 'COMPLICATION_TYPE_CURRENT_TEMPERATURE', '4.2.0'),
    _l('high_low_temperature', 'COMPLICATION_TYPE_HIGH_LOW_TEMPERATURE', '4.2.0'),
    _l('wheelchair_pushes', 'COMPLICATION_TYPE_WHEELCHAIR_PUSHES', '4.2.3'),
    _l('last_golf_round_score', 'COMPLICATION_TYPE_LAST_GOLF_ROUND_SCORE', '5.0.0'),
    _l('sleep_score', 'COMPLICATION_TYPE_SLEEP_SCORE', '6.0.2'),
]}


def get(name: str) -> Launchable | None:
    return LAUNCHABLE.get(name)


def names() -> list[str]:
    return sorted(LAUNCHABLE)


def suggest(name: str, limit: int = 3) -> list[str]:
    """Nearest names, for the "misspelled tap target" diagnostic."""
    import difflib

    return difflib.get_close_matches(name, LAUNCHABLE, n=limit, cutoff=0.5)
