// Generates examples/features/profile/face.yaml: the same sixteen drawables
// in three layouts -- no `outline:`, a 1px ring and a 2px ring -- for
// `wfb build --profile` to time on a watch (docs/guide/preview-and-cli.md,
// "Profiling"). Three copies of one design differ only in their ids and
// their `outline:`, which is what a generator is for; the output is
// committed, so the face builds without running this.
//
//   node ts/tools/gen-profile-face.ts
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { REPO_ROOT } from "../src/devices/node.ts";

const OUT = join(REPO_ROOT, "examples", "features", "profile", "face.yaml");

/** Grid cell centres, as `dx`/`dy` percentages of the screen. */
const COLUMNS = [-27, -9, 9, 27];
const ROWS = [-22, -5, 12, 29];

/** `[name, element body]` in grid order, as format strings: `{at}` is the cell's anchor, `{{` and `}}` a literal brace. */
const DRAWABLES: [string, string][] = [
  ["disc", `type: circle
    at: {at}
    radius: 6%r
    color: color.fill`],
  ["card", `type: rectangle
    at: {at}
    size: {{ width: 12%, height: 7% }}
    color: color.fill`],
  ["pill", `type: rectangle
    at: {at}
    size: {{ width: 12%, height: 7% }}
    corner_radius: 4px
    color: color.fill`],
  ["egg", `type: ellipse
    at: {at}
    size: {{ width: 13%, height: 8% }}
    color: color.fill`],
  ["hoop", `type: circle
    at: {at}
    radius: 6%r
    thickness: 3px
    filled: false
    color: color.fill`],
  ["label", `type: text
    text: "12:34"
    font: FONT_XTINY
    at: {at}
    color: color.fill`],
  ["arc", `type: arc
    at: {at}
    radius: 6%r
    thickness: 3px
    start_angle: 300deg
    sweep: 120deg
    color: color.fill`],
  ["tri", `type: polygon
    points:
      - {{ {anchor}, dx: {dx_l}%, dy: {dy_b}% }}
      - {{ {anchor}, dx: {dx}%, dy: {dy_t}% }}
      - {{ {anchor}, dx: {dx_r}%, dy: {dy_b}% }}
    color: color.fill`],
  ["rule", `type: line
    at: {{ {anchor}, dx: {dx_l}%, dy: {dy}% }}
    to: {{ {anchor}, dx: {dx_r}%, dy: {dy}% }}
    thickness: 2px
    color: color.fill`],
  ["digits", `type: text
    text: "12:34"
    font: font.digits
    at: {at}
    color: color.fill`],
  ["alarm", `type: icon
    icon: alarm
    size: 12%r
    at: {at}
    color: color.fill`],
  ["ticks", `type: pattern
    pattern: radial
    at: {at}
    count: 8
    step: 45deg
    color: color.fill
    parts:
      - {{ type: line, at: {{ dy: -9%r }}, to: {{ dy: -5%r }}, thickness: 2px }}`],
  ["battery", `type: gauge
    style: arc
    value: system.battery
    max: 100
    at: {at}
    radius: 6%r
    thickness: 3px
    start_angle: 240deg
    sweep: 240deg
    color: color.fill
    track_color: color.track`],
  ["steps", `type: gauge
    style: bar
    value: system.battery
    max: 100
    at: {at}
    size: {{ width: 13%, height: 3% }}
    color: color.fill
    track_color: color.track`],
  ["badge", `type: group
    at: {at}
    size: {{ width: 16%, height: 8% }}
    children:
      {id}_icon: {{ type: icon, icon: heart, size: 8%r, at: {{ anchor: left }}, align: left, color: color.fill }}
      {id}_value: {{ type: text, text: "72", font: FONT_XTINY, at: {{ anchor: right }}, align: right, color: color.fill }}`],
  ["hands", `type: hands
    set: mini
    at: {at}`],
];

const VARIANTS: [string, string, number | null][] = [
  ["plain", "No outline", null],
  ["ring1", "1px outline", 1],
  ["ring2", "2px outline", 2],
];

const HEADER = `# Generated by ts/tools/gen-profile-face.ts -- edit that, not this.
#
# A profiling face for \`outline:\`: sixteen drawables on a 4x4
# grid -- the three grown shapes, every stamped shape, text in a baked font
# (ringed from its baked ring font) and in a system font (stamped), an icon, a
# pattern, two gauges, hands and a group -- in three layouts: no outline, a
# 1px ring and a 2px ring.  Switch between them with the watch's style
# setting (the native editor, or the generated settings menu on fr955).
#
# Build it instrumented, sideload it and read the numbers off the watch:
#
#     ./wfb.py build examples/features/profile/face.yaml --profile
#
# Each element's average draw time per call, in microseconds, appears above
# it; the top line is the last frame's time, the app's memory, and the
# empty-loop baseline to subtract.  An outlined group's ring pass is timed
# on its own.  See docs/guide/preview-and-cli.md, "Profiling".
#
# yaml-language-server: $schema=../../../schema/wfb-face-2.schema.json

format: 2

face:
  id: 5c3a9e82-7d14-4b6f-a0e3-8f2d1c6b9a47
  name: Feature Profile
  version: 1.0.0

build:
  targets:
    - fenix8solar47mm
    - fenix8solar51mm
    - fr955

resources:
  fonts:
    digits:
      source: ../outline/assets/ChivoMono-Bold.ttf
      size: 8%r

  palette:
    bg: "#000000"
    fill: "#AA00FF"
    ring: "#FFFF00"
    track: "#555555"

  hand_sets:
    mini:
      hour:
        color: color.fill
        parts:
          - type: polygon
            points: [{ dx: -2%r, dy: 2%r }, { dy: -7%r }, { dx: 2%r, dy: 2%r }]
      minute:
        color: color.fill
        parts:
          - { type: rectangle, at: { dy: -4%r }, size: { width: 1%r, height: 10%r } }

config:
  style:
    default: plain
    choices:
`;

/** Python's `str.format` for named fields: `{name}` filled, `{{` and `}}` a brace. */
const format = (template: string, fields: Record<string, string | number>): string =>
  template.replace(/\{\{|\}\}|\{(\w+)\}/g, (whole, name: string | undefined) => (name === undefined ? whole[0]! : String(fields[name])));

function element(name: string, body: string, index: number, suffix: string, ring: number | null): string {
  const dx = COLUMNS[index % 4]!, dy = ROWS[Math.floor(index / 4)]!;
  const id = `${name}_${suffix}`;
  const text = format(body, {
    at: `{ anchor: center, dx: ${dx}%, dy: ${dy}% }`, anchor: "anchor: center",
    dx, dy, dx_l: dx - 6, dx_r: dx + 6, dy_t: dy - 4, dy_b: dy + 4, id,
  });
  const [first, ...rest] = text.split("\n");
  const lines = [`      ${id}:`, `        ${first}`, ...rest.map((line) => `    ${line}`)];
  if (ring !== null) {
    lines.push(ring === 1 ? "        outline: color.ring" : `        outline: { color: color.ring, width: ${ring} }`);
    if (name === "digits" || name === "label") {
      lines.push("        lint:", "          allow: [text-outline-interior]", "          reason: \"a ringed, filled numeral: the interior is meant to show\"");
    }
  }
  return lines.join("\n");
}

const out = [HEADER];
for (const [key, label] of VARIANTS) out.push(`      ${key}: { label: "${label}", layout: ${key} }\n`);
out.push(`
static:
  background:
    type: rectangle
    at: { anchor: center }
    size: { width: 100%, height: 100% }
    color: color.bg

layouts:
`);
for (const [key, , ring] of VARIANTS) {
  out.push(`  ${key}:\n    elements:\n`);
  DRAWABLES.forEach(([name, body], index) => out.push(element(name, body, index, key, ring) + "\n\n"));
}
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out.join("").trimEnd() + "\n");
console.log(`wrote ${relative(REPO_ROOT, OUT)}`);
