
services:
  garmin-wf-builder:
    container_name: garmin-wf-builder
    image: garmin-wf-builder:latest
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    user: 1000:1000
    restart: unless-stopped
    command: ["studio", "--host=0.0.0.0", "--port=8765"]
    ports:
      - 8765:8765
    volumes:
      - ./vendor/devices:/devices:ro
      - ./vendor/fonts:/fonts:ro
      - wfb-keys:/keys:rw

    # deploy:
    #   resources:
    #     limits:
    #       memory: 2048M
    #     reservations:
    #       memory: 1G
    
volumes:
  wfb-keys:
    external: true

