"""Shared small helpers and types used across the Monkey C generation package."""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

from ... import __version__
from ...availability import Guards
from ...ir import (
    ComplicationSlot, Expression, Face, Graph, HandsElement, IconElement, PatternElement,
    Position, Progress, Shape, Text, config_data_ids, element_const_prefix,
    element_method_name,
)
from ...layout import PlacedComplicationSlot, PlacedIcon, PlacedPattern, PlacedText, ResolvedFace


#: Base Toybox imports every generated face needs.
_BASE_IMPORTS = ("Toybox.Graphics", "Toybox.Lang", "Toybox.WatchUi")


#: The "nothing is missing" `Guards` -- every emit function below that takes
#: an optional `guards` parameter defaults to this, so a call site that
#: predates `wfb.availability` (every existing test, and any caller that
#: only ever generates for one device) keeps producing exactly the
#: unguarded code it always did.
_NO_GUARDS = Guards(complications=False, fields=frozenset())


@dataclass
class SourceFile:
    """One generated file, and where it belongs in the project."""

    #: Relative to the build directory, e.g. ``source/SliceView.mc``.
    path: str
    text: str


def source_label(path) -> str:
    """The design's path as it should appear in a generated header.

    Relative to the working directory when it is under it, and the bare filename
    otherwise.  An absolute path would make generated output differ between
    machines, which would defeat the golden-file tests and make every diff noisy.
    """
    try:
        relative = os.path.relpath(Path(path).resolve(), Path.cwd())
    except (OSError, ValueError):
        return Path(path).name
    return Path(path).name if relative.startswith("..") else relative


def header(face: Face, extra: str = "") -> str:
    lines = [
        f"Generated by garmin-wf-builder {__version__} -- do not edit.",
        f"Source:    {source_label(face.source_path)}",
        f"Face:      {face.name} (format {face.format})",
    ]
    if extra:
        lines.append(extra)
    lines.append("Regenerate with `wfb build`.  Edits here are lost on the next build;")
    lines.append("hand-written Monkey C belongs in a `raw` element instead (ADR 0007).")
    return "\n".join(lines)


@dataclass(frozen=True)
class McLiteral:
    """A layout constant whose value is not a plain number.

    Every other constant is a `Number` or a `Float` that `_mc_type`/`_mc_number`
    can derive from the Python value.  A polygon's point array is the one
    exception, so it carries its own declared Monkey C type and source text.

    **The type is not cosmetic and the shape was chosen by building, not by
    preference** (`docs/research/probes/polygon-const/`).  `Dc.fillPolygon`
    takes `Array<Graphics.Point2D>`, and `Point2D` is the *fixed-size* tuple
    type `[Numeric, Numeric]`: declaring the const `Array<Array<Number> >`
    instead compiles the const fine and then fails at the call site under
    `-l 3`.  A module-level `const` of the right type is accepted, so the array
    lives in `Layout` like every other coordinate (ADR 0004) rather than being
    assembled from per-coordinate constants at the call site.
    """

    type: str
    code: str


def hold_targets(face: Face) -> list:
    """Elements a hold does something with, in draw order.

    An `on_hold:` on any element.  Empty means a passive face, and the whole
    delegate is then omitted.
    """
    return [e for e in face.walk() if e.on_hold is not None]


def complication_slots(face: Face) -> list:
    """Every `complication_slot` element, in draw order.

    Drives the editor-only machinery (`AppBase.onStart`'s edit-mode flag,
    `WatchFaceDelegate.onTap`/`getComplicationDrawable`, the generated
    `SlotDrawable`) -- all of it gated on this being non-empty, never on
    `face.config_data` alone, since a declared `config: data:` slot with no
    `complication_slot` element drawing it would otherwise pull in a whole
    editor-highlight seam for nothing on screen to highlight.
    """
    return [e for e in face.walk() if isinstance(e, ComplicationSlot)]


def needs_delegate(face: Face) -> bool:
    """Does this design need a `WatchFaceDelegate` at all?

    Two independent reasons, either sufficient on its own: a hold target
    (`on_hold:`), or a declared `config:` block, whose
    `onWatchFaceConfigEdited` lives on the delegate the same way `onPress`
    does.  A design with `config:` and no interactivity still needs the
    delegate purely to re-read settings when the editor reports a change.
    """
    return bool(hold_targets(face)) or face.has_config


def _editor_slot_pairs(face: Face) -> list:
    """Every `complication_slot` element this design actually draws, paired
    with its declared slot's `<complication id=...>` unique id
    (`wfb.ir.config_data_ids`) -- one pair per distinct slot *name*, in
    document order.

    Backs every editor-only piece (`onTap`'s hit-test, `getComplicationDrawable`'s
    dispatch, the generated `SlotDrawable`): all three need "which element
    goes with which unique id", and deduplicating by slot name here, once, is
    what keeps two elements bound to the same slot -- legal, if unusual, and
    not otherwise checked anywhere in this project -- from generating two
    `case`/`if` labels for one id.
    """
    ids = config_data_ids(face)
    seen: set[str] = set()
    pairs = []
    for element in complication_slots(face):
        if element.slot in seen:
            continue
        seen.add(element.slot)
        unique = ids.get(element.slot)
        if unique is not None:
            pairs.append((element, unique))
    return pairs


#: The view's public accessor for `CONFIG_LAYOUT_FIELD`, emitted only when
#: some `on_hold:` target belongs to a layout -- the delegate's `onPress`
#: is the only cross-class reader (`_view.configLayout()`), and `private`
#: genuinely blocks a cross-class call (docs/lore/monkeyc.md).
CONFIG_LAYOUT_METHOD = "configLayout"


def _pattern_needs_math(placed: "PlacedPattern") -> bool:
    """Does this pattern's device loop compute a `sin`/`cos` pair at all?

    Only a **radial** pattern turns; a linear one only ever translates
    (plan 05 §5.3), so it never needs trigonometry.  And even a radial
    pattern skips it when every part is an `arc`: an arc's start angle
    turns by plain degree subtraction through `WfbArc.drawSpan`'s own
    `startDegrees` parameter (§6.4), not by rotating a coordinate -- so an
    all-arc radial pattern (`segments` in `examples/patterns/face.yaml`)
    needs no `sin`/`cos` and therefore no `Toybox.Math` either.  A text part
    (plan 06 §3.4) is on the same footing as a filled circle's centre here:
    only its *anchor* is rotated (the glyphs themselves stay upright), but
    `WfbGeom.drawTextRotated` still takes `sin`/`cos` as plain call
    arguments, exactly like `fillCircleRotated` does for a circle at the
    origin -- so a text part counts as "not an arc" with no special case
    needed, the same one `any(part.shape != "arc" ...)` line already covers
    it. Shared by the view's import gate and :func:`_emit_pattern` itself so
    the two cannot drift into disagreeing about whether the loop declares
    `angle`/`sin`/`cos`.
    """
    if placed.element.pattern != "radial":
        return False
    return any(part.shape != "arc" for part in placed.parts)


def _glyph_y_expr(y_expr: str, vertical_align: str, font_expr: str) -> str:
    """The `y` a glyph draw hands `dc.drawText`/`WfbGeom.drawTextRotated`,
    for a given `vertical_align:` (plan 07 §3.2(b)): `y_expr` unchanged for
    `top`/`center` (`Resolver._justify` already adds `TEXT_JUSTIFY_VCENTER`
    for `center`, and `top` is `Dc.drawText`'s own natural top-left
    placement) -- there is no bottom-justify flag on the platform, so
    `bottom` instead subtracts the font's *own*, on-device measured height,
    exact even for a system font whose `size_px` `wfb.devices` only
    scraped. Shared by a `text` element and a pattern's `shape: text` part
    (and, from phase C, an icon) -- one subtraction, written once, not a
    per-kind copy. `font_expr` is whatever Monkey C expression names the
    font at the call site (a local `font` or `Graphics.FONT_...`).
    """
    if vertical_align != "bottom":
        return y_expr
    return f"{y_expr} - dc.getFontHeight({font_expr})"


# --------------------------------------------------------------------------
# naming and small helpers


#: The symbol-derivation logic lives in `wfb.ir` now (`element_const_prefix`,
#: `element_method_name`) so that id uniqueness (checked in `ir.Builder`) and
#: symbol derivation (used here) cannot drift into two different notions of
#: "the same name" -- see `Builder._check_symbol_collision`. These aliases
#: keep every call site below unchanged.
_const_prefix = element_const_prefix


_method = element_method_name


def _field(name: str) -> str:
    parts = [p for p in name.replace("-", "_").split("_") if p]
    return "font" + "".join(p[:1].upper() + p[1:] for p in parts)


def _color(expression: Expression | None) -> str:
    if expression is None:
        return "Graphics.COLOR_WHITE"
    return expression.code


def _mc_bool(value: bool) -> str:
    return "true" if value else "false"


def _mc_float(value: float) -> str:
    """A bare `Float` literal for inline use in the view, not a `Layout`
    constant (`_mc_number` handles those, with a trailing `f`).  A Python
    float's own `repr` always carries a decimal point, which is what makes
    a literal like `0.10471975511965977` unambiguously `Float` rather than
    `Number` to the Monkey C parser with no suffix needed at all -- plan 05
    §6.4's own radial-angle example spells it exactly this way.
    """
    text = repr(float(value))
    return text if "." in text or "e" in text else text + ".0"


def _loaded_fonts(resolved: ResolvedFace) -> list[str]:
    """Every font resource this view loads once in `onLayout`.

    Covers both an author's declared custom text fonts and the synthetic
    per-size icon fonts (`wfb.icons.font_key`) -- both are bitmap fonts loaded
    the same way, so one list and one loop serves both.  A pattern's `shape:
    text` part (plan 06 §3.4) is one more source of a custom font: every
    *drawn* copy shares the one font its part resolved to, so it is a single
    entry here regardless of `count`, the same "one load, many uses" shape
    `_emit_pattern`'s own per-pattern ``text_fonts`` map follows.
    """
    out: list[str] = []
    for placed in resolved.items:
        if isinstance(placed, PlacedText) and placed.font_is_custom:
            if placed.font_reference not in out:
                out.append(placed.font_reference)
        elif isinstance(placed, PlacedIcon):
            if placed.font_key not in out:
                out.append(placed.font_key)
        elif isinstance(placed, PlacedComplicationSlot):
            if placed.font_is_custom and placed.font_reference not in out:
                out.append(placed.font_reference)
            if placed.icon_font_key is not None and placed.icon_font_key not in out:
                out.append(placed.icon_font_key)
        elif isinstance(placed, PlacedPattern):
            for part in placed.parts:
                if part.shape == "text" and part.font_is_custom and part.font_reference not in out:
                    out.append(part.font_reference)
    return out


def _describe(placed) -> str:
    element = placed.element
    if isinstance(element, Shape):
        if element.shape == "polygon":
            return f"a polygon of {len(element.points)} points"
        noun = _article(element.shape.replace("_", " "))
        if element.shape in ("rectangle", "rounded_rectangle", "circle", "ellipse") \
                and not element.filled:
            return f"{noun}, outlined"
        return noun
    if isinstance(element, Text):
        return "text" if element.value is not None else "fixed text"
    if isinstance(element, Progress):
        return _article(f"{element.style} progress indicator")
    if isinstance(element, IconElement):
        if element.is_dynamic:
            return f"an icon chosen at runtime from {element.value_for.text!r}"
        return f"the {element.icon!r} icon"
    if isinstance(element, Graph):
        return f"{_article(f'{element.style} graph')} of {element.series}"
    if isinstance(element, ComplicationSlot):
        return f"a native Data-axis slot (config.data.{element.slot})"
    if isinstance(element, HandsElement):
        drawn = [n for n in ("hour", "minute", "second") if getattr(placed, n, None) is not None]
        seconds_note = f", seconds: {element.seconds}" if element.seconds else ""
        return f"analog hands (hands.{element.hands}): {_and_list(drawn)}{seconds_note}"
    if isinstance(element, PatternElement):
        total = element.count
        drawn_count = len(placed.copies)
        note = "" if drawn_count == total else f" ({drawn_count} drawn)"
        if element.pattern == "radial":
            return f"a radial pattern: {total} copies, {element.step_angle:g} degrees apart{note}"
        step = element.step or Position()
        offsets = [f"{axis} {length}" for axis, length in
                  (("dx", step.dx), ("dy", step.dy)) if length is not None]
        step_desc = ", ".join(offsets) if offsets else "0px"
        return f"a linear pattern: {total} copies, step {step_desc}{note}"
    return element.kind


def _and_list(items) -> str:
    items = list(items)
    if len(items) <= 1:
        return "".join(items)
    return ", ".join(items[:-1]) + " and " + items[-1]


def _article(noun: str) -> str:
    return f"{'an' if noun[:1].lower() in 'aeiou' else 'a'} {noun}"


def _mc_type(value: float | McLiteral) -> str:
    if isinstance(value, McLiteral):
        return value.type
    return "Float" if isinstance(value, float) else "Number"


def _mc_number(value: float | McLiteral) -> str:
    if isinstance(value, McLiteral):
        return value.code
    return f"{value}f" if isinstance(value, float) else str(int(value))
