"""Shared small helpers and types used across the Monkey C generation package."""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

from ... import __version__, kinds
from ...availability import Guards
from ...ir import ComplicationSlot, Expression, Face, aod_color_choice, config_data_ids, \
    element_const_prefix, element_method_name
from ...layout import PlacedText, ResolvedFace
from ...palette import Color


#: Base Toybox imports every generated face needs.
_BASE_IMPORTS = ("Toybox.Graphics", "Toybox.Lang", "Toybox.WatchUi")


#: The "nothing is missing" `Guards` -- the default of every emit function
#: taking an optional `guards` parameter, which then generates the
#: unguarded code (a test, or a single-device caller).
_NO_GUARDS = Guards(complications=False, fields=frozenset())


@dataclass
class SourceFile:
    """One generated file, and where it belongs in the project."""

    #: Relative to the build directory, e.g. ``source/SliceView.mc``.
    path: str
    text: str


def source_label(path) -> str:
    """The design's path as it should appear in a generated header.

    Relative to the working directory when it is under it, and the bare filename
    otherwise.  An absolute path would make generated output differ between
    machines, which would defeat the golden-file tests and make every diff noisy.
    """
    try:
        relative = os.path.relpath(Path(path).resolve(), Path.cwd())
    except (OSError, ValueError):
        return Path(path).name
    return Path(path).name if relative.startswith("..") else relative


def header(face: Face, extra: str = "") -> str:
    lines = [
        f"Generated by garmin-wf-builder {__version__} -- do not edit.",
        f"Source:    {source_label(face.source_path)}",
        f"Face:      {face.name} (format {face.format})",
    ]
    if extra:
        lines.append(extra)
    lines.append("Regenerate with `wfb build`.  Edits here are lost on the next build;")
    lines.append("hand-written Monkey C belongs in a `raw` element instead (ADR 0007).")
    return "\n".join(lines)


@dataclass(frozen=True)
class McLiteral:
    """A layout constant whose value is not a plain number.

    Every other constant is a `Number` or a `Float` that `_mc_type`/`_mc_number`
    can derive from the Python value.  A polygon's point array is the one
    exception, so it carries its own declared Monkey C type and source text.

    **The type is not cosmetic and the shape was chosen by building, not by
    preference** (`docs/research/probes/polygon-const/`).  `Dc.fillPolygon`
    takes `Array<Graphics.Point2D>`, and `Point2D` is the *fixed-size* tuple
    type `[Numeric, Numeric]`: declaring the const `Array<Array<Number> >`
    instead compiles the const fine and then fails at the call site under
    `-l 3`.  A module-level `const` of the right type is accepted, so the array
    lives in `Layout` like every other coordinate (ADR 0004) rather than being
    assembled from per-coordinate constants at the call site.
    """

    type: str
    code: str


def hold_targets(face: Face) -> list:
    """Elements a hold does something with, in draw order.

    An `on_hold:` on any element.  Empty means a passive face, and the whole
    delegate is then omitted.
    """
    return [e for e in face.walk() if e.on_hold is not None]


def complication_slots(face: Face) -> list:
    """Every `complication_slot` element, in draw order.

    Drives the editor-only machinery (`AppBase.onStart`'s edit-mode flag,
    `WatchFaceDelegate.onTap`/`getComplicationDrawable`, the generated
    `SlotDrawable`) -- all of it gated on this being non-empty, never on
    `face.config_data` alone, since a declared `config: data:` slot with no
    `complication_slot` element drawing it would otherwise pull in a whole
    editor-highlight seam for nothing on screen to highlight.
    """
    return [e for e in face.walk() if isinstance(e, ComplicationSlot)]


def needs_delegate(face: Face) -> bool:
    """Does this design need a `WatchFaceDelegate` at all?

    Two independent reasons, either sufficient on its own: a hold target
    (`on_hold:`), or a declared `config:` block, whose
    `onWatchFaceConfigEdited` lives on the delegate the same way `onPress`
    does.  A design with `config:` and no interactivity still needs the
    delegate purely to re-read settings when the editor reports a change.
    """
    return bool(hold_targets(face)) or face.has_config


def _editor_slot_pairs(face: Face) -> list:
    """Every `complication_slot` element this design actually draws, paired
    with its declared slot's `<complication id=...>` unique id
    (`wfb.ir.config_data_ids`) -- one pair per distinct slot *name*, in
    document order.

    Backs every editor-only piece (`onTap`'s hit-test, `getComplicationDrawable`'s
    dispatch, the generated `SlotDrawable`): all three need "which element
    goes with which unique id", and deduplicating by slot name here, once, is
    what keeps two elements bound to the same slot -- legal, if unusual, and
    not otherwise checked anywhere in this project -- from generating two
    `case`/`if` labels for one id.
    """
    ids = config_data_ids(face)
    seen: set[str] = set()
    pairs = []
    for element in complication_slots(face):
        if element.slot in seen:
            continue
        seen.add(element.slot)
        unique = ids.get(element.slot)
        if unique is not None:
            pairs.append((element, unique))
    return pairs


#: The view's public accessor for `CONFIG_LAYOUT_FIELD`, emitted only when
#: some `on_hold:` target belongs to a layout -- the delegate's `onPress`
#: is the only cross-class reader (`_view.configLayout()`), and `private`
#: genuinely blocks a cross-class call (docs/lore/monkeyc.md).
CONFIG_LAYOUT_METHOD = "configLayout"


def _glyph_y_expr(y_expr: str, vertical_align: str, font_expr: str) -> str:
    """The `y` a glyph draw hands `dc.drawText` (directly, or through
    `WfbGeom.rotatedY` for a radial pattern's `shape: text` part), for a
    given `vertical_align:`: `y_expr` unchanged for `top`/`center`
    (`Resolver._justify` already adds `TEXT_JUSTIFY_VCENTER` for `center`,
    and `top` is `Dc.drawText`'s own natural top-left placement) -- there is
    no bottom-justify flag on the platform, so `bottom` instead subtracts
    the font's *own*, on-device measured height, exact even for a system
    font whose `size_px` `wfb.devices` only scraped. Shared by a `text`
    element, a pattern's `shape: text` part, and an icon -- one subtraction,
    written once, not a per-kind copy. `font_expr` is whatever Monkey C
    expression names the font at the call site (a local `font` or
    `Graphics.FONT_...`).
    """
    if vertical_align != "bottom":
        return y_expr
    return f"{y_expr} - dc.getFontHeight({font_expr})"


# --------------------------------------------------------------------------
# naming and small helpers


#: Symbol derivation lives in `wfb.ir` so id uniqueness
#: (`Builder._check_symbol_collision`) and the symbols used here cannot drift
#: into two notions of "the same name"; short local aliases.
_const_prefix = element_const_prefix


_method = element_method_name


def _field(name: str) -> str:
    parts = [p for p in name.replace("-", "_").split("_") if p]
    return "font" + "".join(p[:1].upper() + p[1:] for p in parts)


def _aod_font_field(name: str) -> str:
    """The view field a baked font used *only* by an `aod: {font: ...}`
    override (never drawn while awake) is loaded into -- `_field(name)`
    with an `Aod` suffix, so it never collides with an awake field for a
    font of the same name used elsewhere too (plan 14 §4.3: "a resource
    font used only as an AOD override is a second resource").
    """
    return f"{_field(name)}Aod"


def _color(expression: Expression | None) -> str:
    if expression is None:
        return "Graphics.COLOR_WHITE"
    return expression.code


#: `aod: {dim: ...}` (plan 14 slice 3), as the `(num, den)` integer ratio
#: `wfb.palette.dim_channel`/the generated `WfbColor.dim` both read -- `None`
#: means "no dimming", the same as the face never writing `dim:` at all
#: (`Face.aod_dim`'s own normalisation folds `dim: 1` into this too).
AodDim = tuple[int, int] | None


def _dim_color_code(expression: Expression | None, awake_code: str, dim: "AodDim") -> str:
    """The AOD Monkey C expression for one colour that has **no** explicit
    `aod: {color: ...}`-style override, when the face's own `aod: {dim:
    ...}` still applies to it (plan 14 §4.5: dimming reaches every colour
    the AOD frame draws, override or not).

    A colour whose value is fixed at build time -- a bare hex literal, or a
    `palette.<name>` reference, `Expression.is_constant` either way -- is
    pre-dimmed into a second literal here, in Python, once, rather than
    spending a runtime call on arithmetic whose answer never changes
    (`wfb.palette.Color.dim`). Anything else -- `config.colors.<role>` (a
    view field the wearer's own on-device pick can repoint) or a
    conditional between several colours -- is dimmed on-device instead, with
    the exact same integer math (`WfbColor.dim`, `runtime-lib/WfbColor.mc`).
    `expression is None` is a `color:` an element never wrote at all, which
    defaults to `Graphics.COLOR_WHITE` (`_color`) and is dimmed like any
    other constant.
    """
    num, den = dim
    if expression is None or expression.is_constant:
        value = expression.constant if expression is not None else 0xFFFFFF
        return Color.parse(value).dim(num, den).as_monkeyc()
    return f"WfbColor.dim({awake_code}, {num}, {den})"


@dataclass(frozen=True)
class AodStyle:
    """How this build restyles a draw call for the AMOLED always-on frame
    (plan 14 §4.2): every override becomes an inline ``_aod ? <aod> :
    <awake>`` ternary at the draw call site.

    ``on`` is whether this build emits AOD code at all (some target is
    AMOLED, `wfb.availability.Guards.amoled_target`); ``dim`` is the
    face-wide `aod: {dim: ...}` ratio. Both are derived once, in
    `emit_view`, and every per-kind emitter takes this one object. With
    ``on`` false every method hands back the awake code unchanged, which is
    what keeps an all-MIP build byte-identical to a face with no `aod:`.
    """

    on: bool = False
    dim: AodDim = None

    def value(self, override: str | None, awake_code: str) -> str:
        """``(_aod ? <override> : <awake>)``, or ``awake_code`` alone when
        there is no override (already rendered as Monkey C: a `Layout`
        constant, a literal, a font expression, ...)."""
        if not self.on or override is None:
            return awake_code
        return f"(_aod ? {override} : {awake_code})"

    def layout(self, prefix: str, suffix: str, has_override: bool) -> str:
        """``Layout.<P>_<suffix>``, ternary against ``Layout.<P>_AOD_<suffix>``
        when the element's resolved `aod:` overrides that key -- the shape
        every `Layout`-backed override (`thickness:`, `bar_width:`) takes."""
        override = f"Layout.{prefix}_AOD_{suffix}" if has_override else None
        return self.value(override, f"Layout.{prefix}_{suffix}")

    def color(self, element, key: str, awake_code: str | None = None) -> str:
        """One colour argument (`color`/`track_color`/`icon_color`) of an
        element shown in AOD: its own `aod:` override for ``key`` if it has
        one, else its awake colour dimmed by `dim` (which reaches every
        colour the AOD frame draws), else the awake colour unchanged.
        ``awake_code`` defaults to the element's own ``key`` colour.

        An override colour is a fully resolved `Expression` built by the same
        machinery as the element's own `color:`, so it follows
        `color_scheme:`/`config.colors` at runtime exactly as the awake one
        does (plan 14 §4.6). Which of the three applies is `aod_color_choice`
        (`wfb.ir`), the one decision `wfb.preview._aod_color` also reads --
        this method only turns that decision into Monkey C.
        """
        expression = getattr(element, key, None)
        if awake_code is None:
            awake_code = _color(expression)
        if not self.on or element.aod is None:
            return awake_code
        choice, override = aod_color_choice(element.aod, key, self.dim is not None)
        return self._render(choice, override, expression, awake_code)

    def part_color(self, element, color_expr: Expression | None) -> str:
        """`color`'s rule for one `hands`/`pattern` part: the element-level
        `aod: {color: ...}` applies uniformly to every part (§5.1), and
        `dim` dims each part's own colour."""
        awake_code = _color(color_expr)
        if not self.on or element.aod is None:
            return awake_code
        choice, override = aod_color_choice(element.aod, "color", self.dim is not None)
        return self._render(choice, override, color_expr, awake_code)

    def _render(self, choice: str, override: Expression | None,
                expression: Expression | None, awake_code: str) -> str:
        """`aod_color_choice`'s decision, printed as Monkey C: the override's
        own compiled code, `WfbColor.dim`/a pre-dimmed literal
        (`_dim_color_code`), or `awake_code` unchanged -- each wrapped in
        `self.value`'s `_aod ? ... : ...` ternary."""
        if choice == "override":
            return self.value(override.code, awake_code)
        if choice == "dim":
            return self.value(_dim_color_code(expression, awake_code, self.dim), awake_code)
        return awake_code


#: No AOD code at all -- the default for every emitter's `aod` parameter.
NO_AOD = AodStyle()


def _mc_bool(value: bool) -> str:
    return "true" if value else "false"


def _mc_float(value: float) -> str:
    """A bare `Float` literal for inline use in the view, not a `Layout`
    constant (`_mc_number` handles those, with a trailing `f`).  A Python
    float's own `repr` always carries a decimal point, which is what makes
    a literal like `0.10471975511965977` unambiguously `Float` rather than
    `Number` to the Monkey C parser with no suffix needed at all.
    """
    text = repr(float(value))
    return text if "." in text or "e" in text else text + ".0"


def _loaded_fonts(resolved: ResolvedFace) -> list[str]:
    """Every **bitmap** font resource this view loads once in `onLayout`
    through `WatchUi.loadResource`, in first-appearance draw order: an
    author's baked text fonts (a `text` element's, a `complication_slot`'s,
    a pattern `shape: text` part's) and the synthetic per-size icon fonts
    (`wfb.icons.font_key`) alike.

    **A `face:` (vector) font is never in this list** (plan 11): it is not
    a resource at all, and `_vector_fonts_used` covers it instead.
    """
    out: list[str] = []
    for placed in resolved.items:
        out.extend(kinds.for_placed(placed).loaded_fonts(placed))
    return list(dict.fromkeys(out))


def _aod_only_fonts(resolved: ResolvedFace) -> list[str]:
    """Baked (non-vector) custom fonts named only by a `text` element's own
    `aod: {font: ...}` override, and never drawn while awake (`_loaded_
    fonts`) -- plan 14 §4.3's "a resource font used only as an AOD override
    is a second resource": loaded in `onEnterSleep`, only when `_aod`, and
    released (nulled) in `onExitSleep`, so it does not sit in memory the
    whole time the way an ordinarily-loaded font does.

    Excludes an override that names the *same* resource the element already
    draws with while awake (nothing to load a second time -- the awake
    field already covers it). A `face:` (vector) font override, a
    `complication_slot`'s own `font:` override and a pattern's own `font:`
    override are all rejected outright as friendly build errors
    (`Builder._build_aod_authored`, `docs/limitations.md` §2), so none of
    them can ever reach this function -- only `PlacedText` is consulted.
    """
    awake = set(_loaded_fonts(resolved))
    out: list[str] = []
    for placed in resolved.items:
        if not isinstance(placed, PlacedText):
            continue
        aod = placed.element.aod
        if aod is None or aod.font is None or not aod.font_is_custom:
            continue
        if aod.font == placed.font.reference or aod.font in awake or aod.font in out:
            continue
        spec = resolved.face.fonts.get(aod.font)
        if spec is None or spec.is_vector:
            continue
        out.append(aod.font)
    return out


def _vector_fonts_used(resolved: ResolvedFace) -> list[str]:
    """Every `face:` (vector) font name a `text` element, or a pattern's own
    `shape: text` part, draws with, in first-appearance draw order -- the
    vector counterpart of :func:`_loaded_fonts` (built through
    `Graphics.getVectorFont`, not `WatchUi.loadResource`, plan 11 §3).  A
    declared but undrawn font contributes nothing.  `wfb.availability.
    vector_fonts_used(face)` answers the same question off the IR, for the
    build-wide guard decision made before any device is resolved.
    """
    out: list[str] = []
    for placed in resolved.items:
        out.extend(kinds.for_placed(placed).vector_fonts(placed))
    return list(dict.fromkeys(out))


def _describe(placed) -> str:
    return kinds.for_placed(placed).describe(placed)


def _and_list(items) -> str:
    items = list(items)
    if len(items) <= 1:
        return "".join(items)
    return ", ".join(items[:-1]) + " and " + items[-1]


def _article(noun: str) -> str:
    return f"{'an' if noun[:1].lower() in 'aeiou' else 'a'} {noun}"


def _mc_type(value: float | str | bool | McLiteral) -> str:
    """A `Layout` constant's declared Monkey C type -- every constant
    (`layout_constants.Constants`) is typed and rendered through this and
    `_mc_number`.  `bool` is checked before `float`/`int`: Python's `bool`
    is a subtype of `int`, so the order matters or `True`/`False` would
    fall through to `Number`.
    """
    if isinstance(value, McLiteral):
        return value.type
    if isinstance(value, bool):
        return "Boolean"
    if isinstance(value, str):
        return "String"
    return "Float" if isinstance(value, float) else "Number"


def _mc_string(value: str) -> str:
    """A double-quoted Monkey C string literal for `value`.

    Every string this project ever emits into a `Layout` constant is a
    device-published face *name* (`Device.scalable_faces`, straight out of
    a device's own `simulator.json`) or the empty string (an unavailable
    font, plan 11 -- never drawn, since the null check at the call site
    always gates it) -- neither can contain a `"` or a control character in
    practice, but the two characters that would break the literal if they
    somehow did are still escaped rather than assumed absent.
    """
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _mc_number(value: float | str | bool | McLiteral) -> str:
    if isinstance(value, McLiteral):
        return value.code
    if isinstance(value, bool):
        return _mc_bool(value)
    if isinstance(value, str):
        return _mc_string(value)
    return f"{value}f" if isinstance(value, float) else str(int(value))
