"""Write face.yaml: each primitive whose `outline:` the compiler draws as one
*grown* copy, beside the same primitive with the ring built by hand as a
*stamp* (the primitive in the ring colour at every
`wfb.ir.disc_perimeter_offsets(width)` point, then the fill).

Backs docs/research/28-editor-open-questions.md §8. Today's `wfb preview`
draws both columns the same way (it always stamps); the generated code draws
the left column grown. A simulator screenshot on the user's host shows which
one the watch's rasteriser makes.

    ./.venv/bin/python docs/research/probes/ring-on-device/make_face.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[4]))

from wfb.ir import disc_perimeter_offsets  # noqa: E402

ROWS = {"circle": 70, "rectangle": 130, "rounded": 190}
COLUMNS = {(1, "grown"): 62, (1, "stamp"): 104, (2, "grown"): 156, (2, "stamp"): 198}


def shape(kind: str, x: int, y: int, color: str, extra: str = "") -> str:
    if kind == "circle":
        return (f"{{ type: circle, at: {{ anchor: top_left, dx: {x}px, dy: {y}px }}, "
                f"radius: 14px, color: {color}{extra} }}")
    corner = ", corner_radius: 5px" if kind == "rounded" else ""
    return (f"{{ type: rectangle, at: {{ anchor: top_left, dx: {x}px, dy: {y}px }}, "
            f"size: {{ width: 30px, height: 20px }}{corner}, color: {color}{extra} }}")


def main() -> None:
    lines = [
        "# Generated by make_face.py: grown (left of each pair) vs hand-stamped",
        "# (right) outline rings, 1px then 2px, on circle/rectangle/rounded rect.",
        "format: 2",
        "",
        "face:",
        "  id: 0d6f4e0a-27c4-4f1e-9b9e-7f3a6c2d8e15",
        "  name: Ring Probe",
        "  version: 1.0.0",
        "",
        "build:",
        "  targets:",
        "    - fenix8solar47mm",
        "",
        "resources:",
        "  palette:",
        '    bg: "#000000"',
        '    fill: "#FFFFFF"',
        '    ring: "#FF0000"',
        "",
        "elements:",
        "  background: { type: rectangle, at: { anchor: center }, "
        "size: { width: 100%, height: 100% }, color: color.bg }",
    ]
    for kind, y in ROWS.items():
        for (width, how), x in COLUMNS.items():
            name = f"{kind}_{how}{width}"
            if how == "grown":
                ring = "color.ring" if width == 1 else "{ color: color.ring, width: 2 }"
                lines.append(f"  {name}: {shape(kind, x, y, 'color.fill', f', outline: {ring}')}")
            else:
                for i, (dx, dy) in enumerate(disc_perimeter_offsets(width)):
                    lines.append(f"  {name}_s{i}: {shape(kind, x + dx, y + dy, 'color.ring')}")
                lines.append(f"  {name}: {shape(kind, x, y, 'color.fill')}")
    Path(__file__).with_name("face.yaml").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
