//! Generated by garmin-wf-builder 0.1.0 -- do not edit.
//! Source:    tests/fixtures/outline_text/face.yaml
//! Face:      OutlineText (format 2)
//! Device:    fr955 -- 260x260 round, mip, family round-260x260
//! Regenerate with `wfb build`.  Edits here are lost on the next build;
//! hand-written Monkey C belongs in a `raw` element instead (ADR 0007).

import Toybox.Lang;

//! Layout resolved for fr955.
//!
//! Every value here came from a relative unit in the design -- percentages of
//! the parent box, fractions of the screen's minor radius, angles measured
//! clockwise from 12 o'clock.  Resolving them here means the device performs
//! no layout arithmetic at all, which costs neither memory nor frame time.
module Layout {
    //! The screen, for reference.
    const SCREEN_WIDTH as Number = 260;
    const SCREEN_HEIGHT as Number = 260;

    //! Device-resident scalable ('face:') fonts this design draws with.
    //!
    //! '_FACE'/'_SIZE' feed Graphics.getVectorFont directly, in onLayout.
    //! '_AVAILABLE' is emitted only for a font at least one target device in
    //! this build fails to publish -- the shared view (identical on every
    //! device) reads it to decide whether to even attempt construction here,
    //! so every device's own Layout.mc has to define it once any device
    //! needs it (wfb.availability.Guards.vector_fonts).

    //! `font.bezel`
    const FONT_BEZEL_FACE as String = "RobotoCondensedBold";  // requested, in author order: RobotoCondensedBold, RobotoCondensedRegular
    const FONT_BEZEL_SIZE as Number = 8;

    //! `background` -- a rectangle
    const BACKGROUND_X as Number = 0;
    const BACKGROUND_Y as Number = 0;
    const BACKGROUND_WIDTH as Number = 260;
    const BACKGROUND_HEIGHT as Number = 260;

    //! `clock` -- text
    const CLOCK_X as Number = 130;
    const CLOCK_Y as Number = 104;
    const CLOCK_WIDTH as Number = 76;  // widest rendering "23:59" is 76 px

    //! `upright_vector` -- fixed text
    const UPRIGHT_VECTOR_X as Number = 130;
    const UPRIGHT_VECTOR_Y as Number = 169;
    const UPRIGHT_VECTOR_WIDTH as Number = 26;  // widest rendering "UPRIGHT" is 26 px (estimated)

    //! `brand` -- fixed text
    const BRAND_X as Number = 130;
    const BRAND_Y as Number = 58;
    const BRAND_WIDTH as Number = 23;  // widest rendering "GARMIN" is 23 px (estimated)
    const BRAND_ANGLE as Float = 315.0f;  // 45deg clockwise rotation from upright, in Garmin's convention

    //! `bezel_text` -- fixed text
    const BEZEL_TEXT_X as Number = 130;
    const BEZEL_TEXT_Y as Number = 130;
    const BEZEL_TEXT_WIDTH as Number = 17;  // widest rendering "BEZEL" is 17 px (estimated)
    const BEZEL_TEXT_ANGLE as Float = 0.0f;  // 90deg clockwise from 12 o'clock, in Garmin's convention
    const BEZEL_TEXT_RADIUS as Number = 57;

    //! `dial_numbers` -- a radial pattern: 3 copies, 12 degrees apart
    const DIAL_NUMBERS_X as Number = 130;  // the centre every copy turns about
    const DIAL_NUMBERS_Y as Number = 130;
    const DIAL_NUMBERS_0_X as Number = 0;  // template, part 0: text (the anchor)
    const DIAL_NUMBERS_0_Y as Number = -104;

    //! `dial_ring` -- a radial pattern: 3 copies, 12 degrees apart
    const DIAL_RING_X as Number = 130;  // the centre every copy turns about
    const DIAL_RING_Y as Number = 130;
    const DIAL_RING_0_X as Number = 0;  // template, part 0: text (the anchor)
    const DIAL_RING_0_Y as Number = 0;
    const DIAL_RING_0_RADIUS as Number = 78;  // curve: radial's own circle radius
}
