// `monkey.jungle` generation. Port of wfb/emit/jungle.py.
//
// Directories are keyed by device id, not `deviceFamily`: two devices of
// one family can differ in system-font metrics and API level, so their
// resolved `Layout` modules genuinely differ.
import type { Device } from "../devices/device.ts";
import type { Face } from "../ir/model.ts";

export function render(face: Face, devices: readonly Device[]): string {
  const name = face.source_path.slice(face.source_path.lastIndexOf("/") + 1);
  const lines = [
    `# Generated by garmin-wf-builder from ${name} -- do not edit.`,
    "#",
    "# Shared code comes first; each device then adds its own resolved Layout",
    "# module. Resources are found by the default jungle's own conventions.",
    "",
    "project.manifest = manifest.xml",
    "",
    "# Strict typechecking, because a generator has no excuse for emitting code",
    "# that fails it. Optimization 3z is the lowest level at which the compiler's",
    "# constant-folding and lexical-only-constants passes run; without them the",
    "# Rez.Styles module survives into the build and costs memory for nothing.",
    "project.typecheck = strict",
    "project.optimization = 3z",
    "",
    "# The default source path is the whole project tree, which would sweep in",
    "# every device's Layout module at once. Narrow it to the shared code, then",
    "# let each device add its own.",
    "base.sourcePath = source;runtime-lib",
    "",
    "# resourcePath is deliberately not set: the default jungle already places",
    "# resources/ and resources-<device>/ on every device's resource path, and",
    "# naming them again would add each file twice.",
    "",
  ];
  for (const device of devices) {
    lines.push(`# ${device.id}: ${device.width}x${device.height} ${device.shape}, family ${device.deviceFamily}`);
    lines.push(`${device.id}.sourcePath = $(${device.id}.sourcePath);source-${device.id}`);
    lines.push("");
  }
  return lines.join("\n").replace(/\n+$/, "") + "\n";
}
