// `manifest.xml` generation.
//
// The permission set is derived from the bindings: a missing permission
// fails silently on the watch (the API returns null), the most common
// "works in the simulator, blank on the wrist" failure.
import * as launchable from "../complications.ts";
import type { Device } from "../devices/device.ts";
import type { Face } from "../ir/model.ts";
import { holdTargets } from "./monkeyc/common.ts";
import { readsUserProfile } from "./monkeyc/slot_scale.ts";
import { escape } from "./xml.ts";
import { BASE_API_LEVEL } from "../build.ts";

/** The floor every generated face declares; newer APIs are guarded per device at runtime. */
export function apiLevel(_face: Face): string {
  return BASE_API_LEVEL;
}

/** The permissions the design's bindings imply, in a stable order. */
export function permissions(face: Face): string[] {
  const needed = new Set(face.requirements().permissions);
  if (holdTargets(face).length > 0 || face.config_data.size > 0) needed.add(launchable.EXIT_TO_PERMISSION);
  if (readsUserProfile(face)) needed.add("UserProfile");
  return [...needed].sort();
}

/** Languages to declare: English only, since every declared language multiplies the resource table. */
export function languages(_devices: readonly Device[]): string[] {
  return ["eng"];
}

export function render(face: Face, devices: readonly Device[]): string {
  const uuid = face.uuid.replaceAll("-", "");
  const name = face.source_path.slice(face.source_path.lastIndexOf("/") + 1);
  const lines = [
    '<?xml version="1.0"?>',
    "<!--",
    `    Generated by garmin-wf-builder from ${name}. Do not edit.`,
    "",
    "    Permissions below are derived from the design's data bindings, not",
    "    hand-maintained. A binding added to the YAML adds its permission here",
    "    automatically; a binding removed takes its permission away.",
    "-->",
    '<iq:manifest version="3" xmlns:iq="http://www.garmin.com/xml/connectiq">',
    `    <iq:application id="${uuid}"`,
    '                    type="watchface"',
    '                    name="@Strings.AppName"',
    `                    entry="${face.entry}App"`,
    '                    launcherIcon="@Drawables.LauncherIcon"',
    `                    minApiLevel="${apiLevel(face)}">`,
    "        <iq:products>",
  ];
  for (const device of devices) lines.push(`            <iq:product id="${device.id}"/>`);
  lines.push("        </iq:products>");
  const perms = permissions(face);
  if (perms.length > 0) {
    lines.push("        <iq:permissions>");
    for (const permission of perms) lines.push(`            <iq:uses-permission id="${escape(permission)}"/>`);
    lines.push("        </iq:permissions>");
  } else {
    lines.push("        <!-- No binding in this design requires a permission. -->");
    lines.push("        <iq:permissions/>");
  }
  lines.push("        <iq:languages>");
  for (const language of languages(devices)) lines.push(`            <iq:language>${language}</iq:language>`);
  lines.push("        </iq:languages>");
  lines.push("        <iq:barrels/>");
  lines.push("    </iq:application>");
  lines.push("</iq:manifest>");
  return lines.join("\n") + "\n";
}
