"""``monkey.jungle`` generation.

Per-device specialisation is a first-class output, not an afterthought
(ADR 0003): the jungle, the per-device resource directories and the per-device
source directories are emitted together, so they cannot drift.

Directories are keyed by **device id**, not by ``deviceFamily``.  ADR 0004 3b is
right that ``deviceFamily`` is the resource-qualifier name and must be read
rather than derived -- but it is not unique enough to key generated layout on:
``fenix8solar47mm`` and ``fr955`` are both ``round-260x260`` and yet have
different system-font pixel metrics and different API levels, so their resolved
``Layout`` modules genuinely differ.  The family is recorded in each generated
header for reference.
"""

from __future__ import annotations

from ..devices import Device
from ..ir import Face


def render(face: Face, devices: list[Device]) -> str:
    lines = [
        f"# Generated by garmin-wf-builder from {face.source_path.name} -- do not edit.",
        "#",
        "# Shared code comes first; each device then adds its own resolved Layout",
        "# module. Resources are found by the default jungle's own conventions.",
        "",
        "project.manifest = manifest.xml",
        "",
        "# Strict typechecking, because a generator has no excuse for emitting code",
        "# that fails it. Optimization 3z is the lowest level at which the compiler's",
        "# constant-folding and lexical-only-constants passes run; without them the",
        "# Rez.Styles module survives into the build and costs memory for nothing.",
        "project.typecheck = strict",
        "project.optimization = 3z",
        "",
        "# The default source path is the whole project tree, which would sweep in",
        "# every device's Layout module at once. Narrow it to the shared code, then",
        "# let each device add its own.",
        "base.sourcePath = source;runtime-lib",
        "",
        "# resourcePath is deliberately not set: the default jungle already places",
        "# resources/ and resources-<device>/ on every device's resource path, and",
        "# naming them again would add each file twice.",
        "",
    ]
    for device in devices:
        lines.append(f"# {device.id}: {device.width}x{device.height} "
                     f"{device.shape}, family {device.device_family}")
        lines.append(
            f"{device.id}.sourcePath = $({device.id}.sourcePath);source-{device.id}"
        )
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"
