"""``manifest.xml`` generation.

The single strongest justification for the whole project lives here: **the
permission set is derived from the bindings**.  A missing permission does not
fail loudly on a Garmin device -- the API returns null and the element simply
never appears, with no diagnostic anywhere.  That is the most common
"works in the simulator, blank on the wrist" failure, and a compiler that knows
every source a face reads can make it structurally impossible.

The language list matters too, though less obviously: a manifest with no
declared languages makes the compiler ignore language-specific resources and
carry a much larger resource table, which on this measurement cost about 12 KB
of foreground data for an otherwise empty face.
"""

from __future__ import annotations

from xml.sax.saxutils import escape

from .. import complications as launchable
from ..devices import Device
from ..ir import Face
from .monkeyc import hold_targets

#: The floor every generated face declares, and the only level this compiler
#: ever emits.  ``manifest.xml`` is one file shared by every target device
#: (`<iq:products>` lists them all under one `minApiLevel`), so raising it
#: for a feature one device needs raises it for every device in the build --
#: and a device whose own ConnectIQ ceiling sits below the raised floor
#: cannot build at all, even on a design that never touches the feature on
#: it (a floor of 4.2.0 for complications would fail `fenix6`, 3.4.5).
#:
#: 3.1.0 is the lowest installed ceiling (`fenix5`/`fenix5x`, 3.1.6): every
#: API the generator emits unguarded was audited against `fenix5`'s own
#: `api.debug.xml`, and anything newer (`Dc.setAntiAlias`,
#: `Toybox.Complications`, vector fonts, AOD, the `config:` editor) is
#: guarded at *runtime* per device via `wfb.availability` -- never by a
#: level compare (CLAUDE.md constraint 6: fr955 is 5.2.0 and still lacks
#: `WatchFaceDelegate.onTap`).  `permissions()` still derives
#: `ComplicationSubscriber` regardless of whether every target can use it:
#: an unreachable permission is harmless, unlike an unreachable
#: `minApiLevel`.  A device below this floor is a friendly `target` build
#: error (`wfb.build.select_devices`); `tests/test_build.py::
#: test_every_installed_device_at_the_floor_or_above_builds_warning_free`
#: proves the rest build.
BASE_API_LEVEL = "3.1.0"


def api_level(face: Face) -> str:
    """The floor every generated face declares -- always :data:`BASE_API_LEVEL`.

    Kept as a function, not a bare constant reference at the call site, so a
    future feature that genuinely cannot be runtime-guarded (unlike
    complications) has exactly one place to raise it again -- and so it
    stays obvious from the name, at the `render()` call site below, that the
    floor is a considered decision rather than a magic string.
    """
    return BASE_API_LEVEL


def permissions(face: Face) -> list[str]:
    """The permissions implied by the design's bindings, in a stable order.

    Bindings are not the only thing that implies one: an `on_hold:` compiles to
    `Complications.exitTo`, and `Toybox.Complications` is gated by
    `ComplicationSubscriber` (the SDK's own permission table marks it
    available to a Watch Face -- checked, not assumed). A design can therefore
    need that permission while reading no complication value at all.

    A `config: data:` slot needs it too, for the same reason it is not a
    catalogue reader `face.requirements()` would otherwise see: which type
    the wearer picked is not known until runtime, so
    `WfbComplications.valueOf` is called regardless of what the design binds
    directly.
    """
    needed = set(face.requirements().permissions)
    if hold_targets(face) or face.config_data:
        needed.add(launchable.EXIT_TO_PERMISSION)
    return sorted(needed)


def languages(devices: list[Device]) -> list[str]:
    """Languages to declare.

    Only English is emitted: the face has no translatable strings beyond its own
    name, and every declared language multiplies the resource table.  This is a
    deliberate scope decision, recorded here rather than left implicit.
    """
    return ["eng"]


def render(face: Face, devices: list[Device]) -> str:
    uuid = face.uuid.replace("-", "")
    lines = [
        '<?xml version="1.0"?>',
        "<!--",
        f"    Generated by garmin-wf-builder from {face.source_path.name}. Do not edit.",
        "",
        "    Permissions below are derived from the design's data bindings, not",
        "    hand-maintained. A binding added to the YAML adds its permission here",
        "    automatically; a binding removed takes its permission away.",
        "-->",
        '<iq:manifest version="3" xmlns:iq="http://www.garmin.com/xml/connectiq">',
        f'    <iq:application id="{uuid}"',
        '                    type="watchface"',
        '                    name="@Strings.AppName"',
        f'                    entry="{face.entry}App"',
        '                    launcherIcon="@Drawables.LauncherIcon"',
        f'                    minApiLevel="{api_level(face)}">',
        "        <iq:products>",
    ]
    for device in devices:
        lines.append(f'            <iq:product id="{device.id}"/>')
    lines.append("        </iq:products>")

    perms = permissions(face)
    if perms:
        lines.append("        <iq:permissions>")
        for permission in perms:
            lines.append(f'            <iq:uses-permission id="{escape(permission)}"/>')
        lines.append("        </iq:permissions>")
    else:
        lines.append("        <!-- No binding in this design requires a permission. -->")
        lines.append("        <iq:permissions/>")

    lines.append("        <iq:languages>")
    for language in languages(devices):
        lines.append(f"            <iq:language>{language}</iq:language>")
    lines.append("        </iq:languages>")
    lines.append("        <iq:barrels/>")
    lines.append("    </iq:application>")
    lines.append("</iq:manifest>")
    return "\n".join(lines) + "\n"
