"""Monkey C generation.

ADR 0003 sets the bar: the generated code is reviewed, debugged and extended by
a human, so it must read as though someone wrote it.  Concretely --

* symbol names are derived from element ids, so they are stable across builds;
* a header cites the source file and the generator version;
* every drawing block carries a comment naming the YAML element it came from;
* layout constants are named in a per-device ``Layout`` module rather than
  inlined as bare numbers;
* every nullable read is guarded, and the guard states the ``when_absent``
  policy that produced it.

The code targets ``-l 3`` (strict typecheck) cleanly.  A generator has no excuse
for emitting code that fails strict checking.
"""

from __future__ import annotations

from dataclasses import dataclass

from .. import __version__, catalog, formatting, icons
from ..catalog import READERS, Tier, Type
from ..ir import Expression, Face, IconElement, Progress, Shape, Text, font_resource_id
from ..layout import (
    PlacedIcon, PlacedProgress, PlacedShape, PlacedText, ResolvedFace,
)
from ..units import IntBox
from .writer import Writer

#: Base Toybox imports every generated face needs.
_BASE_IMPORTS = ("Toybox.Graphics", "Toybox.Lang", "Toybox.WatchUi")


@dataclass
class SourceFile:
    """One generated file, and where it belongs in the project."""

    #: Relative to the build directory, e.g. ``source/SliceView.mc``.
    path: str
    text: str


def source_label(path) -> str:
    """The design's path as it should appear in a generated header.

    Relative to the working directory when it is under it, and the bare filename
    otherwise.  An absolute path would make generated output differ between
    machines, which would defeat the golden-file tests and make every diff noisy.
    """
    import os
    from pathlib import Path

    try:
        relative = os.path.relpath(Path(path).resolve(), Path.cwd())
    except (OSError, ValueError):
        return Path(path).name
    return Path(path).name if relative.startswith("..") else relative


def header(face: Face, extra: str = "") -> str:
    lines = [
        f"Generated by garmin-wf-builder {__version__} -- do not edit.",
        f"Source:    {source_label(face.source_path)}",
        f"Face:      {face.name} (format {face.format})",
    ]
    if extra:
        lines.append(extra)
    lines.append("Regenerate with `wfb build`.  Edits here are lost on the next build;")
    lines.append("hand-written Monkey C belongs in a `raw` element instead (ADR 0007).")
    return "\n".join(lines)


# --------------------------------------------------------------------------
# shared sources


def emit_app(face: Face) -> SourceFile:
    w = Writer()
    w.doc(header(face)).blank()
    w.lines("import Toybox.Application;", "import Toybox.Lang;", "import Toybox.WatchUi;").blank()
    w.doc(f"The application entry point for {face.name!r}.")
    with w.block(f"class {face.entry}App extends Application.AppBase"):
        with w.block("function initialize()"):
            w.line("AppBase.initialize();")
        w.blank()
        with w.block("function getInitialView() as [Views] or [Views, InputDelegates]"):
            w.line(f"return [ new {face.entry}View() ];")
    return SourceFile(f"source/{face.entry}App.mc", w.render())


def emit_palette(face: Face) -> SourceFile:
    w = Writer()
    w.doc(header(face)).blank()
    w.lines("import Toybox.Lang;").blank()
    w.doc(
        "Colours declared in the design's `palette:` block.\n"
        "\n"
        "Elements reference these by name rather than by hex, so a colour can be\n"
        "changed in one place and linted in one place."
    )
    with w.block("module Palette"):
        for index, (name, color) in enumerate(face.palette.items()):
            if index:
                w.blank()
            w.doc(f"`palette.{name}` = {color}")
            w.line(f"const {name.upper()} as Number = {color.as_monkeyc()};")
    return SourceFile("source/Palette.mc", w.render())


def emit_icon_glyphs(face: Face) -> SourceFile:
    """`source/IconGlyphs.mc`: catalogue name -> drawn glyph, for a dynamic
    (`icon_for:`) icon.

    A static icon's glyph is already known at build time and gets baked
    directly into its `drawText` call as a literal (see `_emit_icon` below) --
    no lookup needed. A dynamic icon's name is only known on-device, so
    *something* has to resolve it there. This is that something, generated
    straight from `wfb.icon_catalog.CATALOG` rather than hand-maintained, so
    it cannot drift from the font this project actually bakes: the
    weather-selection logic in `WfbWeather.mc` only ever produces a name
    (`chooseIcon`), and this is the one place, for every icon in the
    catalogue and not just weather ones, where a name becomes a character.

    Scoped to the names a dynamic icon could actually produce in this design
    -- every catalogue entry `icon_for:`'s underlying source table
    (`wfb.icons.GARMIN_WEATHER_CONDITION_ICON`) can select -- not the whole
    catalogue, so a design with one `icon_for:` element does not bake a
    lookup table for icons it never draws dynamically.
    """
    names = sorted(set(icons.GARMIN_WEATHER_CONDITION_ICON.values()))
    w = Writer()
    w.doc(header(face)).blank()
    w.lines("import Toybox.Lang;").blank()
    w.doc(
        "Catalogue name -> drawn glyph, for a dynamic (`icon_for:`) icon.\n"
        "\n"
        "Generated directly from wfb.icon_catalog.CATALOG -- see wfb/icons.py's\n"
        "module docstring for why this table, rather than WfbWeather.mc, is where\n"
        "a name becomes a character."
    )
    with w.block("module IconGlyphs"):
        with w.block("function glyph(name as String) as String"):
            with w.block("switch (name)"):
                for name in names:
                    codepoint = icons.CATALOG[name].codepoint
                    w.line(f'case "{name}": return "{codepoint}";')
                w.line(f'default: return "{icons.FALLBACK_CODEPOINT}";')
    return SourceFile("source/IconGlyphs.mc", w.render())


# --------------------------------------------------------------------------
# per-device layout constants


def emit_layout(resolved: ResolvedFace) -> SourceFile:
    face, device = resolved.face, resolved.device
    w = Writer()
    w.doc(
        header(
            face,
            f"Device:    {device.id} -- {device.width}x{device.height} {device.shape}, "
            f"{device.display_type}, family {device.device_family}",
        )
    ).blank()
    w.lines("import Toybox.Lang;").blank()
    w.doc(
        f"Layout resolved for {device.id}.\n"
        "\n"
        "Every value here came from a relative unit in the design -- percentages of\n"
        "the parent box, fractions of the screen's minor radius, angles measured\n"
        "clockwise from 12 o'clock.  Resolving them here means the device performs\n"
        "no layout arithmetic at all, which costs neither memory nor frame time."
    )
    with w.block("module Layout"):
        w.doc("The screen, for reference.")
        w.line(f"const SCREEN_WIDTH as Number = {device.width};")
        w.line(f"const SCREEN_HEIGHT as Number = {device.height};")
        for placed in resolved.items:
            constants = _layout_constants(placed)
            if not constants:
                continue
            w.blank()
            w.doc(f"`{placed.id}` -- {_describe(placed)}")
            for name, value, note in constants:
                suffix = f"  // {note}" if note else ""
                w.line(f"const {name} as {_mc_type(value)} = {_mc_number(value)};{suffix}")
        clip = resolved.clip_for("low_power")
        if clip is not None:
            w.blank()
            w.doc(
                "The clip rectangle for low-power updates.\n"
                "\n"
                "setClip is charged by region *area* -- every pixel inside it counts as\n"
                "modified whenever any does -- so this is the tightest box covering all\n"
                f"low-power elements: {clip.area} px, "
                f"{100.0 * clip.area / (device.width * device.height):.0f}% of the screen."
            )
            w.line(f"const LOW_POWER_CLIP_X as Number = {clip.x};")
            w.line(f"const LOW_POWER_CLIP_Y as Number = {clip.y};")
            w.line(f"const LOW_POWER_CLIP_WIDTH as Number = {clip.width};")
            w.line(f"const LOW_POWER_CLIP_HEIGHT as Number = {clip.height};")
    return SourceFile(f"source-{device.id}/Layout.mc", w.render())


def _layout_constants(placed) -> list[tuple[str, float, str]]:
    prefix = _const_prefix(placed.id)
    out: list[tuple[str, float, str]] = []
    if isinstance(placed, PlacedShape):
        element = placed.element
        if element.shape in ("circle", "line"):
            out.append((f"{prefix}_CX", placed.center[0], ""))
            out.append((f"{prefix}_CY", placed.center[1], ""))
        if element.shape == "circle":
            out.append((f"{prefix}_RADIUS", placed.radius, ""))
        elif element.shape == "line":
            out.append((f"{prefix}_END_X", placed.end[0], ""))
            out.append((f"{prefix}_END_Y", placed.end[1], ""))
            out.append((f"{prefix}_THICKNESS", placed.thickness, ""))
        else:
            out.append((f"{prefix}_X", placed.box.x, ""))
            out.append((f"{prefix}_Y", placed.box.y, ""))
            out.append((f"{prefix}_WIDTH", placed.box.width, ""))
            out.append((f"{prefix}_HEIGHT", placed.box.height, ""))
            if element.shape == "rounded_rectangle":
                out.append((f"{prefix}_CORNER", placed.corner_radius, ""))
    elif isinstance(placed, PlacedText):
        out.append((f"{prefix}_X", placed.anchor_point[0], ""))
        out.append((f"{prefix}_Y", placed.anchor_point[1], ""))
        note = f'widest rendering "{placed.widest}" is {placed.measured_width} px'
        if placed.width_is_estimated:
            note += " (estimated)"
        out.append((f"{prefix}_WIDTH", placed.measured_width, note))
    elif isinstance(placed, PlacedProgress):
        out.append((f"{prefix}_CX", placed.center[0], ""))
        out.append((f"{prefix}_CY", placed.center[1], ""))
        if placed.element.style == "arc":
            out.append((f"{prefix}_RADIUS", placed.radius, ""))
            out.append((f"{prefix}_THICKNESS", placed.thickness, "pen width; there is no filled-arc primitive"))
            out.append((f"{prefix}_START", float(placed.garmin_start),
                        f"{placed.start_angle:g}deg clockwise from 12 o'clock, in Garmin's convention"))
            out.append((f"{prefix}_SWEEP", float(placed.sweep), "clockwise-positive degrees"))
        else:
            out.append((f"{prefix}_X", placed.box.x, ""))
            out.append((f"{prefix}_Y", placed.box.y, ""))
            out.append((f"{prefix}_WIDTH", placed.box.width, ""))
            out.append((f"{prefix}_HEIGHT", placed.box.height, ""))
    elif isinstance(placed, PlacedIcon):
        out.append((f"{prefix}_CX", placed.center[0], ""))
        out.append((f"{prefix}_CY", placed.center[1], ""))
    return out


# --------------------------------------------------------------------------
# the view


def emit_view(resolved: ResolvedFace) -> SourceFile:
    face, device = resolved.face, resolved.device
    plan = ReadPlan(resolved)
    if resolved.in_mode("low_power") and device.supports_partial_update:
        plan.modules.add("Toybox.System")  # onPowerBudgetExceeded reports via println

    w = Writer()
    w.doc(header(face, f"Device:    {device.id}")).blank()
    for module in sorted(set(_BASE_IMPORTS) | plan.modules):
        w.line(f"import {module};")
    w.blank()

    w.doc(
        f"{face.name}.\n"
        "\n"
        "One private method per design element, in draw order.  Each is named after\n"
        "the element's `id:` in the source YAML, so a change on screen leads back to\n"
        "a line in the design file."
    )
    with w.block(f"class {face.entry}View extends WatchUi.WatchFace"):
        _emit_fields(w, resolved)
        _emit_cache_fields(w, plan)
        _emit_initialize(w, face)
        _emit_on_layout(w, resolved)
        _emit_on_update(w, resolved, plan)
        if resolved.in_mode("low_power") and device.supports_partial_update:
            _emit_on_partial_update(w, resolved, plan)
        _emit_sleep_hooks(w, resolved)
        for placed in resolved.items:
            if placed.kind == "group":
                continue
            w.blank()
            _emit_element_method(w, resolved, placed, plan)
    return SourceFile(f"source/{face.entry}View.mc", w.render())


def _emit_fields(w: Writer, resolved: ResolvedFace) -> None:
    loaded = _loaded_fonts(resolved)
    if not loaded:
        return
    w.doc("Bitmap fonts -- custom text and icon glyphs alike -- loaded once in\n"
          "onLayout rather than per frame.")
    for name in loaded:
        w.line(f"private var _{_field(name)} as FontResource?;")
    w.blank()


def _emit_cache_fields(w: Writer, plan: "ReadPlan") -> None:
    slow = plan.slow_readers()
    if not slow:
        return
    w.doc("`slow`-tier reads, cached here instead of re-read every frame --\n"
          "see WfbCache.mc and ReadPlan.emit_reads.")
    for name in slow:
        reader = READERS[name]
        w.line(f"private var _{reader.name}Cache as {reader.monkeyc_type};")
        w.line(f"private var _{reader.name}CacheTime as Number?;")
    w.blank()


def _emit_initialize(w: Writer, face: Face) -> None:
    with w.block("function initialize()"):
        w.line("WatchFace.initialize();")
    w.blank()


def _emit_on_layout(w: Writer, resolved: ResolvedFace) -> None:
    loaded = _loaded_fonts(resolved)
    w.doc("Load resources once.  Loading is expensive and must not happen per frame.")
    with w.block("function onLayout(dc as Dc) as Void"):
        if not loaded:
            w.line("// No resources to load: this face draws entirely from system fonts.")
        for name in loaded:
            resource = font_resource_id(name)
            w.line(
                f"_{_field(name)} = WatchUi.loadResource(Rez.Fonts.{resource}) as FontResource;"
            )
    w.blank()


def _emit_on_update(w: Writer, resolved: ResolvedFace, plan: "ReadPlan") -> None:
    w.doc(
        "Draw the full face.\n"
        "\n"
        "Called once a minute in low-power mode and once a second while the watch is\n"
        "awake."
    )
    with w.block("function onUpdate(dc as Dc) as Void"):
        w.line("dc.clearClip();")
        plan.emit_reads(w, "active")
        w.blank()
        for placed in resolved.items:
            if placed.kind == "group" or "active" not in placed.element.modes:
                continue
            w.line(f"{_method(placed.id)}(dc{plan.arguments(placed)});")
    w.blank()


def _emit_on_partial_update(w: Writer, resolved: ResolvedFace, plan: "ReadPlan") -> None:
    clip = resolved.clip_for("low_power")
    fraction = 100.0 * clip.area / (resolved.device.width * resolved.device.height) if clip else 0
    w.doc(
        "Redraw only the low-power elements, once a second, while asleep.\n"
        "\n"
        "The clip is the tightest box around them because setClip is charged by\n"
        f"region area: {fraction:.0f}% of the screen here.  Overrunning the power\n"
        "budget calls onPowerBudgetExceeded and disables partial updates for the\n"
        "rest of the app's lifecycle, so only frame-tier sources are read here --\n"
        "the compiler rejects anything slower."
    )
    with w.block("function onPartialUpdate(dc as Dc) as Void"):
        w.line(
            "dc.setClip(Layout.LOW_POWER_CLIP_X, Layout.LOW_POWER_CLIP_Y,"
        )
        w.line(
            "           Layout.LOW_POWER_CLIP_WIDTH, Layout.LOW_POWER_CLIP_HEIGHT);"
        )
        plan.emit_reads(w, "low_power")
        w.blank()
        for placed in resolved.items:
            if placed.kind == "group" or "low_power" not in placed.element.modes:
                continue
            w.line(f"{_method(placed.id)}(dc{plan.arguments(placed)});")
        w.line("dc.clearClip();")
    w.blank()


def _emit_sleep_hooks(w: Writer, resolved: ResolvedFace) -> None:
    w.doc("Awake: full-power updates resume.")
    with w.block("function onExitSleep() as Void"):
        w.line("WatchUi.requestUpdate();")
    w.blank()
    w.doc("Asleep: the next onUpdate draws the low-power layout.")
    with w.block("function onEnterSleep() as Void"):
        w.line("WatchUi.requestUpdate();")
    w.blank()
    if resolved.in_mode("low_power") and resolved.device.supports_partial_update:
        w.doc(
            "The power budget was exceeded and partial updates are now off for the\n"
            "rest of this app's lifecycle.  Nothing can re-enable them; the face\n"
            "simply falls back to once-a-minute updates."
        )
        with w.block("function onPowerBudgetExceeded(powerInfo as WatchUi.WatchFacePowerInfo) as Void"):
            w.line('System.println("wfb: partial-update power budget exceeded: "')
            w.line('               + powerInfo.executionTimeAverage.format("%.2f") + " ms average");')
        w.blank()


# --------------------------------------------------------------------------
# one method per element


def _emit_element_method(w: Writer, resolved: ResolvedFace, placed, plan: "ReadPlan") -> None:
    element = placed.element
    w.doc(_method_doc(placed))
    signature = f"private function {_method(placed.id)}(dc as Dc{plan.parameters(placed)}) as Void"
    placeholder = (
        isinstance(placed, PlacedText)
        and getattr(element, "when_absent", None) == "placeholder"
    )
    with w.block(signature):
        declarations = plan.declarations(placed)
        if declarations:
            w.comment("the values this element is bound to")
            for name, read in declarations:
                w.line(f"var {name} = {read};")
            w.blank()
        guards = plan.guards(placed)
        if guards and not placeholder:
            _emit_guard(w, placed, guards)
        if isinstance(placed, PlacedShape):
            _emit_shape(w, placed)
        elif isinstance(placed, PlacedText):
            _emit_text(w, resolved, placed, guards)
        elif isinstance(placed, PlacedProgress):
            _emit_progress(w, placed)
        elif isinstance(placed, PlacedIcon):
            _emit_icon(w, placed)


def _method_doc(placed) -> str:
    element = placed.element
    lines = [f"`{element.id}` -- {_describe(placed)}."]
    bindings = [e.text for e in element.expressions() if e.sources]
    if bindings:
        lines.append("")
        lines.append("Bound to " + _and_list(f"`{text}`" for text in bindings) + ".")
    policy = getattr(element, "when_absent", None)
    if policy:
        lines.append(f"When the value is absent: {policy}.")
    modes = ", ".join(element.modes)
    lines.append(f"Drawn in: {modes}.")
    return "\n".join(lines)


def _emit_guard(w: Writer, placed, guards: list[str]) -> None:
    """Emit the null check, and say which `when_absent:` produced it."""
    element = placed.element
    policy = getattr(element, "when_absent", None) or "hide"
    condition = " || ".join(f"{name} == null" for name in guards)
    w.comment(f"when_absent: {policy}")
    with w.block(f"if ({condition})"):
        w.line("return;")
    w.blank()


def _emit_shape(w: Writer, placed: PlacedShape) -> None:
    element = placed.element
    prefix = _const_prefix(placed.id)
    w.line(f"dc.setColor({_color(element.color)}, Graphics.COLOR_TRANSPARENT);")
    if element.shape == "rectangle":
        w.line(f"dc.fillRectangle(Layout.{prefix}_X, Layout.{prefix}_Y,")
        w.line(f"                 Layout.{prefix}_WIDTH, Layout.{prefix}_HEIGHT);")
    elif element.shape == "rounded_rectangle":
        w.line(f"dc.fillRoundedRectangle(Layout.{prefix}_X, Layout.{prefix}_Y,")
        w.line(f"                        Layout.{prefix}_WIDTH, Layout.{prefix}_HEIGHT,")
        w.line(f"                        Layout.{prefix}_CORNER);")
    elif element.shape == "circle":
        if element.filled:
            w.line(f"dc.fillCircle(Layout.{prefix}_CX, Layout.{prefix}_CY, Layout.{prefix}_RADIUS);")
        else:
            w.line(f"dc.setPenWidth({placed.thickness});")
            w.line(f"dc.drawCircle(Layout.{prefix}_CX, Layout.{prefix}_CY, Layout.{prefix}_RADIUS);")
            w.line("dc.setPenWidth(1);")
    elif element.shape == "line":
        w.line(f"dc.setPenWidth(Layout.{prefix}_THICKNESS);")
        w.line(
            f"dc.drawLine(Layout.{prefix}_CX, Layout.{prefix}_CY, "
            f"Layout.{prefix}_END_X, Layout.{prefix}_END_Y);"
        )
        w.line("dc.setPenWidth(1);")


def _emit_text(w: Writer, resolved: ResolvedFace, placed: PlacedText, guards: list[str]) -> None:
    element = placed.element
    if element.literal is not None:
        _emit_text_draw(w, placed, f'"{element.literal}"')
        return

    value_code = formatting.emit(
        element.format or "{}",
        element.value.code,
        element.value.value.type,
    )
    if element.when_absent == "placeholder" and guards:
        # Build the string once rather than duplicating the draw call in both
        # branches: the placeholder is a different *value*, not a different draw.
        w.comment(f"when_absent: placeholder")
        available = " && ".join(f"{name} != null" for name in guards)
        w.line(f'var text = "{element.placeholder}";')
        with w.block(f"if ({available})"):
            w.line(f"text = {value_code};")
        w.blank()
        _emit_text_draw(w, placed, "text")
        return
    _emit_text_draw(w, placed, value_code)


def _emit_text_draw(w: Writer, placed: PlacedText, value_code: str) -> None:
    element = placed.element
    prefix = _const_prefix(placed.id)
    justify = " | ".join(f"Graphics.{flag}" for flag in placed.justify)
    if placed.font_is_custom:
        w.line(f"var font = _{_field(placed.font_reference)};")
        with w.block("if (font == null)"):
            w.line("return;  // the font resource failed to load")
        w.blank()
        font_expr = "font"
    else:
        font_expr = f"Graphics.{placed.font_reference}"
    w.line(f"dc.setColor({_color(element.color)}, Graphics.COLOR_TRANSPARENT);")
    w.line(f"dc.drawText(Layout.{prefix}_X, Layout.{prefix}_Y, {font_expr},")
    w.line(f"            {value_code},")
    w.line(f"            {justify});")


def _emit_progress(w: Writer, placed: PlacedProgress) -> None:
    element = placed.element
    prefix = _const_prefix(placed.id)
    if element.style == "arc":
        if element.track_color is not None:
            w.comment("the unfilled track")
            w.line(f"dc.setColor({_color(element.track_color)}, Graphics.COLOR_TRANSPARENT);")
            w.line(
                f"WfbArc.drawSpan(dc, Layout.{prefix}_CX, Layout.{prefix}_CY, "
                f"Layout.{prefix}_RADIUS,"
            )
            w.line(
                f"                Layout.{prefix}_THICKNESS, Layout.{prefix}_START, "
                f"Layout.{prefix}_SWEEP);"
            )
            w.blank()
        w.comment("the filled portion")
        w.line(f"dc.setColor({_color(element.color)}, Graphics.COLOR_TRANSPARENT);")
        w.line(
            f"WfbArc.drawProgress(dc, Layout.{prefix}_CX, Layout.{prefix}_CY, "
            f"Layout.{prefix}_RADIUS,"
        )
        w.line(
            f"                    Layout.{prefix}_THICKNESS, Layout.{prefix}_START, "
            f"Layout.{prefix}_SWEEP,"
        )
        w.line(f"                    {_fraction(element)});")
        return

    if element.track_color is not None:
        w.line(f"dc.setColor({_color(element.track_color)}, Graphics.COLOR_TRANSPARENT);")
        w.line(
            f"dc.fillRectangle(Layout.{prefix}_X, Layout.{prefix}_Y, "
            f"Layout.{prefix}_WIDTH, Layout.{prefix}_HEIGHT);"
        )
        w.blank()
    w.line(f"var filled = (Layout.{prefix}_WIDTH * {_fraction(element)}).toNumber();")
    w.line(f"dc.setColor({_color(element.color)}, Graphics.COLOR_TRANSPARENT);")
    w.line(
        f"dc.fillRectangle(Layout.{prefix}_X, Layout.{prefix}_Y, filled, Layout.{prefix}_HEIGHT);"
    )


def _emit_icon(w: Writer, placed: PlacedIcon) -> None:
    """A `drawText` call against the icon's baked glyph -- see `wfb.icons`:
    an icon is a one-character string drawn with a bitmap font, the same
    mechanism any other bound text uses, not a hand-drawn shape.

    A *dynamic* icon (`icon_for:`) draws the same way, except the glyph
    string is resolved in two steps at runtime instead of being a literal
    baked in at build time: `WfbWeather.chooseIcon` picks a catalogue *name*
    from the bound value, and `IconGlyphs.glyph` (generated per project,
    directly from `wfb.icon_catalog.CATALOG`) turns that name into the actual
    character -- the same table any static icon's build-time lookup uses, not
    a second, weather-only one. The font still has every glyph that call
    could return, baked in ahead of time (`wfb.emit.resources.icon_font_specs`).
    """
    element = placed.element
    prefix = _const_prefix(placed.id)
    w.line(f"var font = _{_field(placed.font_key)};")
    with w.block("if (font == null)"):
        w.line("return;  // the icon font resource failed to load")
    w.blank()
    if element.is_dynamic:
        from ..ir import local_name

        condition_local = local_name(element.value_for.sources[0])
        w.comment(f"{element.value_for.text!r} -> a name (WfbWeather) -> a glyph (IconGlyphs)")
        glyph_expr = f"IconGlyphs.glyph(WfbWeather.chooseIcon({condition_local}))"
    else:
        w.comment(f"{element.icon!r}")
        glyph_expr = f'"{element.codepoint}"'
    w.line(f"dc.setColor({_color(element.color)}, Graphics.COLOR_TRANSPARENT);")
    w.line(f"dc.drawText(Layout.{prefix}_CX, Layout.{prefix}_CY, font,")
    w.line(f"            {glyph_expr},")
    w.line("            Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER);")


def _fraction(element: Progress) -> str:
    return f"WfbMath.percent({element.value.code}, {element.maximum.code}) / 100.0"


# --------------------------------------------------------------------------
# the read plan: which API calls happen, and where


class ReadPlan:
    """Decides which reader locals each element needs, and hoists the reads.

    Sources are grouped by reader so that ``ActivityMonitor.getInfo()`` is called
    once per frame no matter how many fields read off it, and every nullable
    field becomes a named local that the element's guard narrows.
    """

    def __init__(self, resolved: ResolvedFace) -> None:
        self.resolved = resolved
        self.modules: set[str] = set()
        self.barrel: set[str] = set(resolved.face.barrel_functions())
        #: Every source an element touches, for reader hoisting.
        self._per_element: dict[str, list[str]] = {}
        #: The subset referenced by compiled expressions, which read through a
        #: named local.  Format specs read their reader directly instead.
        self._bound: dict[str, list[str]] = {}
        self._readers_for_mode: dict[str, list[str]] = {}
        self._analyse()
        if self.slow_readers():
            self.modules.add("Toybox.Time")  # Time.now(), for WfbCache.stale()

    def _analyse(self) -> None:
        for placed in self.resolved.items:
            paths: list[str] = []
            for expression in placed.element.expressions():
                self.modules |= set(expression.modules)
                for path in expression.sources:
                    if path not in paths:
                        paths.append(path)
            # A time format reads the clock (and, for %h, the device settings)
            # even though the format string names no source.
            element = placed.element
            format_paths: list[str] = []
            if (isinstance(element, Text) and element.format
                    and formatting.is_time_spec(element.format)):
                # A date format reads the calendar; a time format reads the clock,
                # and %h additionally reads the 12/24-hour setting.
                if element.value is not None and element.value.value.type is Type.DATE:
                    format_paths.append("date.today")
                else:
                    format_paths.append("time.clock")
                    if "%h" in element.format:
                        format_paths.append("device.is_24_hour")
            self._bound[placed.id] = list(paths)
            paths = paths + [p for p in format_paths if p not in paths]
            self._per_element[placed.id] = paths
            for path in paths:
                self.modules.add(READERS[catalog.CATALOG[path].reader].module)

        for mode in ("active", "low_power", "always_on"):
            readers: list[str] = []
            for placed in self.resolved.items:
                if mode not in placed.element.modes:
                    continue
                for path in self._per_element[placed.id]:
                    reader = catalog.CATALOG[path].reader
                    if reader not in readers:
                        readers.append(reader)
            self._readers_for_mode[mode] = readers

    # -- emission ---------------------------------------------------------

    def slow_readers(self) -> list[str]:
        """Reader names on `Tier.SLOW` this design actually reads.

        Always found under ``active`` mode only: `wfb.ir`'s `_check_tiers`
        rejects binding a non-frame-tier source from a `low_power` or
        `always_on` element, so there is nothing to check here -- a slow
        reader appearing under any other mode would be an IR bug, not a
        design mistake, and `emit_reads` below is written on that assumption.
        """
        return sorted({name for name in self._readers_for_mode.get("active", [])
                       if READERS[name].tier is not Tier.FRAME})

    def emit_reads(self, w: Writer, mode: str) -> None:
        readers = self._readers_for_mode.get(mode) or []
        if not readers:
            return
        tier_note = "frame-tier reads only" if mode != "active" else "data for this frame"
        w.comment(tier_note)
        for name in readers:
            reader = READERS[name]
            if reader.tier is Tier.FRAME:
                w.line(f"var {reader.name} = {reader.call};")
                continue
            # A `slow`-tier reader is cached in a view field instead of called
            # fresh every frame -- see WfbCache.mc and `_emit_cache_fields`.
            cache = f"_{reader.name}Cache"
            cache_time = f"_{reader.name}CacheTime"
            with w.block(f"if (WfbCache.stale({cache_time}, {reader.ttl_seconds}))"):
                w.line(f"{cache} = {reader.call};")
                w.line(f"{cache_time} = Time.now().value();")
            w.line(f"var {reader.name} = {cache};")

    def parameters(self, placed) -> str:
        params = []
        for name in self._readers_used_by(placed):
            reader = READERS[name]
            params.append(f", {reader.name} as {reader.monkeyc_type}")
        return "".join(params)

    def arguments(self, placed) -> str:
        return "".join(f", {READERS[name].name}" for name in self._readers_used_by(placed))

    def guards(self, placed) -> list[str]:
        """Locals the element must null-check, declared in dependency order."""
        from ..ir import local_name

        names: list[str] = []
        for path in self._bound[placed.id]:
            source = catalog.CATALOG[path]
            if source.guard_needed and source.field_name is not None:
                names.append(local_name(path))
        return names

    def declarations(self, placed) -> list[tuple[str, str]]:
        from ..ir import local_name

        out: list[tuple[str, str]] = []
        for path in self._bound[placed.id]:
            source = catalog.CATALOG[path]
            if source.field_name is None:
                continue
            reader = READERS[source.reader]
            read = source.read_expr
            guard_parts = []
            if reader.nullable:
                # The reader itself can be absent -- Activity.getActivityInfo()
                # returns null when there is no activity -- so the field cannot
                # be dereferenced unconditionally.  Narrowing here keeps the
                # element's own `when_absent` guard below unchanged: an absent
                # reader and an absent field are the same thing to the design.
                guard_parts.append(f"{reader.name} != null")
            if source.array_guard is not None:
                # An Array being non-null does not mean it has an element at
                # this index -- a forecast provider can return fewer days than
                # asked for. Short-circuit `&&` means the null check above (if
                # any) always runs first, so `.size()` never hits a null array.
                guard_parts.append(source.array_guard)
            if guard_parts:
                read = f"({' && '.join(guard_parts)}) ? {read} : null"
            out.append((local_name(path), read))
        return out

    def _readers_used_by(self, placed) -> list[str]:
        readers: list[str] = []
        for path in self._per_element[placed.id]:
            reader = catalog.CATALOG[path].reader
            if reader not in readers:
                readers.append(reader)
        return readers

    def sources_for(self, placed) -> list[str]:
        return self._per_element[placed.id]


# --------------------------------------------------------------------------
# naming and small helpers


def _const_prefix(element_id: str) -> str:
    out = []
    for index, char in enumerate(element_id):
        if char.isupper() and index and not element_id[index - 1].isupper():
            out.append("_")
        out.append(char.upper() if char.isalnum() else "_")
    return "".join(out)


def _method(element_id: str) -> str:
    parts = [p for p in element_id.replace("-", "_").split("_") if p]
    return "draw" + "".join(p[:1].upper() + p[1:] for p in parts)


def _field(name: str) -> str:
    parts = [p for p in name.replace("-", "_").split("_") if p]
    return "font" + "".join(p[:1].upper() + p[1:] for p in parts)


def _color(expression: Expression | None) -> str:
    if expression is None:
        return "Graphics.COLOR_WHITE"
    return expression.code


def _loaded_fonts(resolved: ResolvedFace) -> list[str]:
    """Every font resource this view loads once in `onLayout`.

    Covers both an author's declared custom text fonts and the synthetic
    per-size icon fonts (`wfb.icons.font_key`) -- both are bitmap fonts loaded
    the same way, so one list and one loop serves both.
    """
    out: list[str] = []
    for placed in resolved.items:
        if isinstance(placed, PlacedText) and placed.font_is_custom:
            if placed.font_reference not in out:
                out.append(placed.font_reference)
        elif isinstance(placed, PlacedIcon):
            if placed.font_key not in out:
                out.append(placed.font_key)
    return out


def _describe(placed) -> str:
    element = placed.element
    if isinstance(element, Shape):
        return _article(element.shape.replace("_", " "))
    if isinstance(element, Text):
        return "text" if element.value is not None else "fixed text"
    if isinstance(element, Progress):
        return _article(f"{element.style} progress indicator")
    if isinstance(element, IconElement):
        if element.is_dynamic:
            return f"an icon chosen at runtime from {element.value_for.text!r}"
        return f"the {element.icon!r} icon"
    return element.kind


def _and_list(items) -> str:
    items = list(items)
    if len(items) <= 1:
        return "".join(items)
    return ", ".join(items[:-1]) + " and " + items[-1]


def _article(noun: str) -> str:
    return f"{'an' if noun[:1].lower() in 'aeiou' else 'a'} {noun}"


def _mc_type(value: float) -> str:
    return "Float" if isinstance(value, float) else "Number"


def _mc_number(value: float) -> str:
    return f"{value}f" if isinstance(value, float) else str(int(value))
