"""Monkey C generation.

ADR 0003 sets the bar: the generated code is reviewed, debugged and extended by
a human, so it must read as though someone wrote it.  Concretely --

* symbol names are derived from element ids, so they are stable across builds;
* a header cites the source file and the generator version;
* every drawing block carries a comment naming the YAML element it came from;
* layout constants are named in a per-device ``Layout`` module rather than
  inlined as bare numbers;
* every nullable read is guarded, and the guard states the ``when_absent``
  policy that produced it.

The code targets ``-l 3`` (strict typecheck) cleanly.  A generator has no excuse
for emitting code that fails strict checking.
"""

from __future__ import annotations

from dataclasses import dataclass

from .. import __version__, catalog, complications, formatting, icons
from ..catalog import READERS, Tier, Type
from ..ir import (
    Carousel, Expression, Face, IconElement, Progress, Shape, Text,
    carousel_index_field, carousel_slide_done_method, carousel_slide_field,
    carousel_step_method, element_const_prefix, element_method_name, font_resource_id,
)
from ..layout import (
    PlacedCarousel, PlacedIcon, PlacedProgress, PlacedShape, PlacedText, ResolvedFace,
)
from ..units import IntBox
from .writer import Writer

#: Base Toybox imports every generated face needs.
_BASE_IMPORTS = ("Toybox.Graphics", "Toybox.Lang", "Toybox.WatchUi")


@dataclass
class SourceFile:
    """One generated file, and where it belongs in the project."""

    #: Relative to the build directory, e.g. ``source/SliceView.mc``.
    path: str
    text: str


def source_label(path) -> str:
    """The design's path as it should appear in a generated header.

    Relative to the working directory when it is under it, and the bare filename
    otherwise.  An absolute path would make generated output differ between
    machines, which would defeat the golden-file tests and make every diff noisy.
    """
    import os
    from pathlib import Path

    try:
        relative = os.path.relpath(Path(path).resolve(), Path.cwd())
    except (OSError, ValueError):
        return Path(path).name
    return Path(path).name if relative.startswith("..") else relative


def header(face: Face, extra: str = "") -> str:
    lines = [
        f"Generated by garmin-wf-builder {__version__} -- do not edit.",
        f"Source:    {source_label(face.source_path)}",
        f"Face:      {face.name} (format {face.format})",
    ]
    if extra:
        lines.append(extra)
    lines.append("Regenerate with `wfb build`.  Edits here are lost on the next build;")
    lines.append("hand-written Monkey C belongs in a `raw` element instead (ADR 0007).")
    return "\n".join(lines)


# --------------------------------------------------------------------------
# shared sources


def emit_app(face: Face) -> SourceFile:
    interactive = bool(hold_targets(face))
    w = Writer()
    w.doc(header(face)).blank()
    w.lines("import Toybox.Application;", "import Toybox.Lang;", "import Toybox.WatchUi;").blank()
    w.doc(f"The application entry point for {face.name!r}.")
    with w.block(f"class {face.entry}App extends Application.AppBase"):
        with w.block("function initialize()"):
            w.line("AppBase.initialize();")
        w.blank()
        with w.block("function getInitialView() as [Views] or [Views, InputDelegates]"):
            if not interactive:
                w.line(f"return [ new {face.entry}View() ];")
            else:
                w.line(f"var view = new {face.entry}View();")
                w.comment("the `has` guard is the SDK's own idiom (samples/Analog): a watch")
                w.comment("without WatchFaceDelegate still gets the face, just not the holds")
                with w.block("if (WatchUi has :WatchFaceDelegate)"):
                    w.comment("the delegate holds the view so a hold can move a carousel")
                    w.line(f"return [ view, new {face.entry}Delegate(view) ];")
                w.line("return [ view ];")
    return SourceFile(f"source/{face.entry}App.mc", w.render())


def emit_palette(face: Face) -> SourceFile:
    w = Writer()
    w.doc(header(face)).blank()
    w.lines("import Toybox.Lang;").blank()
    w.doc(
        "Colours declared in the design's `palette:` block.\n"
        "\n"
        "Elements reference these by name rather than by hex, so a colour can be\n"
        "changed in one place and linted in one place."
    )
    with w.block("module Palette"):
        for index, (name, color) in enumerate(face.palette.items()):
            if index:
                w.blank()
            w.doc(f"`palette.{name}` = {color}")
            w.line(f"const {name.upper()} as Number = {color.as_monkeyc()};")
    return SourceFile("source/Palette.mc", w.render())


def emit_icon_glyphs(face: Face) -> SourceFile:
    """`source/IconGlyphs.mc`: catalogue name -> drawn glyph, for a dynamic
    (`icon_for:`) icon.

    A static icon's glyph is already known at build time and gets baked
    directly into its `drawText` call as a literal (see `_emit_icon` below) --
    no lookup needed. A dynamic icon's name is only known on-device, so
    *something* has to resolve it there. This is that something, generated
    straight from `wfb.icon_catalog.CATALOG` rather than hand-maintained, so
    it cannot drift from the font this project actually bakes: the
    weather-selection logic in `WfbWeather.mc` only ever produces a name
    (`chooseIcon`), and this is the one place, for every icon in the
    catalogue and not just weather ones, where a name becomes a character.

    Scoped to the names a dynamic icon could actually produce in this design
    -- every catalogue entry `icon_for:`'s underlying source table
    (`wfb.icons.GARMIN_WEATHER_CONDITION_ICON`) can select -- not the whole
    catalogue, so a design with one `icon_for:` element does not bake a
    lookup table for icons it never draws dynamically.
    """
    names = sorted(set(icons.GARMIN_WEATHER_CONDITION_ICON.values()))
    w = Writer()
    w.doc(header(face)).blank()
    w.lines("import Toybox.Lang;").blank()
    w.doc(
        "Catalogue name -> drawn glyph, for a dynamic (`icon_for:`) icon.\n"
        "\n"
        "Generated directly from wfb.icon_catalog.CATALOG -- see wfb/icons.py's\n"
        "module docstring for why this table, rather than WfbWeather.mc, is where\n"
        "a name becomes a character."
    )
    with w.block("module IconGlyphs"):
        with w.block("function glyph(name as String) as String"):
            with w.block("switch (name)"):
                for name in names:
                    codepoint = icons.CATALOG[name].codepoint
                    w.line(f'case "{name}": return "{codepoint}";')
                w.line(f'default: return "{icons.FALLBACK_CODEPOINT}";')
    return SourceFile("source/IconGlyphs.mc", w.render())


def hold_targets(face: Face) -> list:
    """Elements a hold does something with, in draw order.

    Both kinds: an `on_hold:` on any element, and every `carousel`, which is
    interactive by construction.  Empty means a passive face, and the whole
    delegate is then omitted.
    """
    return [e for e in face.walk()
            if e.on_hold is not None or isinstance(e, Carousel)]


def carousels(face: Face) -> list:
    """Every `carousel` element, in draw order."""
    return [e for e in face.walk() if isinstance(e, Carousel)]


def launches_a_glance(face: Face) -> bool:
    """Does anything in this design actually emit `Complications.exitTo`?

    Not the same question as :func:`hold_targets`: a carousel is interactive
    (it rotates) without necessarily opening anything, and it would be wrong to
    make such a face declare `ComplicationSubscriber` or raise its
    `minApiLevel` to 4.2.0 for a call it never makes.
    """
    for element in face.walk():
        if element.on_hold is not None:
            return True
        if isinstance(element, Carousel) and any(
                item.launch is not None for item in element.items):
            return True
    return False


def emit_delegate(resolved: ResolvedFace) -> SourceFile:
    """`source/<Face>Delegate.mc`: turn a touch and hold into a glance.

    **`onPress` only, on every device.**  `WatchFaceDelegate.onTap` exists on
    the fēnix 8 targets, but the SDK documents it "Only available in WatchFace
    config mode" -- it is how the *on-device editor* learns which complication
    slot the user picked (`samples/ConfigurableWatchFace`), and it never fires
    on a face that is merely being looked at.  Touch and hold is the whole
    input surface a live watch face gets; there is no swipe, and the physical
    keys belong to the system.  See `docs/research/07-carousel-interaction.md`
    §1, which corrects the earlier "tap where available, hold on fr955"
    reading of ADR 0006 §6.

    `Complications.exitTo` is the whole mechanism on the other side: a watch
    face cannot launch an arbitrary app, only the one that owns a
    complication type.

    A `carousel` uses the *same* one gesture for three things, told apart by
    where the finger landed within its own box -- left third, right third,
    middle.  That is the whole reason ADR 0006 §6's "hold-to-cycle and
    hold-to-launch conflict" is no longer a conflict: geometry separates them,
    so the compiler lays out zones rather than rejecting the combination.
    """
    face = resolved.face
    targets = hold_targets(face)
    w = Writer()
    w.doc(header(face)).blank()
    imports = ["import Toybox.Lang;", "import Toybox.WatchUi;"]
    if launches_a_glance(face):
        imports.insert(0, "import Toybox.Complications;")
    w.lines(*imports).blank()
    w.doc(
        f"Touch handling for {face.name}.\n"
        "\n"
        "Each region below is one element's own drawn box, resolved per device in\n"
        "the Layout module, so what the finger must hit is what the eye sees."
    )
    with w.block(f"class {face.entry}Delegate extends WatchUi.WatchFaceDelegate"):
        w.doc("The view, so a carousel's selection can be moved and read back.\n"
              "\n"
              "Held even by a face with no carousel: one delegate shape is easier to\n"
              "read than two, and an unused field costs nothing measurable.")
        w.line(f"private var _view as {face.entry}View;")
        w.blank()
        with w.block(f"function initialize(view as {face.entry}View)"):
            w.line("WatchFaceDelegate.initialize();")
            w.line("_view = view;")
        w.blank()
        w.doc("A touch and hold -- the only gesture a live watch face receives.\n"
              "\n"
              "There is deliberately no onTap here: it is documented \"Only available in\n"
              "WatchFace config mode\" and never fires during normal display, on any\n"
              "device.\n"
              "\n"
              "Returns true when the touch was consumed, so the system does not also\n"
              "act on it.")
        with w.block("function onPress(clickEvent as ClickEvent) as Boolean"):
            w.line("var where = clickEvent.getCoordinates();")
            w.line("var x = where[0];")
            w.line("var y = where[1];")
            for element in targets:
                prefix = _const_prefix(element.id)
                w.blank()
                condition = (
                    f"if (x >= Layout.{prefix}_HOLD_X && "
                    f"x < Layout.{prefix}_HOLD_X + Layout.{prefix}_HOLD_WIDTH\n"
                    f"        && y >= Layout.{prefix}_HOLD_Y && "
                    f"y < Layout.{prefix}_HOLD_Y + Layout.{prefix}_HOLD_HEIGHT)"
                )
                if isinstance(element, Carousel):
                    w.comment(f"carousel `{element.id}`: previous | open | next, by zone")
                    with w.block(condition):
                        _emit_carousel_zones(w, element, prefix)
                    continue
                launch = complications.LAUNCHABLE[element.on_hold]
                w.comment(f"`{element.id}` -> {element.on_hold}")
                with w.block(condition):
                    w.line(f"Complications.exitTo(new Complications.Id("
                           f"Complications.{launch.constant}));")
                    w.line("return true;")
            w.blank()
            w.line("return false;")
    return SourceFile(f"source/{face.entry}Delegate.mc", w.render())


def _emit_carousel_zones(w: Writer, element: Carousel, prefix: str) -> None:
    """The three zones inside one carousel's box.

    Every branch returns true, including the one that opens nothing: the hold
    landed on the carousel, so passing it back to the system would let a stray
    finger on the middle zone do something else entirely.
    """
    step = carousel_step_method(element.id)
    with w.block(f"if (x < Layout.{prefix}_PREV_EDGE)"):
        w.line(f"_view.{step}(-1);")
        w.line("return true;")
    with w.block(f"if (x >= Layout.{prefix}_NEXT_EDGE)"):
        w.line(f"_view.{step}(1);")
        w.line("return true;")
    w.blank()
    launchable = [(index, item) for index, item in enumerate(element.items)
                  if item.launch is not None]
    if launchable:
        w.comment("the middle: open whatever owns the selected item's reading")
        with w.block(f"switch (_view.{carousel_index_field(element.id)})"):
            for index, item in launchable:
                constant = complications.LAUNCHABLE[item.launch].constant
                w.line(f"// item {index}: {item.icon}")
                w.line(f"case {index}: Complications.exitTo("
                       f"new Complications.Id(Complications.{constant})); break;")
    else:
        w.comment("no item declares a `launch:`, so the middle zone opens nothing")
    w.line("return true;")


# --------------------------------------------------------------------------
# per-device layout constants


def emit_layout(resolved: ResolvedFace) -> SourceFile:
    face, device = resolved.face, resolved.device
    w = Writer()
    w.doc(
        header(
            face,
            f"Device:    {device.id} -- {device.width}x{device.height} {device.shape}, "
            f"{device.display_type}, family {device.device_family}",
        )
    ).blank()
    w.lines("import Toybox.Lang;").blank()
    w.doc(
        f"Layout resolved for {device.id}.\n"
        "\n"
        "Every value here came from a relative unit in the design -- percentages of\n"
        "the parent box, fractions of the screen's minor radius, angles measured\n"
        "clockwise from 12 o'clock.  Resolving them here means the device performs\n"
        "no layout arithmetic at all, which costs neither memory nor frame time."
    )
    with w.block("module Layout"):
        w.doc("The screen, for reference.")
        w.line(f"const SCREEN_WIDTH as Number = {device.width};")
        w.line(f"const SCREEN_HEIGHT as Number = {device.height};")
        for placed in resolved.items:
            constants = _layout_constants(placed) + _hold_constants(placed)
            if not constants:
                continue
            w.blank()
            w.doc(f"`{placed.id}` -- {_describe(placed)}")
            for name, value, note in constants:
                suffix = f"  // {note}" if note else ""
                w.line(f"const {name} as {_mc_type(value)} = {_mc_number(value)};{suffix}")
        clip = resolved.clip_for("low_power")
        if clip is not None:
            w.blank()
            w.doc(
                "The clip rectangle for low-power updates.\n"
                "\n"
                "setClip is charged by region *area* -- every pixel inside it counts as\n"
                "modified whenever any does -- so this is the tightest box covering all\n"
                f"low-power elements: {clip.area} px, "
                f"{100.0 * clip.area / (device.width * device.height):.0f}% of the screen."
            )
            w.line(f"const LOW_POWER_CLIP_X as Number = {clip.x};")
            w.line(f"const LOW_POWER_CLIP_Y as Number = {clip.y};")
            w.line(f"const LOW_POWER_CLIP_WIDTH as Number = {clip.width};")
            w.line(f"const LOW_POWER_CLIP_HEIGHT as Number = {clip.height};")
    return SourceFile(f"source-{device.id}/Layout.mc", w.render())


def _hold_constants(placed) -> list[tuple[str, float, str]]:
    """The hit rectangle for an `on_hold:` element.

    Deliberately the element's own resolved box, not an inflated one: the
    region a finger must hit is then exactly the thing the eye sees, which is
    predictable and reviewable in `wfb preview`.  Inflating to some minimum
    touch size would be inventing a number Garmin does not publish, and would
    silently overlap neighbouring targets on a dense face.  An author who
    wants a bigger target puts the element in a `group` and taps that.
    """
    # A carousel is interactive by construction -- its three zones are the
    # whole point of the element -- so it gets a hit region without asking,
    # where every other element opts in with `on_hold:`.
    if placed.element.on_hold is None and not isinstance(placed, PlacedCarousel):
        return []
    prefix = _const_prefix(placed.id)
    box = placed.box
    return [
        (f"{prefix}_HOLD_X", box.x, "hit region: the element's own drawn box"),
        (f"{prefix}_HOLD_Y", box.y, ""),
        (f"{prefix}_HOLD_WIDTH", box.width, ""),
        (f"{prefix}_HOLD_HEIGHT", box.height, ""),
    ]


def _layout_constants(placed) -> list[tuple[str, float, str]]:
    prefix = _const_prefix(placed.id)
    out: list[tuple[str, float, str]] = []
    if isinstance(placed, PlacedShape):
        element = placed.element
        if element.shape in ("circle", "line"):
            out.append((f"{prefix}_CX", placed.center[0], ""))
            out.append((f"{prefix}_CY", placed.center[1], ""))
        if element.shape == "circle":
            out.append((f"{prefix}_RADIUS", placed.radius, ""))
        elif element.shape == "line":
            out.append((f"{prefix}_END_X", placed.end[0], ""))
            out.append((f"{prefix}_END_Y", placed.end[1], ""))
            out.append((f"{prefix}_THICKNESS", placed.thickness, ""))
        else:
            out.append((f"{prefix}_X", placed.box.x, ""))
            out.append((f"{prefix}_Y", placed.box.y, ""))
            out.append((f"{prefix}_WIDTH", placed.box.width, ""))
            out.append((f"{prefix}_HEIGHT", placed.box.height, ""))
            if element.shape == "rounded_rectangle":
                out.append((f"{prefix}_CORNER", placed.corner_radius, ""))
    elif isinstance(placed, PlacedText):
        out.append((f"{prefix}_X", placed.anchor_point[0], ""))
        out.append((f"{prefix}_Y", placed.anchor_point[1], ""))
        note = f'widest rendering "{placed.widest}" is {placed.measured_width} px'
        if placed.width_is_estimated:
            note += " (estimated)"
        out.append((f"{prefix}_WIDTH", placed.measured_width, note))
    elif isinstance(placed, PlacedProgress):
        out.append((f"{prefix}_CX", placed.center[0], ""))
        out.append((f"{prefix}_CY", placed.center[1], ""))
        if placed.element.style == "arc":
            out.append((f"{prefix}_RADIUS", placed.radius, ""))
            out.append((f"{prefix}_THICKNESS", placed.thickness, "pen width; there is no filled-arc primitive"))
            out.append((f"{prefix}_START", float(placed.garmin_start),
                        f"{placed.start_angle:g}deg clockwise from 12 o'clock, in Garmin's convention"))
            out.append((f"{prefix}_SWEEP", float(placed.sweep), "clockwise-positive degrees"))
        else:
            out.append((f"{prefix}_X", placed.box.x, ""))
            out.append((f"{prefix}_Y", placed.box.y, ""))
            out.append((f"{prefix}_WIDTH", placed.box.width, ""))
            out.append((f"{prefix}_HEIGHT", placed.box.height, ""))
    elif isinstance(placed, PlacedIcon):
        out.append((f"{prefix}_CX", placed.center[0], ""))
        out.append((f"{prefix}_CY", placed.center[1], ""))
    elif isinstance(placed, PlacedCarousel):
        out.append((f"{prefix}_CX", placed.row_center[0], "centre of the icon row"))
        out.append((f"{prefix}_CY", placed.row_center[1], ""))
        out.append((f"{prefix}_PITCH", placed.pitch, "centre-to-centre slot spacing"))
        out.append((f"{prefix}_VALUE_X", placed.value_anchor[0],
                    "where the selected item's reading is drawn"))
        out.append((f"{prefix}_VALUE_Y", placed.value_anchor[1], ""))
        out.append((f"{prefix}_PREV_EDGE", placed.prev_edge,
                    "a hold left of this is 'previous'"))
        out.append((f"{prefix}_NEXT_EDGE", placed.next_edge,
                    "a hold at or right of this is 'next'; between them opens the glance"))
    return out


# --------------------------------------------------------------------------
# the view


def emit_view(resolved: ResolvedFace) -> SourceFile:
    face, device = resolved.face, resolved.device
    plan = ReadPlan(resolved)
    if resolved.in_mode("low_power") and device.supports_partial_update:
        plan.modules.add("Toybox.System")  # onPowerBudgetExceeded reports via println

    w = Writer()
    w.doc(header(face, f"Device:    {device.id}")).blank()
    for module in sorted(set(_BASE_IMPORTS) | plan.modules):
        w.line(f"import {module};")
    w.blank()

    w.doc(
        f"{face.name}.\n"
        "\n"
        "One private method per design element, in draw order.  Each is named after\n"
        "the element's `id:` in the source YAML, so a change on screen leads back to\n"
        "a line in the design file."
    )
    always_on = bool(resolved.in_mode("always_on"))
    rings = [p for p in resolved.items if isinstance(p, PlacedCarousel)]
    animated = [p for p in rings if p.element.animate > 0]
    # A carousel needs the sleep flag whether or not the design uses
    # `always_on`: WatchUi.animate crashes the app in low power mode, so the
    # slide has to know (research 07 3).
    sleep_flag = always_on or bool(animated)
    with w.block(f"class {face.entry}View extends WatchUi.WatchFace"):
        _emit_fields(w, resolved)
        _emit_cache_fields(w, plan)
        _emit_carousel_fields(w, rings)
        if sleep_flag:
            w.doc(_sleep_flag_doc(always_on, bool(animated)))
            w.line("private var _sleeping as Boolean = false;")
            w.blank()
        _emit_initialize(w, face, rings)
        _emit_on_layout(w, resolved, plan)
        _emit_on_update(w, resolved, plan, always_on)
        if resolved.in_mode("low_power") and device.supports_partial_update:
            _emit_on_partial_update(w, resolved, plan)
        _emit_sleep_hooks(w, resolved, always_on, sleep_flag)
        if plan.event_readers():
            _emit_complication_callback(w, plan)
        for placed in rings:
            _emit_carousel_step(w, placed, sleep_flag)
        for placed in resolved.items:
            if placed.kind == "group":
                continue
            w.blank()
            _emit_element_method(w, resolved, placed, plan)
    return SourceFile(f"source/{face.entry}View.mc", w.render())


def _sleep_flag_doc(always_on: bool, animated: bool) -> str:
    reasons = []
    if always_on:
        reasons.append(
            "onUpdate reads it to choose which element set to draw: the 'always_on'\n"
            "elements while asleep, the 'active' ones while awake."
        )
    if animated:
        reasons.append(
            "A carousel's slide reads it because WatchUi.animate is documented to\n"
            "*crash the app* if called from a watch face in low power mode, so a\n"
            "rotation while asleep is instant instead of animated."
        )
    return ("Whether the watch is currently asleep.  Set by onEnterSleep/onExitSleep "
            "below.\n\n" + "\n\n".join(reasons))


def _emit_carousel_fields(w: Writer, rings: list) -> None:
    """One selection field per carousel, and one slide offset per animated one."""
    if not rings:
        return
    for placed in rings:
        element = placed.element
        w.doc(f"`{element.id}`: which of its {len(element.items)} items is centred."
              + ("  Persisted in Application.Storage, so the wearer's choice survives "
                 "a restart." if element.persist else "  Not persisted: the design "
                 "declares `persist: false`, so it starts at item 0 every launch."))
        w.line(f"public var {carousel_index_field(element.id)} as Number = 0;")
        if element.animate > 0:
            w.doc(f"`{element.id}`: the slide offset, in pixels, while it rotates.\n"
                  "\n"
                  "Public because WatchUi.animate takes a Symbol and looks the property\n"
                  "up indirectly -- a private member is not found that way, and monkeyc\n"
                  "warns about exactly that.")
            w.line(f"public var {carousel_slide_field(element.id)} as Number = 0;")
    w.blank()


def _emit_carousel_step(w: Writer, placed, sleep_flag: bool) -> None:
    """`step<Id>(direction)` -- the one thing a hold on an outer zone does."""
    element = placed.element
    count = len(element.items)
    index = carousel_index_field(element.id)
    w.blank()
    w.doc(f"Move `{element.id}` one slot.  Called from the delegate's zone test.\n"
          "\n"
          "-1 is the item to the left, +1 the item to the right; both wrap.")
    with w.block(f"public function {carousel_step_method(element.id)}"
                 "(direction as Number) as Void"):
        w.line(f"{index} = WfbCarousel.step({index}, direction, {count});")
        if element.persist:
            w.line(f'WfbCarousel.remember("{element.id}", {index});')
        if element.animate > 0:
            slide = carousel_slide_field(element.id)
            prefix = _const_prefix(element.id)
            w.blank()
            w.comment("cancel first: a second press mid-slide must not stack animations")
            w.line("WatchUi.cancelAllAnimations();")
            w.line(f"{slide} = 0;")
            with w.block("if (!_sleeping)" if sleep_flag else "if (true)"):
                w.comment("the new item starts off-centre and slides into place; asleep,")
                w.comment("animate() would crash the app, so the change is instant instead")
                w.line(f"{slide} = direction * Layout.{prefix}_PITCH;")
                w.line(f"WatchUi.animate(self, :{slide}, WatchUi.ANIM_TYPE_EASE_OUT,")
                w.line(f"                direction * Layout.{prefix}_PITCH, 0, "
                       f"{element.animate}f,")
                w.line(f"                method(:{carousel_slide_done_method(element.id)}));")
        w.line("WatchUi.requestUpdate();")
    if element.animate > 0:
        w.blank()
        w.doc(f"`{element.id}` finished sliding.  One more frame draws it at rest.")
        with w.block(f"public function {carousel_slide_done_method(element.id)}() as Void"):
            w.line(f"{carousel_slide_field(element.id)} = 0;")
            w.line("WatchUi.requestUpdate();")


def _emit_fields(w: Writer, resolved: ResolvedFace) -> None:
    loaded = _loaded_fonts(resolved)
    if not loaded:
        return
    w.doc("Bitmap fonts -- custom text and icon glyphs alike -- loaded once in\n"
          "onLayout rather than per frame.")
    for name in loaded:
        w.line(f"private var _{_field(name)} as FontResource?;")
    w.blank()


def _emit_cache_fields(w: Writer, plan: "ReadPlan") -> None:
    slow = plan.slow_readers()
    if slow:
        w.doc("`slow`-tier reads, cached here instead of re-read every frame --\n"
              "see WfbCache.mc and ReadPlan.emit_reads.")
        for name in slow:
            reader = READERS[name]
            w.line(f"private var _{reader.name}Cache as {reader.monkeyc_type};")
            w.line(f"private var _{reader.name}CacheTime as Number?;")
        w.blank()

    event = plan.event_readers()
    if event:
        w.doc("`event`-tier reads: complications, filled in by\n"
              "onComplicationChanged rather than read fresh every frame -- see\n"
              "_emit_on_layout's subscriptions below.")
        for name in event:
            reader = READERS[name]
            w.line(f"private var {reader.call} as {reader.monkeyc_type};")
        w.blank()


def _emit_initialize(w: Writer, face: Face, rings: list) -> None:
    with w.block("function initialize()"):
        w.line("WatchFace.initialize();")
        restored = [p for p in rings if p.element.persist]
        if restored:
            w.blank()
            w.comment("carousel selections, as the wearer last left them")
            for placed in restored:
                element = placed.element
                w.line(f"{carousel_index_field(element.id)} = "
                       f'WfbCarousel.restore("{element.id}", {len(element.items)});')
    w.blank()


def _emit_on_layout(w: Writer, resolved: ResolvedFace, plan: "ReadPlan") -> None:
    loaded = _loaded_fonts(resolved)
    event = plan.event_readers()
    w.doc("Load resources once.  Loading is expensive and must not happen per frame.")
    with w.block("function onLayout(dc as Dc) as Void"):
        if not loaded and not event:
            w.line("// No resources to load: this face draws entirely from system fonts.")
        for name in loaded:
            resource = font_resource_id(name)
            w.line(
                f"_{_field(name)} = WatchUi.loadResource(Rez.Fonts.{resource}) as FontResource;"
            )
        if event:
            if loaded:
                w.blank()
            w.comment(
                "complications: one shared callback (below), one subscription per "
                "type -- WfbComplications.subscribe absorbs a device not supporting "
                "a given type, so an unsupported one just never updates its cache"
            )
            w.line("Complications.registerComplicationChangeCallback(method(:onComplicationChanged));")
            for name in event:
                reader = READERS[name]
                w.line(f"WfbComplications.subscribe(new Complications.Id(Complications.{reader.complication_type}));")
    w.blank()


def _emit_on_update(w: Writer, resolved: ResolvedFace, plan: "ReadPlan", always_on: bool) -> None:
    w.doc(
        "Draw the full face.\n"
        "\n"
        "Called once a minute in low-power mode and once a second while the watch is\n"
        "awake." + (
            "  While asleep, draws the 'always_on' set instead of 'active' -- see\n"
            "_sleeping, set by onEnterSleep/onExitSleep below."
            if always_on else ""
        )
    )
    with w.block("function onUpdate(dc as Dc) as Void"):
        w.line("dc.clearClip();")
        if always_on:
            with w.block("if (_sleeping)"):
                plan.emit_reads(w, "always_on")
                w.blank()
                for placed in resolved.items:
                    if placed.kind == "group" or "always_on" not in placed.element.modes:
                        continue
                    w.line(f"{_method(placed.id)}(dc{plan.arguments(placed)});")
            with w.block("else"):
                plan.emit_reads(w, "active")
                w.blank()
                for placed in resolved.items:
                    if placed.kind == "group" or "active" not in placed.element.modes:
                        continue
                    w.line(f"{_method(placed.id)}(dc{plan.arguments(placed)});")
        else:
            plan.emit_reads(w, "active")
            w.blank()
            for placed in resolved.items:
                if placed.kind == "group" or "active" not in placed.element.modes:
                    continue
                w.line(f"{_method(placed.id)}(dc{plan.arguments(placed)});")
    w.blank()


def _emit_on_partial_update(w: Writer, resolved: ResolvedFace, plan: "ReadPlan") -> None:
    clip = resolved.clip_for("low_power")
    fraction = 100.0 * clip.area / (resolved.device.width * resolved.device.height) if clip else 0
    w.doc(
        "Redraw only the low-power elements, once a second, while asleep.\n"
        "\n"
        "The clip is the tightest box around them because setClip is charged by\n"
        f"region area: {fraction:.0f}% of the screen here.  Overrunning the power\n"
        "budget calls onPowerBudgetExceeded and disables partial updates for the\n"
        "rest of the app's lifecycle, so only frame-tier sources are read here --\n"
        "the compiler rejects anything slower."
    )
    with w.block("function onPartialUpdate(dc as Dc) as Void"):
        w.line(
            "dc.setClip(Layout.LOW_POWER_CLIP_X, Layout.LOW_POWER_CLIP_Y,"
        )
        w.line(
            "           Layout.LOW_POWER_CLIP_WIDTH, Layout.LOW_POWER_CLIP_HEIGHT);"
        )
        plan.emit_reads(w, "low_power")
        w.blank()
        for placed in resolved.items:
            if placed.kind == "group" or "low_power" not in placed.element.modes:
                continue
            w.line(f"{_method(placed.id)}(dc{plan.arguments(placed)});")
        w.line("dc.clearClip();")
    w.blank()


def _emit_sleep_hooks(w: Writer, resolved: ResolvedFace, always_on: bool,
                      sleep_flag: bool = False) -> None:
    sleep_flag = sleep_flag or always_on
    w.doc("Awake: full-power updates resume.")
    with w.block("function onExitSleep() as Void"):
        if sleep_flag:
            w.line("_sleeping = false;")
        w.line("WatchUi.requestUpdate();")
    w.blank()
    w.doc(
        "Asleep: the next onUpdate draws the 'always_on' layout."
        if always_on else
        "Asleep: the next onUpdate draws the low-power layout."
    )
    with w.block("function onEnterSleep() as Void"):
        if sleep_flag:
            w.line("_sleeping = true;")
        w.line("WatchUi.requestUpdate();")
    w.blank()
    if resolved.in_mode("low_power") and resolved.device.supports_partial_update:
        w.doc(
            "The power budget was exceeded and partial updates are now off for the\n"
            "rest of this app's lifecycle.  Nothing can re-enable them; the face\n"
            "simply falls back to once-a-minute updates."
        )
        with w.block("function onPowerBudgetExceeded(powerInfo as WatchUi.WatchFacePowerInfo) as Void"):
            w.line('System.println("wfb: partial-update power budget exceeded: "')
            w.line('               + powerInfo.executionTimeAverage.format("%.2f") + " ms average");')
        w.blank()


def _emit_complication_callback(w: Writer, plan: "ReadPlan") -> None:
    """`onComplicationChanged`: the one callback every EVENT-tier reader shares.

    Complications delivers only the changed `Id`, not its value
    (ComplicationChangedCallback as Method(id as Complications.Id) as Void,
    Toybox/Complications.html) -- `getComplication(id)` fetches it, and the
    switch dispatches on `id.getType()` to the one cached field that
    complication backs.  `getComplication` throws `ComplicationNotFoundException`
    when a complication "is not found", which the callback's own doc says
    includes the case where a previously-working one "becomes unavailable" --
    `WfbComplications.valueOf` absorbs that (Bug 7), the same way `subscribe`
    already absorbs a subscription a device declines, so an uncaught throw
    here cannot take the whole watch face down.
    """
    w.doc(
        "A subscribed complication changed.\n"
        "\n"
        "Complications.registerComplicationChangeCallback delivers only the id --\n"
        "WfbComplications.valueOf looks the value back up (absorbing a "
        "'not found or became unavailable' error the same way a declined "
        "subscription already is), and the switch below routes it to the "
        "cached field the changed type backs."
    )
    with w.block("function onComplicationChanged(id as Complications.Id) as Void"):
        w.line("var complication = WfbComplications.valueOf(id);")
        with w.block("if (complication == null)"):
            w.line("return;  // not found, or no longer available")
        w.blank()
        with w.block("switch (id.getType())"):
            for name in plan.event_readers():
                reader = READERS[name]
                w.line(
                    f"case Complications.{reader.complication_type}: "
                    f"{reader.call} = complication.value as {reader.monkeyc_type}; break;"
                )
        w.line("WatchUi.requestUpdate();")
    w.blank()


# --------------------------------------------------------------------------
# one method per element


def _emit_element_method(w: Writer, resolved: ResolvedFace, placed, plan: "ReadPlan") -> None:
    element = placed.element
    w.doc(_method_doc(placed))
    signature = f"private function {_method(placed.id)}(dc as Dc{plan.parameters(placed)}) as Void"
    # 'placeholder'/'fallback' are policies for the *value* -- a substitute
    # text or fill fraction takes over instead of the element simply not
    # drawing.  They say nothing about a nullable colour, track colour or
    # max: there is no placeholder for a colour, so those always get a real
    # guard regardless of which policy the value chose (Bug 5).
    substitutes_value = (
        isinstance(placed, (PlacedText, PlacedProgress))
        and getattr(element, "when_absent", None) in ("placeholder", "fallback")
    )
    with w.block(signature):
        declarations = plan.declarations(placed)
        if declarations:
            w.comment("the values this element is bound to")
            for name, read in declarations:
                w.line(f"var {name} = {read};")
            w.blank()
        if isinstance(placed, PlacedCarousel):
            # Deliberately no element-level guard.  Every other element hides
            # as a whole when a binding is absent, but a carousel's bindings
            # belong to *items*: one absent reading blanks one slot's text and
            # leaves the row, its icons and its hold zones exactly where they
            # were.  Each item's own policy is applied inside the switch below.
            _emit_carousel(w, placed, plan)
            return
        value_guards = plan.value_guards(placed)
        if substitutes_value:
            other_guards = plan.other_guards(placed)
            if other_guards:
                _emit_guard(w, placed, other_guards,
                           note="hide -- a nullable colour/track_color/max always hides "
                                "the element, regardless of the value's own when_absent")
        else:
            other_guards = plan.guards(placed)
            if other_guards:
                _emit_guard(w, placed, other_guards)
        if isinstance(placed, PlacedShape):
            _emit_shape(w, placed)
        elif isinstance(placed, PlacedText):
            _emit_text(w, resolved, placed, value_guards)
        elif isinstance(placed, PlacedProgress):
            _emit_progress(w, placed, value_guards)
        elif isinstance(placed, PlacedIcon):
            _emit_icon(w, placed)
        elif isinstance(placed, PlacedCarousel):
            _emit_carousel(w, placed, plan)


def _method_doc(placed) -> str:
    element = placed.element
    lines = [f"`{element.id}` -- {_describe(placed)}."]
    bindings = [e.text for e in element.expressions() if e.sources]
    if bindings:
        lines.append("")
        lines.append("Bound to " + _and_list(f"`{text}`" for text in bindings) + ".")
    policy = getattr(element, "when_absent", None)
    if policy:
        lines.append(f"When the value is absent: {policy}.")
    modes = ", ".join(element.modes)
    lines.append(f"Drawn in: {modes}.")
    return "\n".join(lines)


def _emit_guard(w: Writer, placed, guards: list[str], note: str | None = None) -> None:
    """Emit the null check, and say which `when_absent:` produced it.

    ``note`` overrides the default "when_absent: <policy>" comment for the
    case (Bug 5) where the guard covers only bindings the value's own policy
    does not govern -- a nullable colour still just hides the element even
    when the value itself falls back to a placeholder.
    """
    element = placed.element
    condition = " || ".join(f"{name} == null" for name in guards)
    w.comment(note if note is not None else f"when_absent: {getattr(element, 'when_absent', None) or 'hide'}")
    with w.block(f"if ({condition})"):
        w.line("return;")
    w.blank()


def _emit_shape(w: Writer, placed: PlacedShape) -> None:
    element = placed.element
    prefix = _const_prefix(placed.id)
    w.line(f"dc.setColor({_color(element.color)}, Graphics.COLOR_TRANSPARENT);")
    if element.shape == "rectangle":
        w.line(f"dc.fillRectangle(Layout.{prefix}_X, Layout.{prefix}_Y,")
        w.line(f"                 Layout.{prefix}_WIDTH, Layout.{prefix}_HEIGHT);")
    elif element.shape == "rounded_rectangle":
        w.line(f"dc.fillRoundedRectangle(Layout.{prefix}_X, Layout.{prefix}_Y,")
        w.line(f"                        Layout.{prefix}_WIDTH, Layout.{prefix}_HEIGHT,")
        w.line(f"                        Layout.{prefix}_CORNER);")
    elif element.shape == "circle":
        if element.filled:
            w.line(f"dc.fillCircle(Layout.{prefix}_CX, Layout.{prefix}_CY, Layout.{prefix}_RADIUS);")
        else:
            w.line(f"dc.setPenWidth({placed.thickness});")
            w.line(f"dc.drawCircle(Layout.{prefix}_CX, Layout.{prefix}_CY, Layout.{prefix}_RADIUS);")
            w.line("dc.setPenWidth(1);")
    elif element.shape == "line":
        w.line(f"dc.setPenWidth(Layout.{prefix}_THICKNESS);")
        w.line(
            f"dc.drawLine(Layout.{prefix}_CX, Layout.{prefix}_CY, "
            f"Layout.{prefix}_END_X, Layout.{prefix}_END_Y);"
        )
        w.line("dc.setPenWidth(1);")


def _emit_text(w: Writer, resolved: ResolvedFace, placed: PlacedText, guards: list[str]) -> None:
    element = placed.element
    if element.literal is not None:
        _emit_text_draw(w, placed, f'"{element.literal}"')
        return

    value_code = formatting.emit(
        element.format or "{}",
        element.value.code,
        element.value.value.type,
    )
    if element.when_absent == "placeholder" and guards:
        # Build the string once rather than duplicating the draw call in both
        # branches: the placeholder is a different *value*, not a different draw.
        w.comment(f"when_absent: placeholder")
        available = " && ".join(f"{name} != null" for name in guards)
        w.line(f'var text = "{element.placeholder}";')
        with w.block(f"if ({available})"):
            w.line(f"text = {value_code};")
        w.blank()
        _emit_text_draw(w, placed, "text")
        return
    if element.when_absent == "fallback" and guards:
        # Same shape as placeholder above, except the substitute is itself a
        # compiled expression rather than a literal string, so it is run
        # through the same format spec the real value uses.
        fallback_code = formatting.emit(
            element.format or "{}",
            element.fallback.code,
            element.fallback.value.type,
        )
        w.comment("when_absent: fallback")
        available = " && ".join(f"{name} != null" for name in guards)
        w.line(f"var text = {fallback_code};")
        with w.block(f"if ({available})"):
            w.line(f"text = {value_code};")
        w.blank()
        _emit_text_draw(w, placed, "text")
        return
    _emit_text_draw(w, placed, value_code)


def _emit_text_draw(w: Writer, placed: PlacedText, value_code: str) -> None:
    element = placed.element
    prefix = _const_prefix(placed.id)
    justify = " | ".join(f"Graphics.{flag}" for flag in placed.justify)
    if placed.font_is_custom:
        w.line(f"var font = _{_field(placed.font_reference)};")
        with w.block("if (font == null)"):
            w.line("return;  // the font resource failed to load")
        w.blank()
        font_expr = "font"
    else:
        font_expr = f"Graphics.{placed.font_reference}"
    w.line(f"dc.setColor({_color(element.color)}, Graphics.COLOR_TRANSPARENT);")
    w.line(f"dc.drawText(Layout.{prefix}_X, Layout.{prefix}_Y, {font_expr},")
    w.line(f"            {value_code},")
    w.line(f"            {justify});")


def _emit_progress(w: Writer, placed: PlacedProgress, guards: list[str]) -> None:
    element = placed.element
    prefix = _const_prefix(placed.id)
    fraction_expr = _fraction(element)
    if element.when_absent == "fallback" and guards:
        # The fill fraction falls back, not the raw value/max -- 'fallback:'
        # supplies a number in the same 0.0-1.0 range _fraction() computes, so
        # it slots into exactly the same drawProgress/fillRectangle call the
        # real reading would have used.  (This is why a `progress` fallback
        # means something different from a `text` one, which supplies the
        # *value* and is then formatted; for progress either half of the pair
        # can be the absent reading, so the outcome is the only well-defined
        # thing to substitute.  wfb/ir.py checks it is in range and
        # wfb/preview.py renders the same substitution.)
        w.comment("when_absent: fallback")
        available = " && ".join(f"{name} != null" for name in guards)
        w.line(f"var fraction = {_fallback_fraction(element)};")
        with w.block(f"if ({available})"):
            w.line(f"fraction = {fraction_expr};")
        w.blank()
        fraction_expr = "fraction"
    if element.style == "arc":
        if element.track_color is not None:
            w.comment("the unfilled track")
            w.line(f"dc.setColor({_color(element.track_color)}, Graphics.COLOR_TRANSPARENT);")
            w.line(
                f"WfbArc.drawSpan(dc, Layout.{prefix}_CX, Layout.{prefix}_CY, "
                f"Layout.{prefix}_RADIUS,"
            )
            w.line(
                f"                Layout.{prefix}_THICKNESS, Layout.{prefix}_START, "
                f"Layout.{prefix}_SWEEP);"
            )
            w.blank()
        w.comment("the filled portion")
        w.line(f"dc.setColor({_color(element.color)}, Graphics.COLOR_TRANSPARENT);")
        w.line(
            f"WfbArc.drawProgress(dc, Layout.{prefix}_CX, Layout.{prefix}_CY, "
            f"Layout.{prefix}_RADIUS,"
        )
        w.line(
            f"                    Layout.{prefix}_THICKNESS, Layout.{prefix}_START, "
            f"Layout.{prefix}_SWEEP,"
        )
        w.line(f"                    {fraction_expr});")
        return

    if element.track_color is not None:
        w.line(f"dc.setColor({_color(element.track_color)}, Graphics.COLOR_TRANSPARENT);")
        w.line(
            f"dc.fillRectangle(Layout.{prefix}_X, Layout.{prefix}_Y, "
            f"Layout.{prefix}_WIDTH, Layout.{prefix}_HEIGHT);"
        )
        w.blank()
    w.line(f"var filled = (Layout.{prefix}_WIDTH * {fraction_expr}).toNumber();")
    w.line(f"dc.setColor({_color(element.color)}, Graphics.COLOR_TRANSPARENT);")
    w.line(
        f"dc.fillRectangle(Layout.{prefix}_X, Layout.{prefix}_Y, filled, Layout.{prefix}_HEIGHT);"
    )


def _emit_icon(w: Writer, placed: PlacedIcon) -> None:
    """A `drawText` call against the icon's baked glyph -- see `wfb.icons`:
    an icon is a one-character string drawn with a bitmap font, the same
    mechanism any other bound text uses, not a hand-drawn shape.

    A *dynamic* icon (`icon_for:`) draws the same way, except the glyph
    string is resolved in two steps at runtime instead of being a literal
    baked in at build time: `WfbWeather.chooseIcon` picks a catalogue *name*
    from the bound value, and `IconGlyphs.glyph` (generated per project,
    directly from `wfb.icon_catalog.CATALOG`) turns that name into the actual
    character -- the same table any static icon's build-time lookup uses, not
    a second, weather-only one. The font still has every glyph that call
    could return, baked in ahead of time (`wfb.emit.resources.icon_font_specs`).
    """
    element = placed.element
    prefix = _const_prefix(placed.id)
    w.line(f"var font = _{_field(placed.font_key)};")
    with w.block("if (font == null)"):
        w.line("return;  // the icon font resource failed to load")
    w.blank()
    if element.is_dynamic:
        from ..ir import local_name

        condition_local = local_name(element.value_for.sources[0])
        w.comment(f"{element.value_for.text!r} -> a name (WfbWeather) -> a glyph (IconGlyphs)")
        glyph_expr = f"IconGlyphs.glyph(WfbWeather.chooseIcon({condition_local}))"
    else:
        w.comment(f"{element.icon!r}")
        glyph_expr = f'"{element.codepoint}"'
    w.line(f"dc.setColor({_color(element.color)}, Graphics.COLOR_TRANSPARENT);")
    w.line(f"dc.drawText(Layout.{prefix}_CX, Layout.{prefix}_CY, font,")
    w.line(f"            {glyph_expr},")
    w.line("            Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER);")


def _emit_carousel(w: Writer, placed: PlacedCarousel, plan: "ReadPlan") -> None:
    """The icon row, then the selected item's reading.

    The row is a loop over *slots* with a switch on the item that lands in
    each, rather than a loop over items: which item sits in which slot changes
    every time the wearer moves the carousel, and the slide offset applies to
    the slot, not the item.
    """
    element = placed.element
    prefix = _const_prefix(placed.id)
    index = carousel_index_field(element.id)
    count = len(element.items)
    slide = (carousel_slide_field(element.id) if element.animate > 0 else None)
    active = _color(element.color)
    inactive = _color(element.inactive_color) if element.inactive_color is not None else active

    if element.slots > 1:
        reach = element.slots // 2
        w.comment(f"the icon row: {element.slots} slots, the centred one selected")
        with w.block(f"for (var slot = -{reach}; slot <= {reach}; slot += 1)"):
            w.line(f"var item = ({index} + slot + {count}) % {count};")
            offset = f" - {slide}" if slide else ""
            w.line(f"var x = Layout.{prefix}_CX + slot * Layout.{prefix}_PITCH{offset};")
            if inactive != active:
                w.line(f"dc.setColor(slot == 0 ? {active} : {inactive}, "
                       "Graphics.COLOR_TRANSPARENT);")
            else:
                w.line(f"dc.setColor({active}, Graphics.COLOR_TRANSPARENT);")
            _emit_carousel_glyph_switch(w, placed, "item", "x")
    else:
        w.comment("one slot: only the selected item is drawn")
        w.line(f"dc.setColor({active}, Graphics.COLOR_TRANSPARENT);")
        _emit_carousel_glyph_switch(w, placed, index, f"Layout.{prefix}_CX")
    w.blank()

    w.comment("the selected item's reading")
    w.line('var text = "";')
    with w.block(f"switch ({index})"):
        for item_placed, item in zip(placed.items, element.items):
            w.line(f"// item {item_placed.index}: {item.icon}"
                   + (f" -- {item.value.text}" if item.value is not None else ""))
            with w.block(f"case {item_placed.index}:"):
                _emit_carousel_item_text(w, item, plan)
                w.line("break;")
    w.blank()
    if placed.value_font_is_custom:
        w.line(f"var valueFont = _{_field(placed.value_font_reference)};")
        with w.block("if (valueFont == null)"):
            w.line("return;  // the font resource failed to load")
        w.blank()
        font_expr = "valueFont"
    else:
        font_expr = f"Graphics.{placed.value_font_reference}"
    value_color = (_color(element.value_color) if element.value_color is not None else active)
    w.line(f"dc.setColor({value_color}, Graphics.COLOR_TRANSPARENT);")
    w.line(f"dc.drawText(Layout.{prefix}_VALUE_X, Layout.{prefix}_VALUE_Y, {font_expr}, text,")
    w.line("            Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER);")


def _emit_carousel_glyph_switch(w: Writer, placed: PlacedCarousel,
                                selector: str, x_expr: str) -> None:
    """Draw whichever item's glyph belongs at `x_expr`.

    Each item gets its own font resource because `wfb.icons.bake_size` picks a
    nominal size per glyph -- the vendored font's aggregated icon sets pad
    their glyphs differently inside the em-square, so one nominal size does not
    give them all the same ink height.
    """
    prefix = _const_prefix(placed.id)
    with w.block(f"switch ({selector})"):
        for item_placed, item in zip(placed.items, placed.element.items):
            w.line(f"// item {item_placed.index}: {item.icon}")
            with w.block(f"case {item_placed.index}:"):
                field = f"_{_field(item_placed.font_key)}"
                w.line(f"var glyphFont = {field};")
                with w.block("if (glyphFont != null)"):
                    w.line(f"dc.drawText({x_expr}, Layout.{prefix}_CY, glyphFont,")
                    w.line(f'            "{item_placed.codepoint}",')
                    w.line("            Graphics.TEXT_JUSTIFY_CENTER "
                           "| Graphics.TEXT_JUSTIFY_VCENTER);")
                w.line("break;")


def _emit_carousel_item_text(w: Writer, item, plan: "ReadPlan") -> None:
    """One item's reading, with that item's own `when_absent:` policy.

    Scoped to the item on purpose: this is the whole reason a carousel skips
    the element-level guard every other element gets.
    """
    from ..ir import local_name

    if item.value is None:
        w.line('text = "";')
        return
    value_code = formatting.emit(item.format or "{}", item.value.code,
                                item.value.value.type)
    guards = [local_name(path) for path in item.value.sources
              if catalog.CATALOG[path].guard_needed]
    if not guards:
        w.line(f"text = {value_code};")
        return
    available = " && ".join(f"{name} != null" for name in guards)
    if item.when_absent == "placeholder":
        w.comment("when_absent: placeholder")
        w.line(f'text = "{item.placeholder}";')
    elif item.when_absent == "fallback":
        w.comment("when_absent: fallback")
        w.line("text = " + formatting.emit(item.format or "{}", item.fallback.code,
                                           item.fallback.value.type) + ";")
    else:
        w.comment("when_absent: hide -- this slot's reading is blank, the icon stays")
        w.line('text = "";')
    with w.block(f"if ({available})"):
        w.line(f"text = {value_code};")


def _fallback_fraction(element: Progress) -> str:
    """The `progress` fallback, as a Float in 0.0-1.0.

    Two things have to be true of it, and neither is automatic.  It must be a
    **Float**: `fraction` is reassigned from `_fraction()` (a Float) in the
    branch below, and a `var` first bound to a Number makes the whole thing a
    `PolyType<Float or Number>` that `WfbArc.drawProgress`'s `Float` parameter
    rejects under `-l 3`.  And it must be **in range**: the real path is
    clamped by `WfbMath.percent`, so an unclamped fallback is the one way a
    bar could be drawn wider than its own box.  A constant is checked at build
    time (wfb/ir.py) and emitted bare; anything else is clamped on device.
    """
    fallback = element.fallback
    if fallback.is_constant:
        return f"{float(fallback.constant)}f"
    return f"WfbMath.clamp({fallback.code}, 0.0, 1.0).toFloat()"


def _fraction(element: Progress) -> str:
    return f"WfbMath.percent({element.value.code}, {element.maximum.code}) / 100.0"


# --------------------------------------------------------------------------
# the read plan: which API calls happen, and where


class ReadPlan:
    """Decides which reader locals each element needs, and hoists the reads.

    Sources are grouped by reader so that ``ActivityMonitor.getInfo()`` is called
    once per frame no matter how many fields read off it, and every nullable
    field becomes a named local that the element's guard narrows.
    """

    def __init__(self, resolved: ResolvedFace) -> None:
        self.resolved = resolved
        self.modules: set[str] = set()
        self.barrel: set[str] = set(resolved.face.barrel_functions())
        #: Every source an element touches, for reader hoisting.
        self._per_element: dict[str, list[str]] = {}
        #: The subset referenced by compiled expressions, which read through a
        #: named local.  Format specs read their reader directly instead.
        self._bound: dict[str, list[str]] = {}
        #: The subset of `_bound` reached through the element's *value*
        #: expression(s) specifically -- `Text.value`, or `Progress.value`
        #: and `Progress.maximum` together, since both feed one fraction.
        #: This is what a `when_absent: placeholder`/`fallback` policy
        #: actually governs (Bug 5).
        self._value_bound: dict[str, list[str]] = {}
        #: The subset reached through every *other* expression (colour, track
        #: colour, max on its own) -- collected independently of
        #: `_value_bound`, not by subtracting it, because a source can be
        #: dereferenced at *both* sites (`value: heart_rate.current` and
        #: `color: "heart_rate.current > 100 ? ..."`) and each site needs its
        #: own protection: the value's dereference is what `when_absent`
        #: covers, but the colour's is a second, independent dereference of
        #: the same possibly-null local, which a placeholder for the *text*
        #: does nothing to protect.
        self._other_bound: dict[str, list[str]] = {}
        self._readers_for_mode: dict[str, list[str]] = {}
        self._analyse()
        if self.slow_readers():
            self.modules.add("Toybox.Time")  # Time.now(), for WfbCache.stale()

    def _analyse(self) -> None:
        for placed in self.resolved.items:
            element = placed.element
            value_exprs = self._value_expressions(element)
            paths: list[str] = []
            value_paths: list[str] = []
            other_paths: list[str] = []
            for expression in element.expressions():
                self.modules |= set(expression.modules)
                is_value = any(expression is v for v in value_exprs)
                for path in expression.sources:
                    if path not in paths:
                        paths.append(path)
                    if is_value:
                        if path not in value_paths:
                            value_paths.append(path)
                    elif path not in other_paths:
                        other_paths.append(path)
            # A time format reads the clock (and, for %h, the device settings)
            # even though the format string names no source.
            format_paths: list[str] = []
            if (isinstance(element, Text) and element.format
                    and formatting.is_time_spec(element.format)):
                # A date format reads the calendar; a time format reads the clock,
                # and %h additionally reads the 12/24-hour setting.
                if element.value is not None and element.value.value.type is Type.DATE:
                    format_paths.append("date.today")
                else:
                    format_paths.append("time.clock")
                    if "%h" in element.format:
                        format_paths.append("device.is_24_hour")
            self._bound[placed.id] = list(paths)
            self._value_bound[placed.id] = list(value_paths)
            self._other_bound[placed.id] = list(other_paths)
            paths = paths + [p for p in format_paths if p not in paths]
            self._per_element[placed.id] = paths
            for path in paths:
                self.modules.add(READERS[catalog.CATALOG[path].reader].module)

        for mode in ("active", "low_power", "always_on"):
            readers: list[str] = []
            for placed in self.resolved.items:
                if mode not in placed.element.modes:
                    continue
                for path in self._per_element[placed.id]:
                    reader = catalog.CATALOG[path].reader
                    if reader not in readers:
                        readers.append(reader)
            self._readers_for_mode[mode] = readers

    # -- emission ---------------------------------------------------------

    def slow_readers(self) -> list[str]:
        """Reader names on `Tier.SLOW` this design actually reads.

        Always found under ``active`` mode only: `wfb.ir`'s `_check_tiers`
        rejects binding a non-frame-tier source from a `low_power` or
        `always_on` element, so there is nothing to check here -- a slow
        reader appearing under any other mode would be an IR bug, not a
        design mistake, and `emit_reads` below is written on that assumption.
        """
        return sorted({name for name in self._readers_for_mode.get("active", [])
                       if READERS[name].tier is Tier.SLOW})

    def event_readers(self) -> list[str]:
        """Reader names on `Tier.EVENT` this design actually reads -- each one
        a complication subscription (see the `complication_*` entries in
        wfb/catalog.py).  Same `active`-only reasoning as `slow_readers`."""
        return sorted({name for name in self._readers_for_mode.get("active", [])
                       if READERS[name].tier is Tier.EVENT})

    def emit_reads(self, w: Writer, mode: str) -> None:
        readers = self._readers_for_mode.get(mode) or []
        if not readers:
            return
        tier_note = "frame-tier reads only" if mode != "active" else "data for this frame"
        w.comment(tier_note)
        for name in readers:
            reader = READERS[name]
            if reader.tier is Tier.SLOW:
                # Cached in a view field instead of called fresh every frame --
                # see WfbCache.mc and `_emit_cache_fields`.
                cache = f"_{reader.name}Cache"
                cache_time = f"_{reader.name}CacheTime"
                with w.block(f"if (WfbCache.stale({cache_time}, {reader.ttl_seconds}))"):
                    w.line(f"{cache} = {reader.call};")
                    w.line(f"{cache_time} = Time.now().value();")
                w.line(f"var {reader.name} = {cache};")
            else:
                # FRAME calls the API fresh; EVENT's `call` is the cached field
                # onComplicationChanged already filled in -- no staleness check,
                # unlike SLOW, because there is nothing to re-fetch on demand.
                w.line(f"var {reader.name} = {reader.call};")

    def parameters(self, placed) -> str:
        params = []
        for name in self._readers_used_by(placed):
            reader = READERS[name]
            params.append(f", {reader.name} as {reader.monkeyc_type}")
        return "".join(params)

    def arguments(self, placed) -> str:
        return "".join(f", {READERS[name].name}" for name in self._readers_used_by(placed))

    def guards(self, placed) -> list[str]:
        """Every local the element must null-check, declared in dependency order.

        Used as-is for an element with no placeholder/fallback policy (the
        whole thing hides together, as one guard always has); split into
        :meth:`value_guards`/:meth:`other_guards` for one that has one
        (Bug 5): the policy governs the value, not a colour.
        """
        from ..ir import local_name

        names: list[str] = []
        for path in self._bound[placed.id]:
            source = catalog.CATALOG[path]
            if source.guard_needed:
                names.append(local_name(path))
        return names

    def value_guards(self, placed) -> list[str]:
        """Locals reached through the element's own *value* expression(s)."""
        from ..ir import local_name

        return [local_name(path) for path in self._value_bound[placed.id]
                if catalog.CATALOG[path].guard_needed]

    def other_guards(self, placed) -> list[str]:
        """Locals dereferenced by a *different* expression (colour, track
        colour, max) -- there is no placeholder for a colour, so every one of
        these needs a real guard (Bug 5), even a source that is *also* the
        value: `color: "heart_rate.current > 100 ? ..."` dereferences
        `heartRateCurrent` at its own call site, which a placeholder guarding
        only the text's dereference does nothing to protect.
        """
        from ..ir import local_name

        return [local_name(path) for path in self._other_bound[placed.id]
                if catalog.CATALOG[path].guard_needed]

    @staticmethod
    def _value_expressions(element) -> tuple:
        """Which of an element's expressions its `when_absent:` policy governs.

        A `Text`'s only substitutable value is `value:`; a `Progress`'s fill
        fraction depends on both `value:` and `max:` together (one nullable
        reading is as absent as the other, from the fraction's point of
        view), which is also why `Builder._build_progress` checks their
        combined nullability as one thing. Every other element kind has no
        `when_absent:` field at all, so nothing here is "the value" -- every
        binding is an "other" one, guarded unconditionally.
        """
        if isinstance(element, Text):
            return (element.value,) if element.value is not None else ()
        if isinstance(element, Progress):
            return tuple(e for e in (element.value, element.maximum) if e is not None)
        if isinstance(element, Carousel):
            # Every item's reading, so none of them lands in `_other_bound` and
            # gets an element-level "hide the whole row" guard.  `_emit_carousel`
            # skips that guard outright and applies each item's own policy
            # inside its `case`, which is the only scope that makes sense here:
            # one absent reading is one blank slot.
            return tuple(e for item in element.items for e in item.expressions())
        return ()

    def declarations(self, placed) -> list[tuple[str, str]]:
        from ..ir import local_name

        out: list[tuple[str, str]] = []
        for path in self._bound[placed.id]:
            source = catalog.CATALOG[path]
            if source.field_name is None and source.type in (Type.TIME, Type.DATE):
                # time.clock/date.today: formatting.py reads the reader
                # parameter (`clock`/`date`) directly by name instead of
                # through a value local, so declaring one here would go
                # unused. Any other field_name-less source (an EVENT-tier
                # complication, where the reader *is* the value) still wants
                # its own named local below, the same as a source with a
                # field_name -- it is what `guards()` and the compiled
                # expression both reference by name.
                continue
            reader = READERS[source.reader]
            guard_parts = []
            if reader.nullable:
                # The reader itself can be absent -- Activity.getActivityInfo()
                # returns null when there is no activity -- so the field cannot
                # be dereferenced unconditionally.  Narrowing here keeps the
                # element's own `when_absent` guard below unchanged: an absent
                # reader and an absent field are the same thing to the design.
                guard_parts.append(f"{reader.name} != null")
            if source.array_guard is not None:
                # An Array being non-null does not mean it has an element at
                # this index -- a forecast provider can return fewer days than
                # asked for. Short-circuit `&&` means the null check above (if
                # any) always runs first, so `.size()` never hits a null array.
                guard_parts.append(source.array_guard)

            intermediate = getattr(source, "intermediate", None)
            if intermediate is not None:
                # A dotted field_name (`activeMinutesWeek.total`) has its own
                # nullable intermediate object.  monkeyc's flow typing narrows
                # a *local variable*, not a field-access expression, inside a
                # ternary -- `(reader.field != null) ? reader.field.x : null`
                # still typechecks `.x` against the declared (nullable) type
                # of `reader.field` and fails -- confirmed against a real
                # build, not assumed.  So the intermediate gets its own local
                # first, and the final field is guarded off *that* local,
                # exactly the pattern every other nullable field here uses.
                base = (reader.name if source.array_index is None
                        else f"{reader.name}[{source.array_index}]")
                obj_read = f"{base}.{intermediate}"
                if guard_parts:
                    obj_read = f"({' && '.join(guard_parts)}) ? {obj_read} : null"
                obj_name = f"{local_name(path)}Obj"
                out.append((obj_name, obj_read))
                suffix = source.field_name[len(intermediate) + 1:]
                out.append((local_name(path), f"({obj_name} != null) ? {obj_name}.{suffix} : null"))
                continue

            read = source.read_expr
            if guard_parts:
                read = f"({' && '.join(guard_parts)}) ? {read} : null"
            out.append((local_name(path), read))
        return out

    def _readers_used_by(self, placed) -> list[str]:
        readers: list[str] = []
        for path in self._per_element[placed.id]:
            reader = catalog.CATALOG[path].reader
            if reader not in readers:
                readers.append(reader)
        return readers

    def sources_for(self, placed) -> list[str]:
        return self._per_element[placed.id]


# --------------------------------------------------------------------------
# naming and small helpers


#: The symbol-derivation logic lives in `wfb.ir` now (`element_const_prefix`,
#: `element_method_name`) so that id uniqueness (checked in `ir.Builder`) and
#: symbol derivation (used here) cannot drift into two different notions of
#: "the same name" -- see `Builder._check_symbol_collision`. These aliases
#: keep every call site below unchanged.
_const_prefix = element_const_prefix
_method = element_method_name


def _field(name: str) -> str:
    parts = [p for p in name.replace("-", "_").split("_") if p]
    return "font" + "".join(p[:1].upper() + p[1:] for p in parts)


def _color(expression: Expression | None) -> str:
    if expression is None:
        return "Graphics.COLOR_WHITE"
    return expression.code


def _loaded_fonts(resolved: ResolvedFace) -> list[str]:
    """Every font resource this view loads once in `onLayout`.

    Covers both an author's declared custom text fonts and the synthetic
    per-size icon fonts (`wfb.icons.font_key`) -- both are bitmap fonts loaded
    the same way, so one list and one loop serves both.
    """
    out: list[str] = []
    for placed in resolved.items:
        if isinstance(placed, PlacedText) and placed.font_is_custom:
            if placed.font_reference not in out:
                out.append(placed.font_reference)
        elif isinstance(placed, PlacedIcon):
            if placed.font_key not in out:
                out.append(placed.font_key)
        elif isinstance(placed, PlacedCarousel):
            # One icon font per item (each glyph bakes at its own nominal size),
            # plus the reading's font when it is a declared custom one.
            for item in placed.items:
                if item.font_key not in out:
                    out.append(item.font_key)
            if placed.value_font_is_custom and placed.value_font_reference not in out:
                out.append(placed.value_font_reference)
    return out


def _describe(placed) -> str:
    element = placed.element
    if isinstance(element, Shape):
        return _article(element.shape.replace("_", " "))
    if isinstance(element, Text):
        return "text" if element.value is not None else "fixed text"
    if isinstance(element, Progress):
        return _article(f"{element.style} progress indicator")
    if isinstance(element, IconElement):
        if element.is_dynamic:
            return f"an icon chosen at runtime from {element.value_for.text!r}"
        return f"the {element.icon!r} icon"
    if isinstance(element, Carousel):
        return (f"a carousel of {len(element.items)} items, "
                f"{element.slots} shown at a time")
    return element.kind


def _and_list(items) -> str:
    items = list(items)
    if len(items) <= 1:
        return "".join(items)
    return ", ".join(items[:-1]) + " and " + items[-1]


def _article(noun: str) -> str:
    return f"{'an' if noun[:1].lower() in 'aeiou' else 'a'} {noun}"


def _mc_type(value: float) -> str:
    return "Float" if isinstance(value, float) else "Number"


def _mc_number(value: float) -> str:
    return f"{value}f" if isinstance(value, float) else str(int(value))
