//! Generated by garmin-wf-builder 0.1.0 -- do not edit.
//! Source:    tests/fixtures/outline_text/face.yaml
//! Face:      OutlineText (format 1)
//! Regenerate with `wfb build`.  Edits here are lost on the next build;
//! hand-written Monkey C belongs in a `raw` element instead (ADR 0007).

import Toybox.Graphics;
import Toybox.Lang;
import Toybox.Math;
import Toybox.System;
import Toybox.WatchUi;

//! OutlineText.
//!
//! One private method per design element, in draw order.  Each is named after
//! the element's `id:` in the source YAML, so a change on screen leads back to
//! a line in the design file.
class OutlineTextView extends WatchUi.WatchFace {
    //! Bitmap fonts -- custom text and icon glyphs alike -- loaded once in
    //! onLayout rather than per frame.
    private var _fontClock as FontResource?;

    //! Device-resident scalable ('face:') fonts (plan 11) -- a Graphics.
    //! VectorFont handed back by Graphics.getVectorFont, not a loaded
    //! resource; null wherever this device cannot build it, which every
    //! draw call below checks before using it.
    private var _fontBezel as Graphics.VectorFont?;

    function initialize() {
        WatchFace.initialize();
    }

    //! Load resources once.  Loading is expensive and must not happen per frame.
    function onLayout(dc as Dc) as Void {
        _fontClock = WatchUi.loadResource(Rez.Fonts.FontClock) as FontResource;

        _fontBezel = Graphics.getVectorFont({:face => Layout.FONT_BEZEL_FACE, :size => Layout.FONT_BEZEL_SIZE});
    }

    //! Draw the full face.
    //!
    //! Called once a minute in low-power mode and once a second while the watch is
    //! awake.
    function onUpdate(dc as Dc) as Void {
        dc.clearClip();
        // data for this frame
        var clock = System.getClockTime();
        var settings = System.getDeviceSettings();

        drawBackground(dc);
        drawClock(dc, clock, settings);
        drawUprightVector(dc);
        drawBrand(dc);
        drawBezelText(dc);
        drawDialNumbers(dc);
        drawDialRing(dc);
    }

    //! Awake: full-power updates resume.
    function onExitSleep() as Void {
        WatchUi.requestUpdate();
    }

    //! Asleep: the next onUpdate draws the low-power layout.
    function onEnterSleep() as Void {
        WatchUi.requestUpdate();
    }

    //! `background` -- a rectangle.
    //! Drawn in: active.
    private function drawBackground(dc as Dc) as Void {
        dc.setColor(Palette.BG, Graphics.COLOR_TRANSPARENT);
        dc.fillRectangle(Layout.BACKGROUND_X, Layout.BACKGROUND_Y,
                         Layout.BACKGROUND_WIDTH, Layout.BACKGROUND_HEIGHT);
    }

    //! `clock` -- text.
    //!
    //! Bound to `time.clock`.
    //! Drawn in: active.
    private function drawClock(dc as Dc, clock as System.ClockTime, settings as System.DeviceSettings) as Void {
        var font = _fontClock;
        if (font == null) {
            return;  // the font resource failed to load
        }

        dc.setColor(Palette.RING, Graphics.COLOR_TRANSPARENT);
        var offsets = Layout.OUTLINE_OFFSETS_2;
        var i = 0;
        while (i < offsets.size()) {
            dc.drawText(Layout.CLOCK_X + offsets[i], Layout.CLOCK_Y + offsets[i + 1], font,
                        WfbTime.displayHour(clock.hour, settings.is24Hour) + ":" + clock.min.format("%02d"),
                        Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER);
            i += 2;
        }

        dc.setColor(Palette.BG, Graphics.COLOR_TRANSPARENT);
        dc.drawText(Layout.CLOCK_X, Layout.CLOCK_Y, font,
                    WfbTime.displayHour(clock.hour, settings.is24Hour) + ":" + clock.min.format("%02d"),
                    Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER);
    }

    //! `upright_vector` -- fixed text.
    //! Drawn in: active.
    private function drawUprightVector(dc as Dc) as Void {
        var font = _fontBezel;
        if (font != null) {
            dc.setColor(Palette.RING, Graphics.COLOR_TRANSPARENT);
            var offsets = Layout.OUTLINE_OFFSETS_2;
            var i = 0;
            while (i < offsets.size()) {
                dc.drawText(Layout.UPRIGHT_VECTOR_X + offsets[i], Layout.UPRIGHT_VECTOR_Y + offsets[i + 1], font,
                            "UPRIGHT",
                            Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER);
                i += 2;
            }

            dc.setColor(Palette.BG, Graphics.COLOR_TRANSPARENT);
            dc.drawText(Layout.UPRIGHT_VECTOR_X, Layout.UPRIGHT_VECTOR_Y, font,
                        "UPRIGHT",
                        Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER);
        }
    }

    //! `brand` -- fixed text.
    //! Drawn in: active.
    private function drawBrand(dc as Dc) as Void {
        var font = _fontBezel;
        if (font != null) {
            dc.setColor(Palette.RING, Graphics.COLOR_TRANSPARENT);
            var offsets = Layout.OUTLINE_OFFSETS_1;
            var i = 0;
            while (i < offsets.size()) {
                dc.drawAngledText(Layout.BRAND_X + offsets[i], Layout.BRAND_Y + offsets[i + 1], font, "GARMIN",
                                  Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER, Layout.BRAND_ANGLE);
                i += 2;
            }

            dc.setColor(Palette.BG, Graphics.COLOR_TRANSPARENT);
            dc.drawAngledText(Layout.BRAND_X, Layout.BRAND_Y, font, "GARMIN",
                              Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER, Layout.BRAND_ANGLE);
        }
    }

    //! `bezel_text` -- fixed text.
    //! Drawn in: active.
    private function drawBezelText(dc as Dc) as Void {
        var font = _fontBezel;
        if (font != null) {
            dc.setColor(Palette.RING, Graphics.COLOR_TRANSPARENT);
            var offsets = Layout.OUTLINE_OFFSETS_3;
            var i = 0;
            while (i < offsets.size()) {
                dc.drawRadialText(Layout.BEZEL_TEXT_X + offsets[i], Layout.BEZEL_TEXT_Y + offsets[i + 1], font, "BEZEL",
                                  Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER, Layout.BEZEL_TEXT_ANGLE, Layout.BEZEL_TEXT_RADIUS,
                                  Graphics.RADIAL_TEXT_DIRECTION_CLOCKWISE);
                i += 2;
            }

            dc.setColor(Palette.BG, Graphics.COLOR_TRANSPARENT);
            dc.drawRadialText(Layout.BEZEL_TEXT_X, Layout.BEZEL_TEXT_Y, font, "BEZEL",
                              Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER, Layout.BEZEL_TEXT_ANGLE, Layout.BEZEL_TEXT_RADIUS,
                              Graphics.RADIAL_TEXT_DIRECTION_CLOCKWISE);
        }
    }

    //! `dial_numbers` -- a radial pattern: 3 copies, 12 degrees apart.
    //! Drawn in: active.
    private function drawDialNumbers(dc as Dc) as Void {
        var cx = Layout.DIAL_NUMBERS_X;
        var cy = Layout.DIAL_NUMBERS_Y;
        var font0 = _fontBezel;

        dc.setColor(Palette.BG, Graphics.COLOR_TRANSPARENT);  // hoisted: one colour
        for (var i = 0; i < 3; i++) {
            var angle = 3.9269908169872414 + i * 0.20943951023931956;  // (225 + 12 i) degrees
            var sin = Math.sin(angle);
            var cos = Math.cos(angle);
            if (font0 != null) {
                dc.setColor(Palette.RING, Graphics.COLOR_TRANSPARENT);
                var outlineOffsetsDIAL_NUMBERS_0 = Layout.OUTLINE_OFFSETS_2;
                var outlineIDIAL_NUMBERS_0 = 0;
                while (outlineIDIAL_NUMBERS_0 < outlineOffsetsDIAL_NUMBERS_0.size()) {
                    dc.drawAngledText(WfbGeom.rotatedX(Layout.DIAL_NUMBERS_0_X, Layout.DIAL_NUMBERS_0_Y, cx, sin, cos) + outlineOffsetsDIAL_NUMBERS_0[outlineIDIAL_NUMBERS_0],
                                      WfbGeom.rotatedY(Layout.DIAL_NUMBERS_0_X, Layout.DIAL_NUMBERS_0_Y, cy, sin, cos) + outlineOffsetsDIAL_NUMBERS_0[outlineIDIAL_NUMBERS_0 + 1], font0, (i + 1).toString(),
                                      Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER, -225.0 - i * 12.0);
                    outlineIDIAL_NUMBERS_0 += 2;
                }

                dc.setColor(Palette.BG, Graphics.COLOR_TRANSPARENT);
                dc.drawAngledText(WfbGeom.rotatedX(Layout.DIAL_NUMBERS_0_X, Layout.DIAL_NUMBERS_0_Y, cx, sin, cos),
                                  WfbGeom.rotatedY(Layout.DIAL_NUMBERS_0_X, Layout.DIAL_NUMBERS_0_Y, cy, sin, cos), font0, (i + 1).toString(),
                                  Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER, -225.0 - i * 12.0);
            }
        }
    }

    //! `dial_ring` -- a radial pattern: 3 copies, 12 degrees apart.
    //! Drawn in: active.
    private function drawDialRing(dc as Dc) as Void {
        var cx = Layout.DIAL_RING_X;
        var cy = Layout.DIAL_RING_Y;
        var font0 = _fontBezel;

        dc.setColor(Palette.BG, Graphics.COLOR_TRANSPARENT);  // hoisted: one colour
        for (var i = 0; i < 3; i++) {
            var angle = 4.4505895925855405 + i * 0.20943951023931956;  // (255 + 12 i) degrees
            var sin = Math.sin(angle);
            var cos = Math.cos(angle);
            if (font0 != null) {
                dc.setColor(Palette.RING, Graphics.COLOR_TRANSPARENT);
                var outlineOffsetsDIAL_RING_0 = Layout.OUTLINE_OFFSETS_1;
                var outlineIDIAL_RING_0 = 0;
                while (outlineIDIAL_RING_0 < outlineOffsetsDIAL_RING_0.size()) {
                    dc.drawRadialText(WfbGeom.rotatedX(Layout.DIAL_RING_0_X, Layout.DIAL_RING_0_Y, cx, sin, cos) + outlineOffsetsDIAL_RING_0[outlineIDIAL_RING_0],
                                      WfbGeom.rotatedY(Layout.DIAL_RING_0_X, Layout.DIAL_RING_0_Y, cy, sin, cos) + outlineOffsetsDIAL_RING_0[outlineIDIAL_RING_0 + 1], font0, "I",
                                      Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER, -165.0 - i * 12.0, Layout.DIAL_RING_0_RADIUS,
                                      Graphics.RADIAL_TEXT_DIRECTION_CLOCKWISE);
                    outlineIDIAL_RING_0 += 2;
                }

                dc.setColor(Palette.BG, Graphics.COLOR_TRANSPARENT);
                dc.drawRadialText(WfbGeom.rotatedX(Layout.DIAL_RING_0_X, Layout.DIAL_RING_0_Y, cx, sin, cos),
                                  WfbGeom.rotatedY(Layout.DIAL_RING_0_X, Layout.DIAL_RING_0_Y, cy, sin, cos), font0, "I",
                                  Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER, -165.0 - i * 12.0, Layout.DIAL_RING_0_RADIUS,
                                  Graphics.RADIAL_TEXT_DIRECTION_CLOCKWISE);
            }
        }
    }
}
