//! Generated by garmin-wf-builder 0.1.0 -- do not edit.
//! Source:    tests/fixtures/outline_text/face.yaml
//! Face:      OutlineText (format 1)
//! Device:    fenix8solar47mm -- 260x260 round, mip, family round-260x260
//! Regenerate with `wfb build`.  Edits here are lost on the next build;
//! hand-written Monkey C belongs in a `raw` element instead (ADR 0007).

import Toybox.Lang;

//! Layout resolved for fenix8solar47mm.
//!
//! Every value here came from a relative unit in the design -- percentages of
//! the parent box, fractions of the screen's minor radius, angles measured
//! clockwise from 12 o'clock.  Resolving them here means the device performs
//! no layout arithmetic at all, which costs neither memory nor frame time.
module Layout {
    //! The screen, for reference.
    const SCREEN_WIDTH as Number = 260;
    const SCREEN_HEIGHT as Number = 260;

    //! Device-resident scalable ('face:') fonts this design draws with (plan 11).
    //!
    //! '_FACE'/'_SIZE' feed Graphics.getVectorFont directly, in onLayout.
    //! '_AVAILABLE' is emitted only for a font at least one target device in
    //! this build fails to publish -- the shared view (identical on every
    //! device) reads it to decide whether to even attempt construction here,
    //! so every device's own Layout.mc has to define it once any device
    //! needs it (wfb.availability.Guards.vector_fonts).

    //! `font.bezel`
    const FONT_BEZEL_FACE as String = "RobotoCondensedBold";  // requested, in author order: RobotoCondensedBold, RobotoCondensedRegular
    const FONT_BEZEL_SIZE as Number = 8;

    //! 'outline:' stamp offsets (plan 15): the disc-perimeter table for
    //! each ring width this design actually uses, shared by every element
    //! drawing with that width -- the array the generated stamp loop
    //! iterates over, index i/i+1 per (dx, dy) pair.
    const OUTLINE_OFFSETS_2 as Array<Number> = [-2, 0, -1, -1, -1, 1, 0, -2, 0, 2, 1, -1, 1, 1, 2, 0];  // 8 disc-perimeter points, 2px ring (plan 15, docs/research/14-stamped-ring-text.md §1)
    const OUTLINE_OFFSETS_1 as Array<Number> = [-1, 0, 0, -1, 0, 1, 1, 0];  // 4 disc-perimeter points, 1px ring (plan 15, docs/research/14-stamped-ring-text.md §1)
    const OUTLINE_OFFSETS_3 as Array<Number> = [-3, 0, -2, -2, -2, -1, -2, 1, -2, 2, -1, -2, -1, 2, 0, -3, 0, 3, 1, -2, 1, 2, 2, -2, 2, -1, 2, 1, 2, 2, 3, 0];  // 16 disc-perimeter points, 3px ring (plan 15, docs/research/14-stamped-ring-text.md §1)

    //! `background` -- a rectangle
    const BACKGROUND_X as Number = 0;
    const BACKGROUND_Y as Number = 0;
    const BACKGROUND_WIDTH as Number = 260;
    const BACKGROUND_HEIGHT as Number = 260;

    //! `clock` -- text
    const CLOCK_X as Number = 130;
    const CLOCK_Y as Number = 104;
    const CLOCK_WIDTH as Number = 76;  // widest rendering "23:59" is 76 px

    //! `upright_vector` -- fixed text
    const UPRIGHT_VECTOR_X as Number = 130;
    const UPRIGHT_VECTOR_Y as Number = 169;
    const UPRIGHT_VECTOR_WIDTH as Number = 26;  // widest rendering "UPRIGHT" is 26 px (estimated)

    //! `brand` -- fixed text
    const BRAND_X as Number = 130;
    const BRAND_Y as Number = 91;
    const BRAND_WIDTH as Number = 23;  // widest rendering "GARMIN" is 23 px (estimated)
    const BRAND_ANGLE as Float = 315.0f;  // 45deg clockwise rotation from upright, in Garmin's convention

    //! `bezel_text` -- fixed text
    const BEZEL_TEXT_X as Number = 130;
    const BEZEL_TEXT_Y as Number = 130;
    const BEZEL_TEXT_WIDTH as Number = 17;  // widest rendering "BEZEL" is 17 px (estimated)
    const BEZEL_TEXT_ANGLE as Float = 0.0f;  // 90deg clockwise from 12 o'clock, in Garmin's convention
    const BEZEL_TEXT_RADIUS as Number = 57;
}
