//! Generated by garmin-wf-builder 0.1.0 -- do not edit.
//! Source:    examples/slice/face.yaml
//! Face:      Slice (format 1)
//! Regenerate with `wfb build`.  Edits here are lost on the next build;
//! hand-written Monkey C belongs in a `raw` element instead (ADR 0007).

import Toybox.Lang;

//! Colours declared in the design's `palette:` block.
//!
//! Elements reference these by name rather than by hex, so a colour can be
//! changed in one place and linted in one place.
module Palette {
    //! `palette.bg` = #000000
    const BG as Number = 0x000000;

    //! `palette.text` = #FFFFFF
    const TEXT as Number = 0xFFFFFF;

    //! `palette.accent` = #FF5500
    const ACCENT as Number = 0xFF5500;

    //! `palette.track` = #555555
    const TRACK as Number = 0x555555;
}
