//! Generated by garmin-wf-builder 0.1.0 -- do not edit.
//! Source:    examples/slice/face.yaml
//! Face:      Slice (format 1)
//! Device:    fenix8solar51mm -- 280x280 round, mip, family round-280x280
//! Regenerate with `wfb build`.  Edits here are lost on the next build;
//! hand-written Monkey C belongs in a `raw` element instead (ADR 0007).

import Toybox.Lang;

//! Layout resolved for fenix8solar51mm.
//!
//! Every value here came from a relative unit in the design -- percentages of
//! the parent box, fractions of the screen's minor radius, angles measured
//! clockwise from 12 o'clock.  Resolving them here means the device performs
//! no layout arithmetic at all, which costs neither memory nor frame time.
module Layout {
    //! The screen, for reference.
    const SCREEN_WIDTH as Number = 280;
    const SCREEN_HEIGHT as Number = 280;

    //! `background` -- a rectangle
    const BACKGROUND_X as Number = 0;
    const BACKGROUND_Y as Number = 0;
    const BACKGROUND_WIDTH as Number = 280;
    const BACKGROUND_HEIGHT as Number = 280;

    //! `step_ring` -- an arc progress indicator
    const STEP_RING_CX as Number = 140;
    const STEP_RING_CY as Number = 140;
    const STEP_RING_RADIUS as Number = 126;
    const STEP_RING_THICKNESS as Number = 10;  // pen width; there is no filled-arc primitive
    const STEP_RING_START as Float = 270.0f;  // 180deg clockwise from 12 o'clock, in Garmin's convention
    const STEP_RING_SWEEP as Float = 340.0f;  // clockwise-positive degrees

    //! `clock` -- text
    const CLOCK_X as Number = 140;
    const CLOCK_Y as Number = 129;
    const CLOCK_WIDTH as Number = 187;  // widest rendering "23:59" is 187 px

    //! `steps_icon` -- the 'steps' icon
    const STEPS_ICON_CX as Number = 140;
    const STEPS_ICON_CY as Number = 185;

    //! `steps_value` -- text
    const STEPS_VALUE_X as Number = 140;
    const STEPS_VALUE_Y as Number = 224;
    const STEPS_VALUE_WIDTH as Number = 80;  // widest rendering "88888" is 80 px (estimated)
}
