//! Generated by garmin-wf-builder 0.1.0 -- do not edit.
//! Source:    examples/slice/face.yaml
//! Face:      Slice (format 1)
//! Regenerate with `wfb build`.  Edits here are lost on the next build;
//! hand-written Monkey C belongs in a `raw` element instead (ADR 0007).

import Toybox.Application;
import Toybox.Lang;
import Toybox.WatchUi;

//! The application entry point for 'Slice'.
class SliceApp extends Application.AppBase {
    function initialize() {
        AppBase.initialize();
    }

    function getInitialView() as [Views] or [Views, InputDelegates] {
        return [ new SliceView() ];
    }
}
