//! Generated by garmin-wf-builder 0.1.0 -- do not edit.
//! Source:    examples/slice/face.yaml
//! Face:      Slice (format 1)
//! Device:    fenix8solar47mm
//! Regenerate with `wfb build`.  Edits here are lost on the next build;
//! hand-written Monkey C belongs in a `raw` element instead (ADR 0007).

import Toybox.ActivityMonitor;
import Toybox.Graphics;
import Toybox.Lang;
import Toybox.System;
import Toybox.WatchUi;

//! Slice.
//!
//! One private method per design element, in draw order.  Each is named after
//! the element's `id:` in the source YAML, so a change on screen leads back to
//! a line in the design file.
class SliceView extends WatchUi.WatchFace {
    //! Bitmap fonts -- custom text and icon glyphs alike -- loaded once in
    //! onLayout rather than per frame.
    private var _fontClock as FontResource?;
    private var _fontIcon30pxUee14 as FontResource?;

    function initialize() {
        WatchFace.initialize();
    }

    //! Load resources once.  Loading is expensive and must not happen per frame.
    function onLayout(dc as Dc) as Void {
        _fontClock = WatchUi.loadResource(Rez.Fonts.FontClock) as FontResource;
        _fontIcon30pxUee14 = WatchUi.loadResource(Rez.Fonts.FontIcon30pxUee14) as FontResource;
    }

    //! Draw the full face.
    //!
    //! Called once a minute in low-power mode and once a second while the watch is
    //! awake.
    function onUpdate(dc as Dc) as Void {
        dc.clearClip();
        // data for this frame
        var activity = ActivityMonitor.getInfo();
        var clock = System.getClockTime();
        var settings = System.getDeviceSettings();

        drawBackground(dc);
        drawStepRing(dc, activity);
        drawClock(dc, clock, settings);
        drawStepsIcon(dc);
        drawStepsValue(dc, activity);
    }

    //! Awake: full-power updates resume.
    function onExitSleep() as Void {
        WatchUi.requestUpdate();
    }

    //! Asleep: the next onUpdate draws the low-power layout.
    function onEnterSleep() as Void {
        WatchUi.requestUpdate();
    }

    //! `background` -- a rectangle.
    //! Drawn in: active.
    private function drawBackground(dc as Dc) as Void {
        dc.setColor(Palette.BG, Graphics.COLOR_TRANSPARENT);
        dc.fillRectangle(Layout.BACKGROUND_X, Layout.BACKGROUND_Y,
                         Layout.BACKGROUND_WIDTH, Layout.BACKGROUND_HEIGHT);
    }

    //! `step_ring` -- an arc progress indicator.
    //!
    //! Bound to `activity.steps` and `activity.step_goal`.
    //! When the value is absent: hide.
    //! Drawn in: active.
    private function drawStepRing(dc as Dc, activity as ActivityMonitor.Info) as Void {
        // the values this element is bound to
        var activitySteps = activity.steps;
        var activityStepGoal = activity.stepGoal;

        // when_absent: hide
        if (activitySteps == null || activityStepGoal == null) {
            return;
        }

        // the unfilled track
        dc.setColor(Palette.TRACK, Graphics.COLOR_TRANSPARENT);
        WfbArc.drawSpan(dc, Layout.STEP_RING_CX, Layout.STEP_RING_CY, Layout.STEP_RING_RADIUS,
                        Layout.STEP_RING_THICKNESS, Layout.STEP_RING_START, Layout.STEP_RING_SWEEP);

        // the filled portion
        dc.setColor(Palette.ACCENT, Graphics.COLOR_TRANSPARENT);
        WfbArc.drawProgress(dc, Layout.STEP_RING_CX, Layout.STEP_RING_CY, Layout.STEP_RING_RADIUS,
                            Layout.STEP_RING_THICKNESS, Layout.STEP_RING_START, Layout.STEP_RING_SWEEP,
                            WfbMath.percent(activitySteps, activityStepGoal) / 100.0);
    }

    //! `clock` -- text.
    //!
    //! Bound to `time.clock`.
    //! Drawn in: active.
    private function drawClock(dc as Dc, clock as System.ClockTime, settings as System.DeviceSettings) as Void {
        var font = _fontClock;
        if (font == null) {
            return;  // the font resource failed to load
        }

        dc.setColor(Palette.TEXT, Graphics.COLOR_TRANSPARENT);
        dc.drawText(Layout.CLOCK_X, Layout.CLOCK_Y, font,
                    WfbTime.displayHour(clock.hour, settings.is24Hour) + ":" + clock.min.format("%02d"),
                    Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER);
    }

    //! `steps_icon` -- the 'steps' icon.
    //! Drawn in: active.
    private function drawStepsIcon(dc as Dc) as Void {
        var font = _fontIcon30pxUee14;
        if (font == null) {
            return;  // the icon font resource failed to load
        }

        // 'steps'
        dc.setColor(Palette.ACCENT, Graphics.COLOR_TRANSPARENT);
        dc.drawText(Layout.STEPS_ICON_CX, Layout.STEPS_ICON_CY, font,
                    "",
                    Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER);
    }

    //! `steps_value` -- text.
    //!
    //! Bound to `activity.steps`.
    //! When the value is absent: placeholder.
    //! Drawn in: active.
    private function drawStepsValue(dc as Dc, activity as ActivityMonitor.Info) as Void {
        // the values this element is bound to
        var activitySteps = activity.steps;

        // when_absent: placeholder
        var text = "--";
        if (activitySteps != null) {
            text = activitySteps.format("%d");
        }

        dc.setColor(Palette.TEXT, Graphics.COLOR_TRANSPARENT);
        dc.drawText(Layout.STEPS_VALUE_X, Layout.STEPS_VALUE_Y, Graphics.FONT_SMALL,
                    text,
                    Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER);
    }
}
