//! Generated by garmin-wf-builder 0.1.0 -- do not edit.
//! Source:    tests/fixtures/vector_text/face.yaml
//! Face:      VectorText (format 1)
//! Device:    fenix8solar47mm
//! Regenerate with `wfb build`.  Edits here are lost on the next build;
//! hand-written Monkey C belongs in a `raw` element instead (ADR 0007).

import Toybox.Graphics;
import Toybox.Lang;
import Toybox.System;
import Toybox.WatchUi;

//! VectorText.
//!
//! One private method per design element, in draw order.  Each is named after
//! the element's `id:` in the source YAML, so a change on screen leads back to
//! a line in the design file.
class VectorTextView extends WatchUi.WatchFace {
    //! Bitmap fonts -- custom text and icon glyphs alike -- loaded once in
    //! onLayout rather than per frame.
    private var _fontClock as FontResource?;

    //! Device-resident scalable ('face:') fonts (plan 11) -- a Graphics.
    //! VectorFont handed back by Graphics.getVectorFont, not a loaded
    //! resource; null wherever this device cannot build it, which every
    //! draw call below checks before using it.
    private var _fontBezel as Graphics.VectorFont?;

    function initialize() {
        WatchFace.initialize();
    }

    //! Load resources once.  Loading is expensive and must not happen per frame.
    function onLayout(dc as Dc) as Void {
        _fontClock = WatchUi.loadResource(Rez.Fonts.FontClock) as FontResource;

        _fontBezel = Graphics.getVectorFont({:face => Layout.FONT_BEZEL_FACE, :size => Layout.FONT_BEZEL_SIZE});
    }

    //! Draw the full face.
    //!
    //! Called once a minute in low-power mode and once a second while the watch is
    //! awake.
    function onUpdate(dc as Dc) as Void {
        dc.clearClip();
        // data for this frame
        var clock = System.getClockTime();
        var settings = System.getDeviceSettings();

        drawBackground(dc);
        drawClock(dc, clock, settings);
        drawUprightVector(dc);
        drawBrand(dc);
        drawBezelText(dc);
    }

    //! Awake: full-power updates resume.
    function onExitSleep() as Void {
        WatchUi.requestUpdate();
    }

    //! Asleep: the next onUpdate draws the low-power layout.
    function onEnterSleep() as Void {
        WatchUi.requestUpdate();
    }

    //! `background` -- a rectangle.
    //! Drawn in: active.
    private function drawBackground(dc as Dc) as Void {
        dc.setColor(Palette.BG, Graphics.COLOR_TRANSPARENT);
        dc.fillRectangle(Layout.BACKGROUND_X, Layout.BACKGROUND_Y,
                         Layout.BACKGROUND_WIDTH, Layout.BACKGROUND_HEIGHT);
    }

    //! `clock` -- text.
    //!
    //! Bound to `time.clock`.
    //! Drawn in: active.
    private function drawClock(dc as Dc, clock as System.ClockTime, settings as System.DeviceSettings) as Void {
        var font = _fontClock;
        if (font == null) {
            return;  // the font resource failed to load
        }

        dc.setColor(Palette.TEXT, Graphics.COLOR_TRANSPARENT);
        dc.drawText(Layout.CLOCK_X, Layout.CLOCK_Y, font,
                    WfbTime.displayHour(clock.hour, settings.is24Hour) + ":" + clock.min.format("%02d"),
                    Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER);
    }

    //! `upright_vector` -- fixed text.
    //! Drawn in: active.
    private function drawUprightVector(dc as Dc) as Void {
        var font = _fontBezel;
        if (font != null) {
            dc.setColor(Palette.TEXT, Graphics.COLOR_TRANSPARENT);
            dc.drawText(Layout.UPRIGHT_VECTOR_X, Layout.UPRIGHT_VECTOR_Y, font,
                        "UPRIGHT",
                        Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER);
        }
    }

    //! `brand` -- fixed text.
    //! Drawn in: active.
    private function drawBrand(dc as Dc) as Void {
        var font = _fontBezel;
        if (font != null) {
            dc.setColor(Palette.ACCENT, Graphics.COLOR_TRANSPARENT);
            dc.drawAngledText(Layout.BRAND_X, Layout.BRAND_Y, font, "GARMIN",
                              Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER, Layout.BRAND_ANGLE);
        }
    }

    //! `bezel_text` -- fixed text.
    //! Drawn in: active.
    private function drawBezelText(dc as Dc) as Void {
        var font = _fontBezel;
        if (font != null) {
            dc.setColor(Palette.ACCENT, Graphics.COLOR_TRANSPARENT);
            dc.drawRadialText(Layout.BEZEL_TEXT_X, Layout.BEZEL_TEXT_Y, font, "BEZEL",
                              Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER, Layout.BEZEL_TEXT_ANGLE, Layout.BEZEL_TEXT_RADIUS,
                              Graphics.RADIAL_TEXT_DIRECTION_CLOCKWISE);
        }
    }
}
