// The garmin-raster probe faces: one face per primitive family, each a grid
// of sizes, odd and even, drawn white on black so a simulator capture shows
// exactly which pixels Garmin's rasteriser lights. Every face targets the
// three verification devices and the AMOLED fenix847mm.
//
//   node docs/research/probes/garmin-raster/make_faces.ts
//
// writes faces/<family>/face.yaml beside this file. Positions are pixel
// offsets from the screen's centre, inside the central 180 px square every
// target shows in full.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const TARGETS = ["fenix8solar47mm", "fenix8solar51mm", "fr955", "fenix847mm"];

/** A uuid from the family's name, so a face keeps its id from run to run. */
function id(family: string): string {
  let h = 2166136261;
  const hex: string[] = [];
  for (let i = 0; i < 16; i++) {
    for (const ch of family + i) h = Math.imul(h ^ ch.charCodeAt(0), 16777619) >>> 0;
    hex.push((h & 0xff).toString(16).padStart(2, "0"));
  }
  const s = hex.join("");
  return `${s.slice(0, 8)}-${s.slice(8, 12)}-4${s.slice(13, 16)}-8${s.slice(17, 20)}-${s.slice(20, 32)}`;
}

type Element = Record<string, unknown>;

const at = (dx: number, dy: number): string => `{ anchor: center, dx: ${dx}px, dy: ${dy}px }`;

function yamlOf(value: unknown, indent: number): string {
  const pad = " ".repeat(indent);
  return Object.entries(value as Element).map(([k, v]) => {
    if (typeof v === "object" && v !== null && !Array.isArray(v)) return `${pad}${k}:\n${yamlOf(v, indent + 2)}`;
    if (Array.isArray(v)) return `${pad}${k}:\n${v.map((item) => `${pad}  - ${item}`).join("\n")}`;
    return `${pad}${k}: ${v}`;
  }).join("\n");
}

function face(family: string, about: string, elements: Record<string, Element>, extra = ""): string {
  return `# garmin-raster probe: ${about}
# Generated by make_faces.ts; edit that, not this.

format: 2

face:
  id: ${id(family)}
  name: Raster ${family}
  version: 1.0.0

build:
  targets: [${TARGETS.join(", ")}]

resources:
  palette:
    bg: "#000000"
    ink: "#FFFFFF"
${extra}
static:
  background:
    type: rectangle
    at: { anchor: center }
    size: { width: 100%, height: 100% }
    color: color.bg

elements:
${yamlOf(elements, 2)}
`;
}

/** `n` cells of a `columns`-wide grid, `pitch` apart, centred on the screen. */
function grid(n: number, columns: number, pitch: number): [number, number][] {
  const rows = Math.ceil(n / columns);
  return Array.from({ length: n }, (_, i) => [
    Math.round((i % columns - (columns - 1) / 2) * pitch),
    Math.round((Math.floor(i / columns) - (rows - 1) / 2) * pitch),
  ]);
}

const faces: Record<string, string> = {};

// fillCircle and drawCircle with a pen: radii 1..12, then pens 1..4 on odd and even radii.
{
  const els: Record<string, Element> = {};
  const fills = Array.from({ length: 12 }, (_, i) => i + 1);
  grid(fills.length, 6, 28).forEach(([dx, dy], i) => {
    els[`fill_r${fills[i]}`] = { type: "circle", at: at(dx, dy - 40), radius: `${fills[i]}px`, color: "color.ink" };
  });
  const outlines: [number, number][] = [];
  for (const pen of [1, 2, 3, 4]) for (const r of [8, 9]) outlines.push([pen, r]);
  grid(outlines.length, 4, 40).forEach(([dx, dy], i) => {
    const [pen, r] = outlines[i]!;
    els[`draw_r${r}_p${pen}`] = { type: "circle", at: at(dx, dy + 40), radius: `${r}px`, thickness: `${pen}px`, filled: "false", color: "color.ink" };
  });
  faces["circles"] = face("circles", "fillCircle radii 1-12, drawCircle pens 1-4 on radii 8 and 9", els);
}

// drawArc with a pen, across start angles and sweeps.
{
  const els: Record<string, Element> = {};
  const cases: [number, number, number][] = [];
  for (const pen of [1, 3]) for (const start of [0, 45, 100, 270]) for (const sweep of [30, 135]) cases.push([pen, start, sweep]);
  grid(cases.length, 4, 42).forEach(([dx, dy], i) => {
    const [pen, start, sweep] = cases[i]!;
    els[`arc_p${pen}_s${start}_w${sweep}`] = {
      type: "arc", at: at(dx, dy), radius: "14px", thickness: `${pen}px`, start_angle: `${start}deg`, sweep: `${sweep}deg`, color: "color.ink",
    };
  });
  faces["arcs"] = face("arcs", "drawArc, pens 1 and 3, four start angles, two sweeps", els);
}

// drawLine with a width, across angles.
{
  const els: Record<string, Element> = {};
  const cases: [number, number][] = [];
  for (const width of [1, 2, 3, 4]) for (const angle of [0, 15, 30, 45, 60, 90]) cases.push([width, angle]);
  grid(cases.length, 6, 30).forEach(([dx, dy], i) => {
    const [width, angle] = cases[i]!;
    const r = 11, t = angle * Math.PI / 180;
    const [ex, ey] = [Math.round(r * Math.cos(t)), Math.round(-r * Math.sin(t))];
    els[`line_w${width}_a${angle}`] = { type: "line", at: at(dx - ex, dy - ey), to: at(dx + ex, dy + ey), thickness: `${width}px`, color: "color.ink" };
  });
  faces["lines"] = face("lines", "drawLine, widths 1-4 at six angles", els);
}

// fillPolygon: triangles and a quad, at odd and even extents.
{
  const els: Record<string, Element> = {};
  const shapes: [string, [number, number][]][] = [
    ["tri_up", [[0, -9], [-8, 7], [8, 7]]], ["tri_down", [[0, 10], [-9, -8], [9, -8]]],
    ["tri_thin", [[0, -12], [-2, 12], [2, 12]]], ["quad", [[-9, -5], [6, -9], [9, 6], [-5, 9]]],
    ["tri_odd", [[0, -9], [-7, 6], [8, 7]]], ["sliver", [[-12, 0], [12, 1], [12, 2]]],
  ];
  grid(shapes.length, 3, 50).forEach(([dx, dy], i) => {
    const [name, points] = shapes[i]!;
    els[name] = { type: "polygon", points: points.map(([x, y]) => at(dx + x, dy + y)), color: "color.ink" };
  });
  faces["polygons"] = face("polygons", "fillPolygon: triangles, a quad and slivers", els);
}

// fillRoundedRectangle and drawRoundedRectangle; drawRectangle with a pen.
{
  const els: Record<string, Element> = {};
  const cases: [number, number, number, number][] = [];
  for (const [w, h] of [[20, 14], [21, 15]] as const) for (const r of [2, 3, 5]) for (const pen of [0, 2]) cases.push([w, h, r, pen]);
  grid(cases.length, 4, 40).forEach(([dx, dy], i) => {
    const [w, h, r, pen] = cases[i]!;
    els[`rr_${w}x${h}_r${r}${pen ? `_p${pen}` : ""}`] = {
      type: "rectangle", at: at(dx, dy - 20), size: `{ width: ${w}px, height: ${h}px }`, corner_radius: `${r}px`,
      ...(pen ? { thickness: `${pen}px`, filled: "false" } : {}), color: "color.ink",
    };
  });
  [1, 2, 3, 4].forEach((pen, i) => {
    els[`rect_p${pen}`] = { type: "rectangle", at: at(-60 + i * 40, 70), size: "{ width: 25px, height: 17px }", thickness: `${pen}px`, filled: "false", color: "color.ink" };
  });
  faces["rects"] = face("rects", "rounded rectangles filled and drawn, radii 2/3/5 on odd and even sizes; drawRectangle pens 1-4", els);
}

// A run of drawText from a baked sheet, and the same with antialias.
{
  const font = "../../../../../../examples/showcase/assets/ChivoMono-Bold.ttf";
  faces["text"] = face("text", "drawText from a baked sheet, plain and anti-aliased", {
    plain: { type: "text", text: '"0123456789"', font: "font.mono", at: at(0, -20), color: "color.ink" },
    smooth: { type: "text", text: '"0123456789"', font: "font.smooth", at: at(0, 20), color: "color.ink" },
  }, `  fonts:
    mono: { source: ${font}, size: 24px }
    smooth: { source: ${font}, size: 24px, antialias: true }
`);
}

// A swatch strip: how the simulator quantises and dithers colours off the 64.
{
  const els: Record<string, Element> = {};
  const colours = ["#000000", "#555555", "#AAAAAA", "#FFFFFF", "#FF0000", "#00FF00", "#0000FF", "#FF5500",
    "#808080", "#C0C0C0", "#123456", "#FF8000", "#7F7F7F", "#2A2A2A", "#D4D4D4", "#3366CC"];
  let palette = "";
  grid(colours.length, 4, 36).forEach(([dx, dy], i) => {
    palette += `    s${i}: "${colours[i]}"\n`;
    els[`swatch_${i}`] = { type: "rectangle", at: at(dx, dy), size: "{ width: 30px, height: 30px }", color: `color.s${i}` };
  });
  faces["swatches"] = face("swatches", "sixteen swatches, on and off the 64 MIP colours", els, palette);
}

for (const [family, text] of Object.entries(faces)) {
  const dir = join(HERE, "faces", family);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "face.yaml"), text);
}
console.log(`wrote ${Object.keys(faces).length} faces to ${join(HERE, "faces")}`);
