// The garmin-raster probe faces: one face per primitive family, each a grid
// of sizes, odd and even, drawn white on black so a simulator capture shows
// exactly which pixels Garmin's rasteriser lights. Every face targets the
// three verification devices and the AMOLED fenix847mm.
//
//   node docs/research/probes/garmin-raster/make_faces.ts
//
// writes faces/<family>/face.yaml beside this file. Positions are pixel
// offsets from the screen's centre, inside the central 180 px square every
// target shows in full.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const TARGETS = ["fenix8solar47mm", "fenix8solar51mm", "fr955", "fenix847mm"];

/** A uuid from the family's name, so a face keeps its id from run to run. */
function id(family: string): string {
  let h = 2166136261;
  const hex: string[] = [];
  for (let i = 0; i < 16; i++) {
    for (const ch of family + i) h = Math.imul(h ^ ch.charCodeAt(0), 16777619) >>> 0;
    hex.push((h & 0xff).toString(16).padStart(2, "0"));
  }
  const s = hex.join("");
  return `${s.slice(0, 8)}-${s.slice(8, 12)}-4${s.slice(13, 16)}-8${s.slice(17, 20)}-${s.slice(20, 32)}`;
}

type Element = Record<string, unknown>;

const at = (dx: number, dy: number): string => `{ anchor: center, dx: ${dx}px, dy: ${dy}px }`;

function yamlOf(value: unknown, indent: number): string {
  const pad = " ".repeat(indent);
  return Object.entries(value as Element).map(([k, v]) => {
    if (typeof v === "object" && v !== null && !Array.isArray(v)) return `${pad}${k}:\n${yamlOf(v, indent + 2)}`;
    if (Array.isArray(v)) return `${pad}${k}:\n${v.map((item) => `${pad}  - ${item}`).join("\n")}`;
    return `${pad}${k}: ${v}`;
  }).join("\n");
}

function face(family: string, about: string, elements: Record<string, Element>, extra = "", targets = TARGETS): string {
  return `# garmin-raster probe: ${about}
# Generated by make_faces.ts; edit that, not this.

format: 2

face:
  id: ${id(family)}
  name: Raster ${family}
  version: 1.0.0

build:
  targets: [${targets.join(", ")}]

resources:
  palette:
    bg: "#000000"
    ink: "#FFFFFF"
${extra}
static:
  background:
    type: rectangle
    at: { anchor: center }
    size: { width: 100%, height: 100% }
    color: color.bg

elements:
${yamlOf(elements, 2)}
`;
}

/** `n` cells of a `columns`-wide grid, `pitch` apart, centred on the screen. */
function grid(n: number, columns: number, pitch: number): [number, number][] {
  const rows = Math.ceil(n / columns);
  return Array.from({ length: n }, (_, i) => [
    Math.round((i % columns - (columns - 1) / 2) * pitch),
    Math.round((Math.floor(i / columns) - (rows - 1) / 2) * pitch),
  ]);
}

const faces: Record<string, string> = {};

// fillCircle and drawCircle with a pen: radii 1..12, then pens 1..4 on odd and even radii.
{
  const els: Record<string, Element> = {};
  const fills = Array.from({ length: 12 }, (_, i) => i + 1);
  grid(fills.length, 6, 28).forEach(([dx, dy], i) => {
    els[`fill_r${fills[i]}`] = { type: "circle", at: at(dx, dy - 40), radius: `${fills[i]}px`, color: "color.ink" };
  });
  const outlines: [number, number][] = [];
  for (const pen of [1, 2, 3, 4]) for (const r of [8, 9]) outlines.push([pen, r]);
  grid(outlines.length, 4, 40).forEach(([dx, dy], i) => {
    const [pen, r] = outlines[i]!;
    els[`draw_r${r}_p${pen}`] = { type: "circle", at: at(dx, dy + 40), radius: `${r}px`, thickness: `${pen}px`, filled: "false", color: "color.ink" };
  });
  faces["circles"] = face("circles", "fillCircle radii 1-12, drawCircle pens 1-4 on radii 8 and 9", els);
}

// drawArc with a pen, across start angles and sweeps.
{
  const els: Record<string, Element> = {};
  const cases: [number, number, number][] = [];
  for (const pen of [1, 3]) for (const start of [0, 45, 100, 270]) for (const sweep of [30, 135]) cases.push([pen, start, sweep]);
  grid(cases.length, 4, 42).forEach(([dx, dy], i) => {
    const [pen, start, sweep] = cases[i]!;
    els[`arc_p${pen}_s${start}_w${sweep}`] = {
      type: "arc", at: at(dx, dy), radius: "14px", thickness: `${pen}px`, start_angle: `${start}deg`, sweep: `${sweep}deg`, color: "color.ink",
    };
  });
  faces["arcs"] = face("arcs", "drawArc, pens 1 and 3, four start angles, two sweeps", els);
}

// drawLine with a width, across angles.
{
  const els: Record<string, Element> = {};
  const cases: [number, number][] = [];
  for (const width of [1, 2, 3, 4]) for (const angle of [0, 15, 30, 45, 60, 90]) cases.push([width, angle]);
  grid(cases.length, 6, 30).forEach(([dx, dy], i) => {
    const [width, angle] = cases[i]!;
    const r = 11, t = angle * Math.PI / 180;
    const [ex, ey] = [Math.round(r * Math.cos(t)), Math.round(-r * Math.sin(t))];
    els[`line_w${width}_a${angle}`] = { type: "line", at: at(dx - ex, dy - ey), to: at(dx + ex, dy + ey), thickness: `${width}px`, color: "color.ink" };
  });
  faces["lines"] = face("lines", "drawLine, widths 1-4 at six angles", els);
}

// fillPolygon: triangles and a quad, at odd and even extents.
{
  const els: Record<string, Element> = {};
  const shapes: [string, [number, number][]][] = [
    ["tri_up", [[0, -9], [-8, 7], [8, 7]]], ["tri_down", [[0, 10], [-9, -8], [9, -8]]],
    ["tri_thin", [[0, -12], [-2, 12], [2, 12]]], ["quad", [[-9, -5], [6, -9], [9, 6], [-5, 9]]],
    ["tri_odd", [[0, -9], [-7, 6], [8, 7]]], ["sliver", [[-12, 0], [12, 1], [12, 2]]],
  ];
  grid(shapes.length, 3, 50).forEach(([dx, dy], i) => {
    const [name, points] = shapes[i]!;
    els[name] = { type: "polygon", points: points.map(([x, y]) => at(dx + x, dy + y)), color: "color.ink" };
  });
  faces["polygons"] = face("polygons", "fillPolygon: triangles, a quad and slivers", els);
}

// fillRoundedRectangle and drawRoundedRectangle; drawRectangle with a pen.
{
  const els: Record<string, Element> = {};
  const cases: [number, number, number, number][] = [];
  for (const [w, h] of [[20, 14], [21, 15]] as const) for (const r of [2, 3, 5]) for (const pen of [0, 2]) cases.push([w, h, r, pen]);
  grid(cases.length, 4, 40).forEach(([dx, dy], i) => {
    const [w, h, r, pen] = cases[i]!;
    els[`rr_${w}x${h}_r${r}${pen ? `_p${pen}` : ""}`] = {
      type: "rectangle", at: at(dx, dy - 20), size: `{ width: ${w}px, height: ${h}px }`, corner_radius: `${r}px`,
      ...(pen ? { thickness: `${pen}px`, filled: "false" } : {}), color: "color.ink",
    };
  });
  [1, 2, 3, 4].forEach((pen, i) => {
    els[`rect_p${pen}`] = { type: "rectangle", at: at(-60 + i * 40, 70), size: "{ width: 25px, height: 17px }", thickness: `${pen}px`, filled: "false", color: "color.ink" };
  });
  faces["rects"] = face("rects", "rounded rectangles filled and drawn, radii 2/3/5 on odd and even sizes; drawRectangle pens 1-4", els);
}

// fillEllipse and drawEllipse: odd and even radii, then pens 1-3.
{
  const els: Record<string, Element> = {};
  const fills: [number, number][] = [[10, 6], [11, 7], [16, 9], [17, 10], [20, 12], [21, 13]];
  grid(fills.length, 3, 50).forEach(([dx, dy], i) => {
    const [w, h] = fills[i]!;
    els[`fill_${w}x${h}`] = { type: "ellipse", at: at(dx, dy - 40), size: `{ width: ${w}px, height: ${h}px }`, color: "color.ink" };
  });
  const outlines: [number, number, number][] = [];
  for (const pen of [1, 2, 3]) for (const [w, h] of [[20, 12], [21, 13]] as const) outlines.push([w, h, pen]);
  grid(outlines.length, 3, 50).forEach(([dx, dy], i) => {
    const [w, h, pen] = outlines[i]!;
    els[`draw_${w}x${h}_p${pen}`] = {
      type: "ellipse", at: at(dx, dy + 40), size: `{ width: ${w}px, height: ${h}px }`, thickness: `${pen}px`, filled: "false", color: "color.ink",
    };
  });
  faces["ellipses"] = face("ellipses", "fillEllipse on odd and even sizes, drawEllipse pens 1-3", els);
}

// drawLine in the directions the lines face leaves out (left, down), and 2 and 4 px diagonals.
{
  const els: Record<string, Element> = {};
  const cases: [number, number][] = [];
  for (const width of [1, 3]) for (const angle of [120, 150, 210, 240, 300, 330]) cases.push([width, angle]);
  for (const width of [2, 4]) for (const angle of [15, 30, 45, 60, 135, 225, 315]) cases.push([width, angle]);
  grid(cases.length, 6, 30).forEach(([dx, dy], i) => {
    const [width, angle] = cases[i]!;
    const r = 11, t = angle * Math.PI / 180;
    const [ex, ey] = [Math.round(r * Math.cos(t)), Math.round(-r * Math.sin(t))];
    els[`line_w${width}_a${angle}`] = { type: "line", at: at(dx - ex, dy - ey), to: at(dx + ex, dy + ey), thickness: `${width}px`, color: "color.ink" };
  });
  faces["lines2"] = face("lines2", "drawLine widths 1 and 3 drawn left and down, widths 2 and 4 on diagonals", els);
}

// drawRoundedRectangle at the pens the rects face leaves out.
{
  const els: Record<string, Element> = {};
  const cases: [number, number, number, number][] = [];
  for (const pen of [1, 3, 4]) for (const r of [2, 3, 5]) cases.push([20, 14, r, pen]);
  for (const pen of [1, 3, 4]) cases.push([21, 15, 3, pen]);
  grid(cases.length, 3, 42).forEach(([dx, dy], i) => {
    const [w, h, r, pen] = cases[i]!;
    els[`rr_${w}x${h}_r${r}_p${pen}`] = {
      type: "rectangle", at: at(dx, dy), size: `{ width: ${w}px, height: ${h}px }`, corner_radius: `${r}px`,
      thickness: `${pen}px`, filled: "false", color: "color.ink",
    };
  });
  faces["rects2"] = face("rects2", "drawRoundedRectangle pens 1, 3 and 4", els);
}

// fillPolygon and drawLine on points turned at runtime: a radial pattern's copies land between pixels.
{
  const els: Record<string, Element> = {};
  for (const [name, count, part] of [
    ["tri_outer", 12, "{type: polygon, points: [{dx: -3px, dy: -80px}, {dx: 3px, dy: -80px}, {dx: 0px, dy: -68px}]}"],
    ["bar_mid", 9, "{type: polygon, points: [{dx: -2px, dy: -56px}, {dx: 2px, dy: -56px}, {dx: 2px, dy: -44px}, {dx: -2px, dy: -44px}]}"],
    ["line2_inner", 8, "{type: line, at: {dy: -36px}, to: {dy: -26px}, thickness: 2px}"],
    ["line1_core", 7, "{type: line, at: {dy: -19px}, to: {dy: -9px}, thickness: 1px}"],
  ] as const) {
    els[name] = { type: "pattern", pattern: "radial", count, at: "{ anchor: center }", start: "7deg", color: "color.ink", parts: [part] };
  }
  faces["rotated"] = face("rotated", "a radial pattern's polygons and lines, turned at runtime off the pixel grid", els);
}

// Large shapes, on fr955 alone: whether a rule fitted on small shapes holds out to the rim.
// Each face nests its shapes about the centre so many sizes fit; every shape stays inside radius 122.
const BIG = ["fr955"];
const offset = (r: number, deg: number): [number, number] => {
  const t = (deg * Math.PI) / 180;
  return [Math.round(r * Math.sin(t)), Math.round(-r * Math.cos(t))];
};
{
  const els: Record<string, Element> = {};
  [20, 26, 33, 40, 46, 53, 60, 66, 73, 80, 86, 93, 100, 106, 113, 120].forEach((r, i) => {
    const pen = [1, 2, 3][i % 3]!;
    els[`ring_r${r}_p${pen}`] = { type: "circle", at: at(0, 0), radius: `${r}px`, thickness: `${pen}px`, filled: "false", color: "color.ink" };
  });
  faces["big_circles"] = face("big_circles", "drawCircle radii 20-120, pens 1-3, nested", els, "", BIG);
}
{
  const els: Record<string, Element> = {};
  ([[-52, -52, 44], [52, -52, 37]] as const).forEach(([dx, dy, r]) => {
    els[`disc_r${r}`] = { type: "circle", at: at(dx, dy), radius: `${r}px`, color: "color.ink" };
  });
  els["oval_88x44"] = { type: "ellipse", at: at(-52, 52), size: "{ width: 88px, height: 44px }", color: "color.ink" };
  els["oval_41x81"] = { type: "ellipse", at: at(52, 52), size: "{ width: 41px, height: 81px }", color: "color.ink" };
  els["rr_45x33_r14"] = { type: "rectangle", at: at(0, 0), size: "{ width: 45px, height: 33px }", corner_radius: "14px", color: "color.ink" };
  faces["big_fills"] = face("big_fills", "fillCircle radii 37 and 44, fillEllipse semi-axes 44x22 and 21x41, fillRoundedRectangle radius 14", els, "", BIG);
}
{
  const els: Record<string, Element> = {};
  ([[60, 20], [90, 40], [120, 54], [150, 70], [180, 82], [200, 90], [220, 100]] as const).forEach(([w, h], i) => {
    const pen = [1, 2, 3][i % 3]!;
    els[`oval_${w}x${h}_p${pen}`] = { type: "ellipse", at: at(0, 0), size: `{ width: ${w}px, height: ${h}px }`, thickness: `${pen}px`, filled: "false", color: "color.ink" };
  });
  faces["big_ellipses"] = face("big_ellipses", "drawEllipse semi-axes 30x10 to 110x50, pens 1-3, nested", els, "", BIG);
}
{
  const els: Record<string, Element> = {};
  for (let k = 0; k < 24; k++) {
    const deg = 7 + k * 15, pen = [1, 2, 3, 4][k % 4]!;
    const [ix, iy] = offset(30, deg), [ox, oy] = offset(118, deg);
    // Half the lines drawn outward, half inward.
    const [from, to] = k % 8 < 4 ? [at(ix, iy), at(ox, oy)] : [at(ox, oy), at(ix, iy)];
    els[`ray_${deg}_p${pen}`] = { type: "line", at: from, to, thickness: `${pen}px`, color: "color.ink" };
  }
  faces["big_lines"] = face("big_lines", "drawLine 88 px long at 24 angles, pens 1-4, drawn outward and inward", els, "", BIG);
}
{
  const els: Record<string, Element> = {};
  ([[40, 28, 8], [66, 48, 13], [92, 66, 19], [118, 86, 25], [144, 104, 31], [170, 124, 37], [196, 142, 44]] as const).forEach(([w, h, r], i) => {
    const pen = [1, 2, 3][i % 3]!;
    els[`rr_${w}x${h}_r${r}_p${pen}`] = {
      type: "rectangle", at: at(0, 0), size: `{ width: ${w}px, height: ${h}px }`, corner_radius: `${r}px`,
      thickness: `${pen}px`, filled: "false", color: "color.ink",
    };
  });
  faces["big_rects"] = face("big_rects", "drawRoundedRectangle 40x28 to 196x142, corner radii 8-44, pens 1-3, nested", els, "", BIG);
}
{
  const els: Record<string, Element> = {};
  [30, 40, 50, 60, 70, 80, 90, 100, 110, 120].forEach((r, i) => {
    const pen = [1, 2, 3][i % 3]!, start = (17 + i * 41) % 360, sweep = [233, 97, 301, 158, 64][i % 5]!;
    els[`arc_r${r}_p${pen}`] = { type: "arc", at: at(0, 0), radius: `${r}px`, thickness: `${pen}px`, start_angle: `${start}deg`, sweep: `${sweep}deg`, color: "color.ink" };
  });
  faces["big_arcs"] = face("big_arcs", "drawArc radii 30-120, pens 1-3, odd starts and sweeps, nested", els, "", BIG);
}

// A run of drawText from a baked sheet, and the same with antialias.
{
  const font = "../../../../../../examples/showcase/assets/ChivoMono-Bold.ttf";
  faces["text"] = face("text", "drawText from a baked sheet, plain and anti-aliased", {
    plain: { type: "text", text: '"0123456789"', font: "font.mono", at: at(0, -20), color: "color.ink" },
    smooth: { type: "text", text: '"0123456789"', font: "font.smooth", at: at(0, 20), color: "color.ink" },
  }, `  fonts:
    mono: { source: ${font}, size: 24px }
    smooth: { source: ${font}, size: 24px, antialias: true }
`);
}

// A swatch strip: how the simulator quantises and dithers colours off the 64.
{
  const els: Record<string, Element> = {};
  const colours = ["#000000", "#555555", "#AAAAAA", "#FFFFFF", "#FF0000", "#00FF00", "#0000FF", "#FF5500",
    "#808080", "#C0C0C0", "#123456", "#FF8000", "#7F7F7F", "#2A2A2A", "#D4D4D4", "#3366CC"];
  let palette = "";
  grid(colours.length, 4, 36).forEach(([dx, dy], i) => {
    palette += `    s${i}: "${colours[i]}"\n`;
    els[`swatch_${i}`] = { type: "rectangle", at: at(dx, dy), size: "{ width: 30px, height: 30px }", color: `color.s${i}` };
  });
  faces["swatches"] = face("swatches", "sixteen swatches, on and off the 64 MIP colours", els, palette);
}

for (const [family, text] of Object.entries(faces)) {
  const dir = join(HERE, "faces", family);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "face.yaml"), text);
}
console.log(`wrote ${Object.keys(faces).length} faces to ${join(HERE, "faces")}`);
