#!/usr/bin/env python3
"""Generate examples/features/profile/face.yaml: the same sixteen drawables
in three layouts -- no `outline:`, a 1px ring and a 2px ring -- for
`wfb build --profile` to time on a watch (`docs/guide/
preview-and-cli.md` "Profiling").

Three copies of one design differ only in their ids and their `outline:`,
which is exactly what a generator is for; the output is committed so the
face builds without running this.  Run from the repo root:

    ./.venv/bin/python tools/gen-profile-face.py
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "examples/features/profile/face.yaml"

#: Grid cell centres, as `dx`/`dy` percentages of the screen.
COLUMNS = (-27, -9, 9, 27)
ROWS = (-22, -5, 12, 29)

#: ``(name, element body)`` in grid order.  `{at}` is the cell's anchor;
#: `{ring}` is the variant's `outline:` line (or nothing).
DRAWABLES = [
    ("disc", """type: circle
    at: {at}
    radius: 6%r
    color: color.fill"""),
    ("card", """type: rectangle
    at: {at}
    size: {{ width: 12%, height: 7% }}
    color: color.fill"""),
    ("pill", """type: rectangle
    at: {at}
    size: {{ width: 12%, height: 7% }}
    corner_radius: 4px
    color: color.fill"""),
    ("egg", """type: ellipse
    at: {at}
    size: {{ width: 13%, height: 8% }}
    color: color.fill"""),
    ("hoop", """type: circle
    at: {at}
    radius: 6%r
    thickness: 3px
    filled: false
    color: color.fill"""),
    ("label", """type: text
    text: "12:34"
    font: FONT_XTINY
    at: {at}
    color: color.fill"""),
    ("arc", """type: arc
    at: {at}
    radius: 6%r
    thickness: 3px
    start_angle: 300deg
    sweep: 120deg
    color: color.fill"""),
    ("tri", """type: polygon
    points:
      - {{ {anchor}, dx: {dx_l}%, dy: {dy_b}% }}
      - {{ {anchor}, dx: {dx}%, dy: {dy_t}% }}
      - {{ {anchor}, dx: {dx_r}%, dy: {dy_b}% }}
    color: color.fill"""),
    ("rule", """type: line
    at: {{ {anchor}, dx: {dx_l}%, dy: {dy}% }}
    to: {{ {anchor}, dx: {dx_r}%, dy: {dy}% }}
    thickness: 2px
    color: color.fill"""),
    ("digits", """type: text
    text: "12:34"
    font: font.digits
    at: {at}
    color: color.fill"""),
    ("alarm", """type: icon
    icon: alarm
    size: 12%r
    at: {at}
    color: color.fill"""),
    ("ticks", """type: pattern
    pattern: radial
    at: {at}
    count: 8
    step: 45deg
    color: color.fill
    parts:
      - {{ type: line, at: {{ dy: -9%r }}, to: {{ dy: -5%r }}, thickness: 2px }}"""),
    ("battery", """type: gauge
    style: arc
    value: system.battery
    max: 100
    at: {at}
    radius: 6%r
    thickness: 3px
    start_angle: 240deg
    sweep: 240deg
    color: color.fill
    track_color: color.track"""),
    ("steps", """type: gauge
    style: bar
    value: system.battery
    max: 100
    at: {at}
    size: {{ width: 13%, height: 3% }}
    color: color.fill
    track_color: color.track"""),
    ("badge", """type: group
    at: {at}
    size: {{ width: 16%, height: 8% }}
    children:
      {id}_icon: {{ type: icon, icon: heart, size: 8%r, at: {{ anchor: left }}, align: left, color: color.fill }}
      {id}_value: {{ type: text, text: "72", font: FONT_XTINY, at: {{ anchor: right }}, align: right, color: color.fill }}"""),
    ("hands", """type: hands
    set: mini
    at: {at}"""),
]

VARIANTS = [
    ("plain", "No outline", None),
    ("ring1", "1px outline", 1),
    ("ring2", "2px outline", 2),
]

HEADER = """\
# Generated by tools/gen-profile-face.py -- edit that, not this.
#
# A profiling face for `outline:`: sixteen drawables on a 4x4
# grid -- the three grown shapes, every stamped shape, text in a baked font
# (ringed from its baked ring font) and in a system font (stamped), an icon, a
# pattern, two gauges, hands and a group -- in three layouts: no outline, a
# 1px ring and a 2px ring.  Switch between them with the watch's style
# setting (the native editor, or the generated settings menu on fr955).
#
# Build it instrumented, sideload it and read the numbers off the watch:
#
#     ./wfb.py build examples/features/profile/face.yaml --profile
#
# Each element's average draw time per call, in microseconds, appears above
# it; the top line is the last frame's time, the app's memory, and the
# empty-loop baseline to subtract.  An outlined group's ring pass is timed
# on its own.  See docs/guide/preview-and-cli.md, "Profiling".
#
# yaml-language-server: $schema=../../../schema/wfb-face-2.schema.json

format: 2

face:
  id: 5c3a9e82-7d14-4b6f-a0e3-8f2d1c6b9a47
  name: Feature Profile
  version: 1.0.0

build:
  targets:
    - fenix8solar47mm
    - fenix8solar51mm
    - fr955

resources:
  fonts:
    digits:
      source: ../outline/assets/ChivoMono-Bold.ttf
      size: 8%r

  palette:
    bg: "#000000"
    fill: "#AA00FF"
    ring: "#FFFF00"
    track: "#555555"

  hand_sets:
    mini:
      hour:
        color: color.fill
        parts:
          - type: polygon
            points: [{ dx: -2%r, dy: 2%r }, { dy: -7%r }, { dx: 2%r, dy: 2%r }]
      minute:
        color: color.fill
        parts:
          - { type: rectangle, at: { dy: -4%r }, size: { width: 1%r, height: 10%r } }

config:
  style:
    default: plain
    choices:
"""


def cell(index: int) -> tuple[int, int]:
    return COLUMNS[index % 4], ROWS[index // 4]


def element(name: str, body: str, index: int, suffix: str, ring: int | None) -> str:
    dx, dy = cell(index)
    ident = f"{name}_{suffix}"
    text = body.format(
        at=f"{{ anchor: center, dx: {dx}%, dy: {dy}% }}", anchor="anchor: center",
        dx=dx, dy=dy, dx_l=dx - 6, dx_r=dx + 6, dy_t=dy - 4, dy_b=dy + 4, id=ident)
    first, *rest = text.split("\n")
    lines = [f"      {ident}:", f"        {first}"] + [f"    {line}" for line in rest]
    if ring is not None:
        lines.append("        outline: color.ring" if ring == 1 else
                     f"        outline: {{ color: color.ring, width: {ring} }}")
        if name in ("digits", "label"):
            lines += ["        lint:",
                      "          allow: [text-outline-interior]",
                      "          reason: \"a ringed, filled numeral: the interior is meant to show\""]
    return "\n".join(lines)


def main() -> None:
    out = [HEADER]
    for key, label, _ in VARIANTS:
        out.append(f"      {key}: {{ label: \"{label}\", layout: {key} }}\n")
    out.append("""
static:
  background:
    type: rectangle
    at: { anchor: center }
    size: { width: 100%, height: 100% }
    color: color.bg

layouts:
""")
    for key, _, ring in VARIANTS:
        out.append(f"  {key}:\n    elements:\n")
        for index, (name, body) in enumerate(DRAWABLES):
            out.append(element(name, body, index, key, ring) + "\n\n")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(out).rstrip() + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
